# Test goal: build with HIP to check HIP compilation
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   Compiler: gcc-11
#   GPU: HIP
#   Scope: configure, build
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 24.04
#   Build type: RelWithAssert
#   Compiler: gcc-11
#   MPI: OpenMPI (AMD build)
#   SIMD: AVX2_256

gromacs:gcc-11-hip-622-mpi:release:configure:
  extends:
    - .gromacs:base:release:configure
    - .use-gcc:base
    - .use-hip
    - .use-mpi
  rules:
    - !reference [.rules:nightly-only-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-gcc-11-rocm-6.2.2
  variables:
    CMAKE: /usr/local/cmake-3.28.0/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=AVX2_256"
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithAssert"
    CMAKE_EXTRA_OPTIONS: "-DGMX_HIP_TARGET_ARCH=gfx906 -DGMX_GPU_FFT_LIBRARY=ROCFFT"
    COMPILER_MAJOR_VERSION: 11
    RELEASE_BUILD_DIR: release-builds-gcc-rocm
  dependencies:
    - archive:package
    - regressiontests:package
    - prepare-release-version

gromacs:gcc-11-hip-622-mpi:release:build:
  extends:
    - .gromacs:base:build
    - .use-gcc:base
    - .use-ccache
  stage: release-build
  rules:
    - !reference [.rules:nightly-only-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-gcc-11-rocm-6.2.2
  variables:
    CMAKE: /usr/local/cmake-3.28.0/bin/cmake
    BUILD_DIR: release-builds-gcc-rocm
  needs:
    - job: gromacs:gcc-11-hip-622-mpi:release:configure

gromacs:gcc-11-hip-622-mpi:release:test:
  extends:
    - .gromacs:base:test
  rules:
    - !reference [.rules:nightly-only-for-release, rules]                 
  stage: release-tests
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-gcc-11-rocm-6.2.2
  variables:
    CMAKE: /usr/local/cmake-3.28.0/bin/cmake
    BUILD_DIR: release-builds-gcc-rocm
    GPU_VENDOR: "AMD"
    GPU_COUNT: 2
    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
  tags:
    - amd-gpu-gfx906
  allow_failure: true   # allow job failure w/o failing pipeline, since no redundant hardware
  needs:
    - job: gromacs:gcc-11-hip-622-mpi:release:configure
    - job: gromacs:gcc-11-hip-622-mpi:release:build

gromacs:gcc-11-hip-622-mpi:release:regressiontest:
  extends:
    - .gromacs:base:regressiontest
  rules:
    - !reference [.rules:nightly-only-for-release, rules]                     
  stage: release-tests
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-gcc-11-rocm-6.2.2
  variables:
    CMAKE: /usr/local/cmake-3.28.0/bin/cmake
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 4
    REGRESSIONTEST_OMP_RANK_NUMBER: 2
    REGRESSIONTEST_PME_RANK_NUMBER: 0
    REGRESSIONTEST_PARALLEL: "-np"
    GPU_VENDOR: "AMD"
    GPU_COUNT: 2
  tags:
    - amd-gpu-gfx906
  allow_failure: true   # allow job failure w/o failing pipeline, since no redundant hardware
  needs:
    - job: gromacs:gcc-11-hip-622-mpi:release:build
    - job: regressiontests:package
