# Test goal: Newest ICPX build with OpenCL, release build
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   Compiler: ICPX newest supported
#   Build type: RelWithAssert
#   FFT: MKL
#   GPU: OpenCL
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 22.04
#   Compiler: ICPX 2025.1
#   MPI: thread_MPI
#   SIMD: AVX2_256
#   Parallelism nt/ntomp: 4/2 (unit tests)
#   Parallelism nt/ntomp: 2/1 (regression tests)

gromacs:oneapi-2025.1-opencl:release:configure:
  extends:
   - .gromacs:base:release:configure
   - .use-oneapi:base
   - .use-opencl
  rules:
   - !reference [.rules:nightly-only-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-oneapi-2025.1-intel-compute-runtime
  variables:
    CMAKE: /usr/local/cmake-3.30.3/bin/cmake
    COMPILER_MAJOR_VERSION: 2025
    RELEASE_BUILD_DIR: release-builds-oneapi

gromacs:oneapi-2025.1-opencl:release:build:
  extends:
    - .gromacs:base:build
    - .use-oneapi:base
    - .use-opencl
    - .use-ccache
  rules:
    - !reference [.rules:nightly-only-for-release, rules]
  stage: release-build
  variables:
    CMAKE: /usr/local/cmake-3.30.3/bin/cmake
    BUILD_DIR: release-builds-oneapi
    COMPILER_MAJOR_VERSION: 2024
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-oneapi-2025.1-intel-compute-runtime
  needs:
    - job: gromacs:oneapi-2025.1-opencl:release:configure

gromacs:oneapi-2025.1-opencl:release:test:
  extends:
    - .gromacs:base:test
    - .use-oneapi:base
  rules:
    - !reference [.rules:nightly-only-for-release, rules]
  stage: release-tests
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-oneapi-2025.1-intel-compute-runtime
  variables:
    CMAKE: /usr/local/cmake-3.30.3/bin/cmake
    BUILD_DIR: release-builds-oneapi
  needs:
    - job: gromacs:oneapi-2025.1-opencl:release:configure
    - job: gromacs:oneapi-2025.1-opencl:release:build

gromacs:oneapi-2025.1-opencl:release:regressiontest:
  extends:
    - .gromacs:base:regressiontest
    - .use-oneapi:base
  rules:
    - !reference [.rules:nightly-only-for-release, rules]
  stage: release-tests
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-oneapi-2025.1-intel-compute-runtime
  variables:
    CMAKE: /usr/local/cmake-3.30.3/bin/cmake
    BUILD_DIR: release-builds-oneapi
    REGRESSIONTEST_PME_RANK_NUMBER: 0
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 2
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
  needs:
    - job: gromacs:oneapi-2025.1-opencl:release:build
    - job: regressiontests:package
