# Test goal: Simple Clang C++20 build with libc++ and no GPU
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   Compiler: Clang
#   GPU: no
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 22.04
#   Build type: Debug
#   Compiler: Clang 14
#   MPI: thread_MPI
#   SIMD: AVX2_256
#   FFT: FFTW3
#   Parallelism nt/ntomp: 4/2
#   TNG: build without TNG
#   Colvars: build without internal colvars support
#.  PLUMED: build without PLUMED support

gromacs:clang-14:cxx-20:configure:
  extends:
    - .gromacs:base:configure
    - .use-clang:base
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-14-cuda-12.1.0-openmpi-5.0.3
  variables:
    CMAKE: /usr/local/cmake-3.29.8/bin/cmake
    CMAKE_EXTRA_OPTIONS: "-DCMAKE_CXX_FLAGS='-stdlib=libc++' -DCMAKE_CXX_STANDARD=20 -DGMX_INSTALL_LEGACY_API=ON -DGMX_USE_TNG=OFF -DGMX_USE_COLVARS=NONE -DGMX_USE_PLUMED=OFF"
    COMPILER_MAJOR_VERSION: 14

gromacs:clang-14:cxx-20:build:
  extends:
    - .gromacs:base:build
    - .before_script:default
    - .use-ccache
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-14-cuda-12.1.0-openmpi-5.0.3
  variables:
    CMAKE: /usr/local/cmake-3.29.8/bin/cmake
  needs:
    - job: gromacs:clang-14:cxx-20:configure

gromacs:clang-14:cxx-20:test:
  extends:
    - .gromacs:base:test
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-14-cuda-12.1.0-openmpi-5.0.3
  variables:
    CMAKE: /usr/local/cmake-3.29.8/bin/cmake
    GMX_FORCE_UPDATE_DEFAULT_CPU: 1
  needs:
    - job: gromacs:clang-14:cxx-20:build

gromacs:clang-14:cxx-20:regressiontest:
  extends:
    - .gromacs:base:regressiontest
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-14-cuda-12.1.0-openmpi-5.0.3
  variables:
    CMAKE: /usr/local/cmake-3.29.8/bin/cmake
  needs:
    - job: gromacs:clang-14:cxx-20:build
    - job: regressiontests:prepare
