#!/bin/sh
# This is a script to create all the configuration files when
# you compile from the CVS source. You should NOT use it to
# compile the distribution.
aclocal
# fix for OSX producing debug directories; replace rm -f with rm -rf in built-in scripts
cat aclocal.m4 | sed -e 's/rm="rm -f"/rm="rm -rf"/' | sed -e 's/rm -f /rm -rf /' > aclocal.tmp && mv aclocal.tmp aclocal.m4
autoheader
automake
autoconf
