#!/bin/sh
# This is a stub script to help developers during the final
# part of the change-over from autotools to CMake.

echo "\
The use of autotools for installing GROMACS is deprecated for 4.6 onwards
Please switch to CMake. Check out
http://www.gromacs.org/Documentation/Installation_Instructions
for instructions."
