#!/bin/csh -f

set THISDIR	= `pwd`
set MANDIR	= progman
set TEXMAN	= $THISDIR/$MANDIR
set INDEX	= $TEXMAN/all.tex

cd $GMXHOME/bin/$GMXCPU
set PROGRAMS    = 
foreach program ( `\ls -1 | grep -v "#"` )
  if ( ( $program != average ) && ( $program != luck ) && ( $program != my_dssp ) ) then
    set PROGRAMS = "$PROGRAMS $program"
  endif
end

if ( ! -d $TEXMAN ) mkdir $TEXMAN
cd $TEXMAN
\rm *
touch $INDEX
foreach prog ( $PROGRAMS )
  set PROG = $GMXHOME/bin/$GMXCPU/$prog
  if ( ( -x $PROG ) && ( $prog != "my_dssp" ) && ( $prog != "luck" ) ) then
    echo -n "$prog "
    $PROG -quiet -man tex >& /dev/null
    endif
    if ( -f $prog.tex ) then
      grep -v "Use dialog box GUI to edit command line options" $prog.tex >! mkman_temp.tex
      grep -v "Set non blocking priority" mkman_temp.tex >! $prog.tex
      \rm mkman_temp.tex
      echo "\\input{"$MANDIR"/"$prog"}" >> $INDEX
    endif
  endif
end

cat >! $TEXMAN.tex << EOD
\chapter{Manual Pages}
\label{app:progman}

{\small
\input{$MANDIR/all}
}
EOD
echo ""

cd $THISDIR

#last line
