#!/bin/csh -f


if ( $#argv < 1 ) then
  echo "Error: provide the GROMACS bin directory as first argument."
  exit
endif

set BINDIR = $1

set THISDIR	= `pwd`
set MANDIR	= progman
set TEXMAN	= $THISDIR/$MANDIR
set INDEX	= $TEXMAN/all.tex

cd $BINDIR
echo -n "Generating manpage from gromacs binaries in "
pwd
set PROGRAMS    = [a-z]*

if ( ! -d $TEXMAN ) mkdir $TEXMAN
cd $TEXMAN
\rm -f *
touch $INDEX
foreach program ( $PROGRAMS )
  set PROG = $BINDIR/$program
  if ( ( -x $PROG ) && ( $program != "my_dssp" ) && ( $program != "GMXRC" ) && ( $program != "completion.csh" ) && ( $program != "completion.zsh" ) && ( $program != "average" ) && ( $program != "completion.bash" ) && ( $program != "luck" ) ) then
    echo -n "$program "
    $PROG -quiet -man tex >& /dev/null
    endif
    if ( -f $program.tex ) then
      grep -v "Use dialog box GUI to edit command line options" $program.tex >! mkman_temp.tex
      grep -v "Set non blocking priority" mkman_temp.tex >! $program.tex
      \rm mkman_temp.tex
      echo "\input{"$MANDIR"/"$program"}" >> $INDEX
    endif
  endif
end

cat >! $TEXMAN.tex << EOD
\chapter{Manual Pages}
\label{app:progman}

{\small
%options.tex is created by the GROMACS binary options in the contrib directory 
\input{options.tex}
}
{\small
\input{$MANDIR/all}
}
EOD
echo ""

cd $THISDIR

#last line
