#!/bin/bash

if [[ $# != 1 ]]; then
  echo "Error: usage is 'mkman GMXBIN' where GMXBIN is the .../bin directory where GROMACS binaries are installed"
  exit
fi

GMXBIN=$1

PROGMAN=progman
MANDIR=${PROGMAN}
INDEX=${MANDIR}/all.tex
OPTIONS_PROGRAM_NAME=g_options

PROGRAMS=$(cd ${GMXBIN}; ls)
echo "Generating manpages from GROMACS binaries in ${GMXBIN}"

\rm -rf ${MANDIR}
mkdir ${MANDIR}

touch ${INDEX}
for PROG in $PROGRAMS; do
    # strip off .exe suffixes (good for Cygwin)
    program=${PROG%.exe}

    if [ -x "${GMXBIN}/${PROG}" -a \
	"$PROG" != "GMXRC" -a \
        "$PROG" != "GMXRC.bash" -a \
        "$PROG" != "GMXRC.csh" -a \
        "$PROG" != "GMXRC.zsh" -a \
        "$program" != "average" -a \
        "$program" != "g_luck" -a \
        "$program" != "${OPTIONS_PROGRAM_NAME}" -a \
	"$program" != "my_dssp" -a \
        "$PROG" != "completion.csh" -a \
        "$PROG" != "completion.zsh" -a \
        "$PROG" != "completion.bash" -a \
        "$PROG" != "demux.pl" -a \
        "$PROG" != "xplor2gmx.pl" ]; then
	echo -n "$program "
	${GMXBIN}/$PROG -quiet -man tex >& /dev/null
	if [ -f ${program}.tex ]; then
	    grep -v "Use dialog box GUI to edit command line options" ${program}.tex > mkman_temp.tex
	    grep -v "non blocking priority" mkman_temp.tex > ${program}.tex
	    \rm mkman_temp.tex
	    mv ${program}.tex ${MANDIR}/
	    echo "\input{${MANDIR}/${program}}" >> $INDEX
	else
	    echo
	    echo "${program}.tex was not created"
	fi
    fi
done

cat > ${PROGMAN}.tex << EOD
\chapter{Manual Pages}
\label{app:progman}

{\small
%${OPTIONS_PROGRAM_NAME}.tex is created by the GROMACS installed binary ${OPTIONS_PROGRAM_NAME}
\input{${OPTIONS_PROGRAM_NAME}.tex}
}
{\small
\input{${MANDIR}/all}
}
EOD
echo ""

#last line
