#!/bin/bash

OPTIONS_PROGRAM_NAME="g_options"

INSTALLED_OPTIONS_PROGRAM_NAME=$(find $1 -name \*${OPTIONS_PROGRAM_NAME}\*)
if [[ "x${INSTALLED_OPTIONS_PROGRAM_NAME}" == "x" ]]; then
    echo "Error: Can't find the executable '${OPTIONS_PROGRAM_NAME}' in GMXBIN directory $1"
    echo "I need it to create a LaTeX file."
    exit 1
else
    ${INSTALLED_OPTIONS_PROGRAM_NAME} -hidden -man tex 2> /dev/null
fi

# We don't want the section header to actually be g_options
sed -i -e "s/${OPTIONS_PROGRAM_NAME}/options/g" ${OPTIONS_PROGRAM_NAME}.tex
