#!/bin/csh -f

#
# This script creates the html manual pages in
# the html subdirectory below the current working
# directory.
#

echo "Generating html manual for GROMACS programs"
echo "-------------------------------------------"

if ( $#argv < 1 ) then
  echo "Error: provide the binary directory as first argument."
  exit
endif

set GMXBINDIR = $1

set 	dir = $cwd

setenv VER 	3.0
setenv HTML     $cwd/html
if ( ! -d $HTML ) mkdir $HTML
setenv MANDIR   online
setenv HTMLOL   $HTML/$MANDIR
if ( ! -d $HTMLOL ) mkdir $HTMLOL
setenv	INDEX	$HTML/$MANDIR.html
if ( -f $INDEX ) \rm $INDEX

cat > $INDEX << EOD
<HTML>
<TITLE>GROMACS $VER Manual </TITLE>
<BODY text="#000000" bgcolor="#FFFFFF">
<H1>GROMACS $VER manual</H1>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=10>
<TR>
<TD VALIGN=top WIDTH="25%">
<h3>General</h3>
<A HREF="changes$VER.html">New features</a>
<br>
<br><A HREF="$MANDIR/getting_started.html">Getting Started</a>
<br>
<br><A HREF="$MANDIR/flow.html" >Flow chart</a>
<br>
<br><A HREF="$MANDIR/files.html" >File formats</a>
<br>
<br><A HREF="$MANDIR/mdp_opt.html" >mdp options</a>
</TD>
<TD VALIGN=top WIDTH="75%">
<h3>Programs</h3>
<multicol cols=5> 
<A HREF="$MANDIR/options.html" >Options</a>
<br>
EOD


cd $GMXBINDIR
set PROGRAMS = [a-z]*
cd $dir

foreach program ( $PROGRAMS )
  if ( ( -x $GMXBINDIR/$program ) && ( $program != "my_dssp" ) && ( $program != "luck" ) ) then
    echo -n "$program "
    cd $HTMLOL
    $GMXBINDIR/$program -quiet -man html >& /dev/null
      cat >> $INDEX << EOK
<br><a href="$MANDIR/$program.html">$program</a>
EOK
    endif
  endif
end

cat >> $INDEX << EOM
</multicol>
</TD>
</TR>
</TABLE>
</BODY>
</HTML>
EOM

echo ""
echo ""
echo "New html pages in $HTML"
echo "file:$INDEX"

#last line
