#!/bin/csh -f

if ( $#argv < 1 ) then
  echo "Error: provide the binary directory as first argument."
  exit
endif

set GMXBINDIR = $1

set dir = $cwd

set VER		= 3.0
set MANDIR	= online
set HTML	= $cwd/html
set HTMLOL	= $HTML/$MANDIR
set HTMLIDX	= $HTML/$MANDIR.html
set TEXDIR	= $cwd/doc
set TEXIDX	= $TEXDIR/proglist.tex
set PROGFILE	= programs.txt

set GENERAL 	= "getting_started:Getting_Started flow:Flow_Chart files:File_Formats mdp_opt:mdp_options"

cd $GMXBINDIR
set PROGRAMS = [a-z]*
cd $dir

echo "generating html page $HTMLIDX"

if ( ! -d $HTML ) mkdir $HTML
if ( -f $HTMLIDX ) \rm $HTMLIDX
touch $HTMLIDX

if ( ! -d $TEXDIR ) mkdir $TEXDIR

cat > $HTMLIDX << EOD
<HTML>
<TITLE>GROMACS $VER Online Reference </TITLE>
<LINK rel=stylesheet href="online/style.css" type="text/css">
<BODY text="#000000" bgcolor="#FFFFFF" link="#0000EF" vlink="#650065" alink="#FF0000">
<H2>GROMACS $VER Online Reference</H2>
<HR>
<P>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=10>
<TR>
<TD VALIGN=top WIDTH="25%">
<h3>General</h3>
EOD
foreach i ( $GENERAL )
  set file = `echo $i | cut -d: -f1`
  set desc = `echo $i | cut -d: -f2 | sed 's/_/ /g'`
  echo "<A HREF="\""$MANDIR/"$file".html"\"">"$desc"</a>" >> $HTMLIDX
  echo "<br><br>" >> $HTMLIDX
end
cat >> $HTMLIDX <<EOD
<A HREF="gmxfaq.html">FAQ</a>
<br>
<br><A HREF="http://www.gromacs.org">GROMACS homepage</A>
</TD>
<TD VALIGN=top WIDTH=75%>
<h3>Programs</h3>
<multicol cols=5> 
<A HREF="$MANDIR/options.html">Options</a>
<br>
EOD
foreach program ( $PROGRAMS )
  echo "<br><a href="$MANDIR/$program.html">$program</a>" >> $HTMLIDX
end
cat >> $HTMLIDX << EOD
</multicol>
</TD>
</TR>
</TABLE>
<HR>
<h3>Programs by Topic</h3>
<multicol cols=3>
EOD
awk -F '|' -v mandir=$MANDIR '{\
  if (NF) {\
    if ( $1 == "HEAD" ) {\
      hnr++;\
      printf("<A HREF=\"#HNR%d\">%s</A><br>\n",hnr,$2);\
    }\
  }\
}' $PROGFILE >> $HTMLIDX
echo "</multicol> " >> $HTMLIDX
awk -F '|' -v mandir=$MANDIR '{\
  if (NF) {\
    if ( $1 == "HEAD" ) {\
      hnr++;\
      printf("\n<A NAME=\"HNR%d\">\n",hnr);\
      printf("<TABLE CELLSPACING=1>\n<TR><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");\
      printf("<TR><TD COLSPAN=2><b>%s</b>\n",$2);\
    } else if ( $1 == "END" ) {\
      printf("</TABLE>\n");\
    } else {\
      printf("<TR><TD><A HREF=\"%s/%s.html\">%s</A><TD>%s\n",mandir,$1,$1,$2);\
    }\
  }\
}' $PROGFILE >> $HTMLIDX
cat >> $HTMLIDX <<EOD
<p>
<hr>
<div ALIGN=RIGHT>
<font size="-1"><a href="http://www.gromacs.org">http://www.gromacs.org</a></font><br>
<font size="-1"><a href="mailto:gromacs@gromacs.org">gromacs@gromacs.org</a></font><br>
</body>
</html>
EOD

echo "generating latex page $TEXIDX"

if ( -f $TEXIDX ) \rm $TEXIDX
touch $TEXIDX

echo "\\begin{description}" >> $TEXIDX
awk -F '|' -v mandir=$MANDIR -v longest="mk\\_angndx" '{\
  gsub("_","\\_",$0);\
  gsub("%","\\%",$0);\
  if (NF) {\
    if ( $1 == "LONGEST" ) {\
      longest = $2;\
    } else if ( $1 == "HEAD" ) {\
      printf("\\item {\\large\\bf %s}\n",$2);\
      printf("\\vspace{-2ex}\\begin{tabbing}\n");\
      printf("{\\bf %s} \\= \\kill\n",longest);\
    } else if ( $1 == "END" ) {\
      printf("\\end{tabbing}\\vspace{-2ex}\n\n");\
    } else {\
      printf("{\\bf %s} \\> %s \\\\\n",$1,$2);\
    }\
  }\
}' $PROGFILE | sed -e 's/e\.g\./{\\eg}/g' >> $TEXIDX
echo "\end{description}" >> $TEXIDX

#last line
