#
#	@(#) Makefile.SGI 1.4 8/4/97
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on Power Challenge using power C and
#	power Fortran
#
#	See README file for info
#
SYSDEFS		= -DHAVE_IDENT -DHAVE_ULONG -D__INLINE_INTRINSICS -DHAVE_STRDUP -D_SGI_ -DHAVE_STRCASECMP -DSIMPLEWATER 

#
#	USER MODIFIABLE SECTION
#
# If you want to use fortran innerloops set this to yes
# For most machines this will improve the performances quite a bit
# because C-compilers are not as good as Fortran compilers
USEF77		= yes
#
# If you want to run in *** P A R A L L E L ***
# please select either PVM or MPI, check with your local hacker
# to see what's installed at your site. If you have neither,
# set both to no. If you select both, something will break!!!
#
USE_PVM3	= no
USE_MPI		= no
#
# If you want to use compressed data files set this to yes
# This uses the xdr libraries of your UNIX system, which is virtually
# Allways present, because it is necessary for NFS (network file system)
#
USE_XDR		= yes
#
# If you want to use the GMX/Motif user interface (and if you have Motif
# or lesstif (www.lesstif.org) installed, uncomment this one.
HAVE_MOTIF	= yes
#
# Note that these variables are also used in Makefile.std
# If something does not work, please check out the link command line
# in that file (e.g. for PVM)
#
CC		= cc
CCC		= CC
F77		= f77

OPT		= -O3 -OPT:IEEE_arithmetic=3 -OPT:rsqrt=ON -SWP:loop_overhead -INLINE:=ON -LNO:opt=1 -LNO:ou_further=3 -OPT:Olimit=0:roundoff=3:alias=typed -fullwarn
# Some options for the 7.30 compilers
#OPT		+= -SWP:heur=fdms,nhms,fdnms
# All warnings except unused vars: -fullwarn -woff 1174
CFLAGS		= $(ABI) $(OPT) -woff 1174 -woff 1233
CCFLAGS		= $(ABI) $(OPT) -woff 1174 -DHAVE_BOOL 
FFLAGS		= $(ABI) $(OPT) -OPT:cray_ivdep=TRUE
#       Add the two GCM options to the FFLAGS for a 7% performance
#       increase, if your compiler supports these options. As far
#       as we know the 7.1 compiler does support these options and
#       the 7.2 does not.
#FFLAGS		+= -GCM:aggressive_speculation -GCM:array_speculation

LDFLAGS		= -L$(LIBDIR) $(ABI) 
LD		= $(CC) $(LDFLAGS)
CCLD		= $(CCC) $(LDFLAGS)
FLD		= $(F77) $(LDFLAGS)

USE_SGI_FPE	= no
ifeq ($(HAVE_MOTIF),yes)
SYSDEFS		+= -DHAVE_MOTIF
SYSLIBS		= -lm -lXm -lXt -lX11
XLIBS		= $(SYSLIB)
else
SYSLIBS		= -lm
XLIBS		= -lX11
endif

ifeq ($(USE_SGI_FPE),yes)
	SYSDEFS += -DUSE_SGI_FPE
	SYSLIBS += -lfpe
endif

CCSHAREIT       = $(CC) $(LDFLAGS) -shared -all \
                  -quickstart_info -check_registry /usr/lib/so_locations \
                  -soname $(SONAME) -o $(LIBDIR)/$(SONAME) *.o
SHAREIT		= (cd $(LIBDIR); ar x $(LIB); $(CCSHAREIT) ; $(RM) *.o)
LINKSTATIC      = -Bstatic
LINKDYNAMIC     = -Bdynamic
RANLIB		= echo
X11INC		= -I/usr/include/X11





