#
#	@(#) Makefile.386 1.28 8/27/96
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on a i386 processor using SCO operating system
#	and gcc compiler
#
# compiler, linker & archiver
#
SYSDEFS		= -DHAVE_IDENT -DHAVE_SEMA -DHAVE_ULONG -DUSE_XDR
CC		= gcc
CFLAGS		= -g -ansi 
LD		= $(CC) $(LDFLAGS)
LDFLAGS		= -L$(LIBDIR)
SYSLIBS		= $(LINKLIB) -lrpc -lsocket -lm
GET		:=get
XLIBS		= $(SYSLIBS) -lX11 -lsocket
AR		= ar ruvls
RANLIB		= echo
X11INC		= -I/usr/include/X11

#
#	USER MODIFIABLE SECTION
#
#WARNING
#WARNING The fortran innerloop is tested only on SUN and SGI machines
#WARNING				
# 	If you want to use fortran innerloops set this to yes
USEF77		= no
#	If you don't have PVM (parallel virtual machines) set this to no
USE_PVM3	= no
#	If you want to use compressed data files set this to yes
USE_XDR		= yes
# 	Sockets
USE_SOCK	= no
#
USE_GL		= no
