# Samba Double Prec.
#	@(#) Makefile.amd 1.2 11/19/95
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on the i860 multiprocessor
#
include		$(GMXHOME)/src/makef/Makefile.amb
SYSDEFS	+=	-DDOUBLE -D_amb_
