#
#	@(#) Makefile.in8 1.5 19 Nov 1995
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on mips processor (sgi)
#
include		$(GMXHOME)/src/makef/Makefile.ins
SYSDEFS		+= -DDOUBLE -D_ins_
