# Linux/x86
#	@(#) Makefile.lnx 1.8 27 Jun 1996
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on a i486 processor (Linux)
#
# 	See README file for info
#
SYSDEFS		= -DHAVE_IDENT -DHAVE_ULONG -DCINVSQRT

#
#	USER MODIFIABLE SECTION
#
# If you want to use fortran innerloops set this to yes
# For most machines this will improve the performance quite a bit
# because C-compilers are not as good as Fortran compilers
USEF77		= no
#
# If you want to run in *** P A R A L L E L ***
# please select either PVM or MPI, check with your local hacker
# to see what's installed at your site. If you have neither,
# set both to no. If you select both, something will break!!!
#
USE_PVM3	= no
USE_MPI		= no
#
# If you want to use compressed data files set this to yes
# This uses the xdr libraries of your UNIX system, which is virtually
# Allways present, because it is necessary for NFS (network file system)
#
USE_XDR		= yes
#
# Graphics Library
# Set this on if you have Open GL and the Viewkit library
# (standard with SGI, available for money elsewhere)
# This is used in the Open GL trajectory viewer.
HAVE_GL		= no
#
#
# If you want to use the GMX/Motif user interface (and if you have Motif
# or lesstif (www.lesstif.org) installed, uncomment this one.
HAVE_MOTIF	= no
#
# Note that these variables are also used in Makefile.std
# If something does not work, please check out the link command line
# in that file (e.g. for PVM)
#

# GNU C compiler
MKDEP		= $(CC) -MM
CC		= gcc
CCC		= gcc
F77		= g77
CFLAGS		= -O3 -ffast-math -m486 -fPIC  #  Assume Intel 486 for now 
CCFLAGS		= $(CFLAGS)
FFLAGS		= -fPIC

# Generic linking stuff
LDFLAGS		= -L$(LIBDIR)
LD		= $(CC) $(LDFLAGS) 
FLD		= $(F77) $(LDFLAGS) 
CCLD		= $(CCC) $(LDFLAGS)
ifeq ($(USE_MPI),yes)
LDFLAGS		+= -L/usr/mpi/lib/LINUX/ch_p4 
endif

ifeq ($(HAVE_MOTIF),yes)
SYSDEFS		+= -DHAVE_MOTIF
XLIBS		= -L/usr/X11R6/lib -lXm -lXt -lX11  -lm
SYSLIBS		= $(XLIBS)
else
XLIBS		= -L/usr/X11R6/lib -lX11 -lm
SYSLIBS		= -lm
endif
SHAREIT		= #(cd $(LIBDIR); ar x $(LIB); $(CC) $(LDFLAGS) -shared -Wl,-soname,$(SONAME) -o $(LIBDIR)/$(SONAME) *.o; $(RM) *.o)
RANLIB		= ranlib
X11INC		= -I/usr/X11R6/include





