# IBM/SP2 Double Prec.
#	@(#) Makefile.sp2 1.1 5/15/97
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on generic cpus
#
# 	See README file for info
#
# The default setup is for nonparallell code, which is what
# you want for all utility programs, etc.
# To get the parallel mdrun, set use_mpi and recompile.
#
# Depending on your machine you might have to change the machine
# type from pwr2 to something else. 
#
SYSDEFS		= -DHAVE_ULONG -DNO_NICE 
# The power2 chip have hardware sqrt faster than the gromacs one

# IBM C compilers
CC              = xlc
CCC             = xlC
F77             = xlf
CFLAGS          = -O3 -qarch=pwr2 -qtune=pwr2 -langlvl=ansi -qmaxmem=16384 
CCFLAGS         = -O3 -qarch=pwr2 -qtune=pwr2 -qmaxmem=16384 
FFLAGS          = -O3 -Q -qarch=pwr2 -qtune=pwr2 -qmaxmem=16384 -qhot -qrealsize=4 -qextname

# Generic linking stuff
LDFLAGS		= -L$(LIBDIR)
LD		= $(CC)  $(LDFLAGS) 
CCLD		= $(CCC) $(LDFLAGS)

SYSLIBS		= -lgmx.$(GMXCPU) -lm
XLIBS		= $(SYSLIBS) -lX11
ARFLAGS		= q
RANLIB		= echo
X11INC		= -I/usr/local/include

#
#	USER MODIFIABLE SECTION
#
# If you want to use fortran innerloops set this to yes
# For most machines this will improve the performance quite a bit
# because C-compilers are not as good as Fortran compilers
USEF77		= yes
#
# If you want to run in *** P A R A L L E L ***
# please select either PVM or MPI, check with your local hacker
# to see what's installed at your site. If you have neither,
# set both to no. If you select both, something will break!!!
#
USE_PVM3	= no
USE_MPI		= no
#
# If you want to use compressed data files set this to yes
# This uses the xdr libraries of your UNIX system, which is virtually
# Allways present, because it is necessary for NFS (network file system)
#
USE_XDR		= yes
#
# Graphics Library
# Set this on if you have Open GL and the Viewkit library
# (standard with SGI, available for money elsewhere)
# This is used in the Open GL trajectory viewer.
HAVE_GL		= no
#
# Note that these variables are also used in Makefile.std
# If something does not work, please check out the link command line
# in that file (e.g. for PVM)
#
ifeq ($(USE_MPI),yes)
CC		= mpcc
CCC             = mpCC
F77		= mpxlf
CC_MKINL	= xlc # no mpi for the program we run during compile
LD_MKINL	= xlc
PARALLEL_ONLY_MDRUN = yes
endif
