# SGI/R8k Double Prec.
#	@(#) Makefile.s8d 1.3 4/15/97
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on mips processor (sgi)
#
include		$(GMXHOME)/src/makef/Makefile.sgp
SYSDEFS		+= -DDOUBLE -D_sgp_
FFLAGS		+= -r8
