# Dec/Alpha with Dec Compilers
#	@(#) Makefile.dec 1.2 5/15/97
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on DEC alpha machines with DEC C and Fortran
#       compilers.
#
# 	See README file for info
#
# Use CPU type lnx for a Dec running Linux with gnu compilers.
# Uncomment the following line if you are running Linux with Dec compilers:
#LINUX_OS = yes

SYSDEFS		= -DHAVE_ULONG -DCINVSQRT -DFINVSQRT -DHAVE_STRCASECMP -DHAVE_STRDUP

#
#	USER MODIFIABLE SECTION
#
# If you want to use fortran innerloops set this to yes
# For most machines this will improve the performance quite a bit
# because C-compilers are not as good as Fortran compilers
USEF77		= yes
#
# If you want to run in *** P A R A L L E L ***
# please select either PVM or MPI, check with your local hacker
# to see what's installed at your site. If you have neither,
# set both to no. If you select both, something will break!!!
#
USE_PVM3	= no
USE_MPI		= no
#
# If you want to use compressed data files set this to yes
# This uses the xdr libraries of your UNIX system, which is virtually
# Allways present, because it is necessary for NFS (network file system)
#
USE_XDR		= yes
#
# If you want to use the GMX/Motif user interface (and if you have Motif
# or lesstif (www.lesstif.org) installed) set HAVE_MOTIF to yes.
HAVE_MOTIF	= no
#
# Note that these variables are also used in Makefile.std
# If something does not work, please check out the link command line
# in that file (e.g. for PVM)
#

# Dec C compilers
ALLOPT		= -O5 -tune host -fast -math_library fast  -unroll 2 -arch host -pipeline -fp_reorder #-inline all 
#ALLOPT		= -g

ifeq ($(LINUX_OS),yes)
# For Linux: your DEC C and Fortran compiler commands:
CC 		= ccc
F77 		= fort
else
# If you have cc.alt installed you can use it, it gives faster code
# but is not guaranteed by DEC (let alone by the GROMACS crew)
#CC		= cc.alt
CC		= cc
F77		= f77
endif
CFLAGS		= -std1 $(ALLOPT) -w0 -warnprotos #-trapuv
FFLAGS		= $(ALLOPT) -speculate all -assume noaccuracy_sensitive

LDFLAGS		= -L$(LIBDIR) 
LD		= $(CC)  $(LDFLAGS) 
RUNLDOPT	= -O4 -non_shared
FLD		= $(F77) $(LDFLAGS)

# Generic linking stuff
ifeq ($(LINUX_OS),yes)
# The Compaq math lib instead of -lm 
SYSLIBS		= -lcpml
XLIBS		= $(SYSLIBS) -lX11 
else
ifeq ($(HAVE_MOTIF),yes)
SYSDEFS		+= -DHAVE_MOTIF
SYSLIBS		= -lm -lXm -lXt -lSM -lICE -lX11 -ldnet_stub #-lefence
XLIBS		= $(SYSLIBS)
else
SYSLIBS		= -ldnet_stub -lm
XLIBS		= $(SYSLIBS) -lX11 
endif
endif

ARFLAGS		= ruv
RANLIB		= ranlib

ifeq ($(USE_MPI),yes)
SYSLIBS         += -lrt -limc -pthread
endif
