# Intel/i860
#	@(#) Makefile.860 1.35 8/26/96
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on the i860 multiprocessor
#
SYSDEFS		=-DHAVE_IDENT -DHAVE_SEMA -DPARALLEL -DNEED_STRDUP -DNO_PWUID -DCINVSQRT -DNO_NICE -DNO_PIPE -DUSE_IDT
SHELL		= /bin/csh
CC		= hc860
CPP		= $(CC) -E
CFLAGS		= -O -Hansi -sched 
#-Hic=5 -Hit=30 

AS		= mas860
ASFLAGS		= 
#-a -x -z -l$(*F).l
LDFLAGS		= -L$(LIBDIR)/
#LDFLAGS	= -L$(LIBDIR)/ -T0xF0780000
LD		= $(CC) $(LDFLAGS)

SYSLIBS		= $(LINKLIB) -lm
AR		= lib860 -r
RANLIB		= echo

.c.ppp:
		$(CPP) $(CCFLAGS) $<
#
#	USER MODIFIABLE SECTION
#
#WARNING
#WARNING The fortran innerloop is tested only on SUN and SGI machines
#WARNING				
# 	If you want to use fortran innerloops set this to yes
USEF77		= no
#	If you don't have PVM (parallel virtual machines) set this to no
USE_PVM3	= no
#	If you want to use compressed data files set this to yes
USE_XDR		= no
# 	Sockets
USE_SOCK	= no
