#
#	@(#) Makefile.amb 1.25 1/24/97
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on the i860 multiprocessor
#
SYSDEFS		=-DHAVE_IDENT -DPARALLEL -DHAVE_ULONG -DNO_PWUID -DNO_NICE -D_SYS_ISA_DEFS_H -DC_INVSQRT -DSHORT_NL -DNO_PIPE -DUSE_AMB -DNO_CLOCK
# That sys_isa shit define is to fool Solaris 2.4

PGI		= /usr/local/pgi
PGI23		= /usr/local/pgi2.3a
PGCDIR		= $(PGI)/i860/bin/
CC		= $(PGCDIR)pgcc
AS		= $(PGCDIR)as860
LOAD		= $(PGCDIR)ld860
NM		= $(PGCDIR)nm860

# Chess stuff
STARTUP		= $(LIBDIR)/crt6.o

# If a new version of Chess software arrives, the crt0.o must be copied !
# This also goes for "ambadma.h" which is copied to the include dir

BELIB		= $(PGI23)/i860/lib-coff-be
TEXT		= 0xff800000
ALLFLAGS	= -Mbe -c 
OPTFLAGS	= $(ALLFLAGS) -O4 -Minfo=loop -Mvect -Minline=30 \
-Mframe -Mfptrap -Msingle -Mfcon
# -Msafeptr=arg,auto 
# -Munroll crashes on the force routine!
HIGHOPT		= $(OTPFLAGS) -Msafeptr=arg,auto
DBGFLAGS	= $(ALLFLAGS) -g 
#-DDEBUG
CFLAGS		= $(DBGFLAGS)
#CFLAGS		= $(OPTFLAGS) 
CCCCC		= $(CC) $(DBGFLAGS) $(ADDFLAGS) $(INCS) $(SYSDEFS) 
LDFLAGS		= -swapc -be -YP$(BELIB) -contig -T$(TEXT) -L$(LIBDIR) $(STARTUP) 
LD2FLAGS	+= -be -YP$(BELIB) -contig -T$(TEXT) $(STARTUP)
ASFLAGS		+= -be

LD		= $(LOAD) $(LDFLAGS)
SYSLIBS		= $(LINKLIB) -lc -lpgc
AR		= ar860 ruv
RANLIB		= echo

#
#	USER MODIFIABLE SECTION
#
#WARNING
#WARNING The fortran innerloop is tested only on SUN and SGI machines
#WARNING				
# 	If you want to use fortran innerloops set this to yes
USEF77		= no
#	If you don't have PVM (parallel virtual machines) set this to no
USE_PVM3	= no
#	If you want to use compressed data files set this to yes
USE_XDR		= no
# 	Sockets
USE_SOCK	= no
