# Alpha/Dec Double Prec.
#	@(#) Makefile.s18 1.1 15 Sep 1996
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on alpha processors running dec unix (compaq tru64 unix)
#
include		$(GMXHOME)/src/makef/Makefile.dec
SYSDEFS		+= -DDOUBLE -D_dec_
FFLAGS		+= -r8

