#
#	@(#) Makefile.def 1.33 8/16/96
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990-1994, Groningen University
#
#	Global definitions for gromacs
#
ROOT		:=$(GMXHOME)
CUR		:=$(shell basename `pwd`)
SRCDIR		:=$(ROOT)/src
MKDIR		:=$(SRCDIR)/makef
INCDIR		:=include
#LIB		:=$(LIBDIR)/libgmx.$(GMXCPU).a
#SONAME		:=libgmx.$(GMXCPU).so
#SOLIB		:=$(LIBDIR)/$(SONAME)
STDTARGET	:=$(MKDIR)/Makefile.std
SHAREIT		:=echo
MKDEP		:= $(CC) -M
#
# Machine dependent stuff
#
include		$(MKDIR)/Makefile.$(GMXCPU)
ifeq ($(USE_MPI),yes)
PARALLEL	= yes
else
ifeq ($(USE_PVM3),yes)
PARALLEL        = yes
else
PARALLEL	= no
endif
endif
ifneq ($(PARALLEL_ONLY),yes)
OBJDIR		:=$(ROOT)/obj/$(GMXCPU)
LIBDIR		:=$(ROOT)/lib/$(GMXCPU)
BINDIR		:=$(ROOT)/bin/$(GMXCPU)
else
SHAREIT		:=echo
ifeq ($(USE_MPI),yes)
OBJDIR		:=$(ROOT)/obj/$(GMXCPU)_mpi
LIBDIR		:=$(ROOT)/lib/$(GMXCPU)_mpi
BINDIR		:=$(ROOT)/bin/$(GMXCPU)_mpi
else
ifeq ($(USE_PVM3),yes)
OBJDIR		:=$(ROOT)/obj/$(GMXCPU)_pvm
LIBDIR		:=$(ROOT)/lib/$(GMXCPU)_pvm
BINDIR		:=$(ROOT)/bin/$(GMXCPU)_pvm
endif
endif
endif
RUNSYSLIBS      := $(LINKSTATIC) -lmd.$(GMXCPU) -lgmx.$(GMXCPU) -lfftw.$(GMXCPU) $(LINKDYNAMIC) $(SYSLIBS)
SYSLIBS		:= -lgmx.$(GMXCPU) $(SYSLIBS)
#
# System independent definitions
#
GET		= ln -s
ifneq ($(GMXCPU),win)
RM		= /bin/rm -f
else
RM              = rm -f
endif
BINMODE		= 755
LIBMODE		= 644
INCS		= -I. -I$(SRCDIR)/$(INCDIR) $(X11INC) 
ADDFLAGS	= -D_$(GMXCPU)_ $(DEFS) $(SYSDEFS) $(INCS)
C-FLAGS		= $(CFLAGS)  $(ADDFLAGS)
CC-FLAGS	= $(CCFLAGS) $(ADDFLAGS) -DCPLUSPLUS 
