# Alpha/Linux 
#	@(#) Makefile.dec 1.2 5/15/97
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on DEC alpha machines with gnu or DEC C and Fortran
#       compilers.
#
# 	See README file for info
#
# The default is to use gnu compilers. Uncomment the next line if you have
# the faster dec/compaq compilers.
#COMPAQ_COMPILERS = yes

SYSDEFS         = -DHAVE_STRCASECMP -DHAVE_STRDUP -DDECREASE_SQUARE_LATENCY -DDECREASE_LOOKUP_LATENCY -DPREFETCH_X_WW -DGMX_INVSQRT -DINLINE_GMXCODE 
#
#	USER MODIFIABLE SECTION
#
# If you want to use fortran innerloops set this to yes
# For most machines this will improve the performance quite a bit
# because C-compilers are not as good as Fortran compilers
# Note that early versions of gnu f77 for alpha/linux were very slow -
# if you are running gcc prior to egcs or gcc<2.95 you are better
# off not using f77. 
# (We definitely recommend you to upgrade, or better, use compaq/dec compilers)
USEF77		= yes
#
# If you want to run in *** P A R A L L E L ***
# please select either PVM or MPI, check with your local hacker
# to see what's installed at your site. If you have neither,
# set both to no. If you select both, something will break!!!
#
USE_PVM3	= no
USE_MPI		= no
#
# If you want to use compressed data files set this to yes
# This uses the xdr libraries of your UNIX system, which is virtually
# Allways present, because it is necessary for NFS (network file system)
#
USE_XDR		= yes
#
# If you want to use the GMX/Motif user interface (and if you have Motif
# or lesstif (www.lesstif.org) installed) set HAVE_MOTIF to yes.
HAVE_MOTIF	= no
#
# Note that these variables are also used in Makefile.std
# If something does not work, please check out the link command line
# in that file (e.g. for PVM)
#


ifeq ($(COMPAQ_COMPILERS),yes)
#
# THIS PART IS FOR DEC/COMPAQ COMPILERS
#
CC 		= ccc
F77 		= fort
# options
ALLOPT		= -fast
CFLAGS		= $(ALLOPT) -w0 -warnprotos 
FFLAGS		= $(ALLOPT) -pipeline 
LDFLAGS		= -L$(LIBDIR) 
LD		= $(CC)  $(LDFLAGS) 
RUNLDOPT	= -O4 -non_shared
FLD		= $(F77) $(LDFLAGS)
# The Compaq math lib instead of -lm 
SYSLIBS		= -lcpml
XLIBS		= -L/usr/X11R6/lib $(SYSLIBS) -lX11 
ARFLAGS		= ruv
RANLIB		= ranlib
else
#
# THIS PART IS FOR GNU COMPILERS:
#
CC		= gcc
F77		= g77
MKDEP		= $(CC) -MM
CFLAGS		= -O3 -ffast-math -finline-functions -Winline -fPIC -funroll-all-loops  -Wall -Wno-unused
#
LDFLAGS		= -L$(LIBDIR) 
LD		= $(CC)  $(LDFLAGS) 
RUNLDOPT	= -O4 -non_shared
FLD		= $(F77) $(LDFLAGS)
ifeq ($(HAVE_MOTIF),yes)
SYSDEFS		+= -DHAVE_MOTIF
XLIBS		= -L/usr/X11R6/lib -lXm -lXt -lX11
SYSLIBS		= $(XLIBS)  -lm 
else
XLIBS		= -L/usr/X11R6/lib -lX11 
SYSLIBS		= -lm
endif
SHAREIT		= (cd $(LIBDIR); ar x $(LIB); $(CC) $(LDFLAGS) -shared -Wl,-soname,$(SONAME) -o $(LIBDIR)/$(SONAME) *.o; $(RM) *.o)
RANLIB		= ranlib
X11INC		= -I/usr/X11R6/include
endif
