# Windows95/NT
#	@(#) Makefile.win 1.1 21 Jul 1998
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs under Windows95/NT
#
# 	See README file for info
#
SYSDEFS		= -DHAVE_IDENT -DCINVSQRT -DNO_NICE

EXTENSION = .exe

# GNU C compiler
CC		= gcc
CCC		= gcc
F77		= g77
CFLAGS		= -O3 
CCFLAGS		= $(CFLAGS)
FFLAGS		=

# Generic linking stuff
LDFLAGS		= -L$(LIBDIR) 
LD		= $(CC) $(LDFLAGS) 
FLD		= $(F77) $(LDFLAGS) 
CCLD		= $(CCC) $(LDFLAGS)

SYSLIBS		= -lgmx.$(CPU) -lm
XLIBS		= -lX11 -L/usr/lib/X11 -L/usr/X11R6/lib
SHAREIT		= #(cd $(LIBDIR); ar x $(LIBRARY).$(CPU).a; $(CC) $(LDFLAGS) -shared -Wl,-soname,$(LIBRARY).$(CPU).so -o $(LIBDIR)/$(LIBRARY).$(CPU).so *.o; $(RM) *.o)
RANLIB		= ranlib
#X11INC		= -I/usr/include/X11

#
#	USER MODIFIABLE SECTION
#
# If you want to use fortran innerloops set this to yes
# For most machines this will improve the performance quite a bit
# because C-compilers are not as good as Fortran compilers
USEF77		= no
#
# If you want to run in *** P A R A L L E L ***
# please select either PVM or MPI, check with your local hacker
# to see what's installed at your site. If you have neither,
# set both to no. If you select both, something will break!!!
#
USE_PVM3	= no
USE_MPI		= no
#
# If you have an XWindows library you can use the Gromacs X-tools
#
USE_XWIN	= no
#
# If you want to use compressed data files set this to yes
# This uses the xdr libraries of your UNIX system, which is virtually
# Allways present, because it is necessary for NFS (network file system)
#
USE_XDR		= no
#
# Graphics Library
# Set this on if you have Open GL and the Viewkit library
# (standard with SGI, available for money elsewhere)
# This is used in the Open GL trajectory viewer.
HAVE_GL		= no
#
# Note that these variables are also used in Makefile.std
# If something does not work, please check out the link command line
# in that file (e.g. for PVM)
#

