# Convex SPP
#       Res, Aug 26 1996
#
#
#       GROMACS - Groningen Machine for Chemical Simulation
#       Copyright (c) 1990, 1991, 1992, Groningen University
#
#       Makefile for gromacs on generic cpus
#
#       See README file for info
#
SYSDEFS         = -DHAVE_STRDUP
 
# Convex CC, HP f77
CC              = /usr/convex/bin/cc
CCC             = CC
F77             = /usr/bin/f77
CFLAGS          = -O2
CCFLAGS         = -O2
FFLAGS          = -O +ppu
 
# Generic linking stuff
LDFLAGS         = -L$(LIBDIR)
LD              = /usr/convex/bin/fc $(LDFLAGS) 
FLD		= $(LD)
CCLD            = $(CCC) $(LDFLAGS)

SYSLIBS         = $(LINKLIB)  -lm
XLIBS           = $(SYSLIBS) -lX11
AR              = ar ruv
RANLIB          = echo
X11INC          = -I/usr/include/X11R5
 
#
#       USER MODIFIABLE SECTION
#
#       If you want to use fortran innerloops set this to yes
USEF77          = yes
#       If you don't have PVM (parallel virtual machines) set this to no
USE_PVM3        = yes
USE_MPI         = 
 
#       If you want to use compressed data files set this to yes
USE_XDR         = no
 
# Note that these variables are also used in Makefile.std
# If you experience any problems using PVM also check that file.
 

