#
#	@(#) Makefile.def 1.33 8/16/96
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990-1994, Groningen University
#
#	Global definitions for gromacs
#
ROOT		:=$(GMXHOME)
CUR		:=$(shell basename `pwd`)
SRCDIR		:=$(ROOT)/src
MKDIR		:=$(SRCDIR)/makef
OBJDIR		:=$(ROOT)/obj/$(CPU)
LIBDIR		:=$(ROOT)/lib/$(CPU)
BINDIR		:=$(ROOT)/bin/$(CPU)
INCDIR		:=include
LIB		:=$(LIBDIR)/libgmx.$(CPU).a
SONAME		:=libgmx.$(CPU).so
SOLIB		:=$(LIBDIR)/$(SONAME)
LINKLIB		:=-lgmx.$(CPU)
STDTARGET	:=$(MKDIR)/Makefile.std
SHAREIT		:=echo
MKDEP		:= $(CC) -M
#
# Machine dependent stuff
#
include		$(MKDIR)/Makefile.$(CPU)
#
# System independent definitions
#
GET		= ln -s
ifneq ($(CPU),win)
RM		= /bin/rm -f
else
RM              = rm -f
endif
BINMODE		= 755
LIBMODE		= 644
INCS		= -I. -I$(SRCDIR)/$(INCDIR) $(X11INC) 
ADDFLAGS	= -D_$(CPU)_ $(DEFS) $(SYSDEFS) $(INCS)
C-FLAGS		= $(CFLAGS)  $(ADDFLAGS)
CC-FLAGS	= $(CCFLAGS) $(ADDFLAGS) -DCPLUSPLUS 
