# SGI/R10000/R12000 Dbl Prec.
#	@(#) Makefile.s18 1.1 15 Sep 1996
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on mips processor (sgi)
#
include		$(GMXHOME)/src/makef/Makefile.s10
SYSDEFS		+= -DDOUBLE -D_s10_
FFLAGS		+= -r8
USE_MPI = yes

