# Sun Ultrasparc
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on ultrsparc processor
#
# 	You may have to change the paths in LDFLAGS below!
#       If you dont have the performace library from sun, change -lmopt to -lm in SYSLIBS
#
SYSDEFS		= -DHAVE_IDENT -DHAVE_ULONG -DHAVE_STRDUP -DHAVE_STRCASECMP -DFINVSQRT -DCINVSQRT

# Sun C compilers
CC		= cc
CCC		= CC
F77		= f77

# This will *only* run on ultrasparc architecture, and allow for semidangerous optimization :-)
CFLAGS		= -fast -KPIC -xO5 -xarch=v8plusa -xsafe=mem -fnonstd -fsimple=2
CCFLAGS		= -fast -xO5 -KPIC -xarch=v8plusa -xsafe=mem -dalign -fnonstd -fsimple=2
FFLAGS          = -fast -xO5 -KPIC -xarch=v8plusa -xsafe=mem -dalign -fnonstd -fsimple=2


# Generic linking stuff
LDFLAGS		= -L$(LIBDIR) -L/usr/lib -L/opt/SUNWspro/SC4.2/lib -L/usr/openwin/lib -fast -xO5 -xarch=v8plusa -xsafe=mem -fnonstd -fsimple=2
LD		= $(F77) $(LDFLAGS) -z nodefs
FLD		= $(F77) $(LDFLAGS)
CCLD		= $(CCC) $(LDFLAGS) -z nodefs

XLIBS		= -lsocket -lX11
SYSLIBS		= $(LINKLIB) -lm -lcopt -lnsl 
SHAREIT		= (cd $(LIBDIR); ar x $(LIB); cc $(LDFLAGS) -o $(SONAME) -G *.o; $(RM) *.o)
RANLIB		= echo
X11INC		= -I/usr/openwin/include

#
#	USER MODIFIABLE SECTION
#
# If you want to use fortran innerloops set this to yes
# For most machines this will improve the performance quite a bit
# because C-compilers are not as good as Fortran compilers
USEF77		= yes
SYSDEFS		+= -DF77UNDERSCORE
#
# If you want to run in *** P A R A L L E L ***
# please select either PVM or MPI, check with your local hacker
# to see what's installed at your site. If you have neither,
# set both to no. If you select both, something will break!!!
#
USE_PVM3	= no
USE_MPI		= no
#
# If you want to use compressed data files set this to yes
# This uses the xdr libraries of your UNIX system, which is virtually
# Allways present, because it is necessary for NFS (network file system)
#
USE_XDR		= yes
#
# Graphics Library
# Set this on if you have Open GL and the Viewkit library
# (standard with SGI, available for money elsewhere)
# This is used in the Open GL trajectory viewer.
HAVE_GL		= no
#
# Note that these variables are also used in Makefile.std
# If something does not work, please check out the link command line
# in that file (e.g. for PVM)
#




