# Linux/x86 Double Prec.
#	@(#) Makefile.ln8 1.8 27 Jun 1996
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on a i486 processor (Linux)
#
include		$(GMXHOME)/src/makef/Makefile.lnx
SYSDEFS		+= -DDOUBLE -D_lnx_
# Note: If you are running with f77 inner loops, you must
# add a flag to make the default real size 8 bytes in fortran.
# (Which is ??? for g77)
