# SGI/R4000
#	@(#) Makefile.sgi 1.57 10/20/97
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on mips processor (sgi)
#
#	See README file for info
#
ABI		= -n32 -mips3

# Include generic SGI stuff
include	$(GMXHOME)/src/makef/Makefile.SGI

USE_PVM3	= no
