# HP/PaRISC
#	@(#) Makefile.hp 1.15 11/20/96
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on PA-RISC processor
#
# 	See README file for info
#
SYSDEFS		= -DNO_PWUID -DNEED_USHORT

CC		= cc
CCC		= CC
F77		= f77
FFLAGS		= +O3 +ppu
CFLAGS		= -Aa +O2

LDFLAGS		= -L$(LIBDIR)
LD		= $(CC) $(LDFLAGS)
CCLD		= $(CCC) $(LDFLAGS)
FLD		= $(F77) $(LDFLAGS)

SYSLIBS		= $(LINKLIB) -lm 
#
# The HP Operating system is definitely NOT cool
# Where is the X Stuff for instance ?
# On our machine it was here, but probably not on yours...
#
XLIBS		= $(SYSLIBS) -L/usr/lib/X11R4 -lX11
AR		= ar ruv
RANLIB		= echo
X11INC		= -I/usr/include/X11

#
#	USER MODIFIABLE SECTION
#
# If you want to use fortran innerloops set this to yes
# For most machines this will improve the performance quite a bit
# because C-compilers are not as good as Fortran compilers
USEF77		= yes
SYSDEFS		+= -DF77UNDERSCORE
#
# If you want to run in *** P A R A L L E L ***
# please select either PVM or MPI, check with your local hacker
# to see what's installed at your site. If you have neither,
# set both to no. If you select both, something will break!!!
#
USE_PVM3	= no
USE_MPI		= no
#
# If you want to use compressed data files set this to yes
# This uses the xdr libraries of your UNIX system, which is virtually
# Allways present, because it is necessary for NFS (network file system)
# Can not compile this on HP ... that OS really sucks ...
# If you can do it, please send me the Makefile and/or other code
# changes...
USE_XDR		= no
#
# Graphics Library
# Set this on if you have Open GL and the Viewkit library
# (standard with SGI, available for money elsewhere)
# This is used in the Open GL trajectory viewer.
HAVE_GL		= no
#
# Note that these variables are also used in Makefile.std
# If something does not work, please check out the link command line
# in that file (e.g. for PVM)
#

