#
#	@(#) Makefile.SGI 1.4 8/4/97
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on Power Challenge using power C and
#	power Fortran
#
#	See README file for info
#
SYSDEFS		= -DHAVE_IDENT -DHAVE_ULONG -D__INLINE_INTRINSICS -DHAVE_STRDUP -D_SGI_ 

CC		= cc
CCC		= CC
F77		= f77

OPT		= -O3 -OPT:IEEE_arithmetic=3 -OPT:rsqrt=ON -SWP:loop_overhead -INLINE:=ON -LNO:opt=1 -LNO:ou_further=3 -OPT:Olimit=0:roundoff=3:alias=typed -fullwarn
# All warnings except unused vars: -fullwarn -woff 1174
CFLAGS		= $(ABI) $(OPT) -woff 1174
CCFLAGS		= $(ABI) $(OPT) -woff 1174 -DHAVE_BOOL 
FFLAGS		= $(ABI) $(OPT) -OPT:cray_ivdep=TRUE
#FFLAGS		+= -GCM:aggressive_speculation -GCM:array_speculation

LDFLAGS		= -L$(LIBDIR) $(ABI) 
LD		= $(CC) $(LDFLAGS)
CCLD		= $(CCC) $(LDFLAGS)
FLD		= $(F77) $(LDFLAGS)

USE_SGI_FPE	= no
XLIBS		= -lX11
SYSLIBS		= $(LINKLIB) -lm
ifeq ($(USE_SGI_FPE),yes)
	SYSDEFS += -DUSE_SGI_FPE
	SYSLIBS += -lfpe
endif

AR		= ar ruv
#SHAREIT		= cc -shared -elf -shared -all -no_unresolved \
#		  -quickstart_info -check_registry /usr/lib/so_locations \
#		  -soname $(SONAME) -o $(SOLIB) $(LIB)
RANLIB		= echo
X11INC		= -I/usr/include/X11

#
#	USER MODIFIABLE SECTION
#
# If you want to use fortran innerloops set this to yes
# For most machines this will improve the performances quite a bit
# because C-compilers are not as good as Fortran compilers
USEF77		= yes
SYSDEFS		+= -DF77UNDERSCORE
#
# If you want to run in *** P A R A L L E L ***
# please select either PVM or MPI, check with your local hacker
# to see what's installed at your site. If you have neither,
# set both to no. If you select both, something will break!!!
#
USE_PVM3	= no
USE_MPI		= no
#
# If you want to use compressed data files set this to yes
# This uses the xdr libraries of your UNIX system, which is virtually
# Allways present, because it is necessary for NFS (network file system)
#
USE_XDR		= yes
#
# Graphics Library
# Set this on if you have Open GL and the Viewkit library
# (standard with SGI, available for money elsewhere)
# This is used in the Open GL trajectory viewer.
HAVE_GL		= no
#
# Note that these variables are also used in Makefile.std
# If something does not work, please check out the link command line
# in that file (e.g. for PVM)
#
