# Alpha/Dec UNIX
#	@(#) Makefile.dec 1.2 5/15/97
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on DEC alpha machines (running OSF1)
#
# 	See README file for info
#
SYSDEFS		= -DHAVE_ULONG -DCINVSQRT -DFINVSQRT -DHAVE_STRCASECMP -DHAVE_STRDUP

#
#	USER MODIFIABLE SECTION
#
# If you want to use fortran innerloops set this to yes
# For most machines this will improve the performance quite a bit
# because C-compilers are not as good as Fortran compilers
USEF77		= yes
#
# If you want to run in *** P A R A L L E L ***
# please select either PVM or MPI, check with your local hacker
# to see what's installed at your site. If you have neither,
# set both to no. If you select both, something will break!!!
#
USE_PVM3	= no
HOME		= /usr/local/lam
USE_MPI		= yes
#
# If you want to use compressed data files set this to yes
# This uses the xdr libraries of your UNIX system, which is virtually
# Allways present, because it is necessary for NFS (network file system)
#
USE_XDR		= yes
#
# If you want to use the GMX/Motif user interface (and if you have Motif
# or lesstif (www.lesstif.org) installed), uncomment this one.
HAVE_MOTIF	= yes
#
# Note that these variables are also used in Makefile.std
# If something does not work, please check out the link command line
# in that file (e.g. for PVM)
#

# Dec C compilers
LOWOPT		= -O2 
ALLOPT		= -O5 -tune host  -unroll 16 -arch host -pipeline -fp_reorder -transform_loops -fast -math_library fast -inline all #-trapuv
#ALLOPT		= -g
# If you have cc.alt installed you can use it, it gives faster code
# but is not guaranteed by DEC (let alone by the GROMACS crew)
#CC		= cc.alt
CC		= $(HOME)/bin/hcc
F77		= $(HOME)/bin/hf77
CFLAGS		= -std1 $(ALLOPT) -warnprotos #-trapuv
CCFLAGS		= -O
FFLAGS		= $(ALLOPT) -speculate all -assume noaccuracy_sensitive 

# Gnu compilers
#OPT		= -O3 -funroll-loops -ffast-math -fschedule-insns -fschedule-insns2
#CC		= gcc
#CCC		= gcc
#F77		= g77
#CFLAGS		= $(OPT)
#FFLAGS		= $(OPT)
#CCFLAGS		= $(OPT)

LDFLAGS		= -L$(LIBDIR) -L$(HOME)/lib
LD		= $(CC)  $(LDFLAGS) 
RUNLDOPT	= -O3 
FLD		= $(F77) $(LDFLAGS)
CCLD		= -$(CCC) $(LDFLAGS)

# Generic linking stuff
ifeq ($(HAVE_MOTIF),yes)
SYSDEFS		+= -DHAVE_MOTIF
SYSLIBS		= -lm -lXm -lXt -lSM -lICE -lX11 -ldnet_stub #-lefence
XLIBS		= $(SYSLIBS)
else
SYSLIBS		= -ldnet_stub -lm
XLIBS		= $(SYSLIBS) -lX11 
endif

ARFLAGS		= ruv
RANLIB		= ranlib

#ifeq ($(USE_MPI),yes)
#SYSLIBS         += -lrt -limc -pthread
#endif
