#
#	@(#) Makefile.std 1.44 6/25/97
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Definitions dependent on CPU but general enough to put here...
#

GET	=	ln -s
ifeq ($(USEF77),yes)
SYSDEFS		+= -DUSEF77
endif

ifeq ($(USE_MPI),yes)
SYSDEFS         += -DUSE_MPI -DPARALLEL
INCDIR		+= -I$(MPIR_HOME)/include
SYSLIBS         += -lmpi
endif

ifeq ($(USE_PVM3),yes)
SYSDEFS		+= -DUSE_PVM3 -DPARALLEL
SYSLIBS		+= -lpvm3
LDFLAGS		+= -L$(PVM_ROOT)/lib/$(PVM_ARCH)
X11INC		+= -I$(PVM_ROOT)/include
CFLAGS		+= -I$(PVM_ROOT)/include
CCFLAGS		+= -I$(PVM_ROOT)/include
endif

FFTLIBS		= -lfftw.$(GMXCPU)

EXECUTABLES = $(foreach FILE, $(PROGRAMS), $(FILE)$(EXTENSION))

ifeq ($(OPTLDFLAGS),)
OPTLDFLAGS	=
endif

ifeq ($(USE_XDR),yes)
SYSDEFS		+= -DUSE_XDR
endif
#
#	Standard target definitions for gromacs
#
all:		lib 	bin

lib:	$(foreach OB,$(OBJ),$(LIB)($(OB)) )

ifeq ($(LIB),)
	echo "No library in $(CUR)"
else
	$(SHAREIT)
endif

bin:		$(PROGRAMS)
ifeq ($(PROGRAMS),)
	echo "No programs in $(CUR)"
else
	cd $(BINDIR) ; $(RM) $(EXECUTABLES)
	chmod $(BINMODE) $(EXECUTABLES)
	mv $(EXECUTABLES) $(BINDIR)
endif


GMXINS	= \$$\(GMXHOME\)
dep:
	$(RM) sedscr Make.dep
ifeq ($(OBJ),)
		touch sedscr
else
	( $(foreach OB,$(OBJ),echo s~^$(OB):~\$$\(LIB\)\($(OB)\):~ ; ) ) > sedscr 
endif
	$(MKDEP) -I. -I$(GMXHOME)/src/include  *.c  |  sed  s~$(GMXHOME)~$(GMXINS)~ | grep GMXHOME | sed -f sedscr > Make.dep
	$(RM) sedscr

Make.dep:
	touch Make.dep

oclean:
	$(RM) $(EXECUTABLES) *.o *.l *~ *.bak \#*\#

clean:	oclean
	$(RM) $(LIB)

.c.o:
		$(CC) $(C-FLAGS) -c $<

.s.o:
		$(AS) $(ASFLAGS) $<

.cc.o:
		$(CCC) $(CC-FLAGS) -c $<

.c++.o:
		$(CCC) $(CC-FLAGS) -c $<

.cxx.o:
		$(CCC) $(CC-FLAGS) -c $<

.f.s:
		$(F77) $(FFLAGS) -s $<

.f.o:
		$(F77) $(FFLAGS) -c $<

.f90.o:
		$(F77) $(FFLAGS) -c $<

.c.s:
		$(CC) $(C-FLAGS) -s $<

:		
		$(LD) -o $@ $^ $(SYSLIBS)






