# Sun Ultrasparc
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on ultrsparc processor
#
# 	You may have to change the paths in LDFLAGS below!
#       If you have the performace library from sun, try changing -lm to -lmopt in SYSLIBS
#
SYSDEFS		= -DHAVE_IDENT -DHAVE_STRDUP -DHAVE_STRCASECMP -DFINVSQRT -DCINVSQRT

# Sun workshop compilers
CC		= cc
CCC		= CC
F77		= f77

# This is intended for ultrasparc architecture, and allows for semidangerous optimization
#
# if your compiler supports it, you should uncomment xarch and set this to any of
# v8, v8plusa, v9 or v9a. Higher is better, but it will only work if your 
# computers is of the proper architecture.
#
# You could also try using the optimization options that are commented out, but some 
# sun compilers seem to produce bad code with these.
#
CFLAGS		= -KPIC -xO3 #-fast -fsimple=2 -fnonstd -xarch=v8plusa
CCFLAGS		= -KPIC -xO3 #-fast -fsimple=2 -fnonstd -xarch=v8plusa
FFLAGS          = -KPIC -xO3 #-fast -fsimple=2 -fnonstd -xarch=v8plusa

# Generic linking stuff
LDFLAGS		= -L$(LIBDIR) -L/usr/lib -L/usr/openwin/lib -xO3 #-fast -fsimple=2 -fnonstd -xarch=v8plusa
LD		= $(F77) $(LDFLAGS) -z nodefs
FLD		= $(F77) $(LDFLAGS) 
CCLD		= $(CCC) $(LDFLAGS) -z nodefs

XLIBS		= -lsocket -lX11
SYSLIBS		= $(LINKLIB) -lm -lnsl 
SHAREIT		= (cd $(LIBDIR); ar x $(LIB); cc $(LDFLAGS) -o $(SONAME) -G *.o; $(RM) *.o)
RANLIB		= echo
X11INC		= -I/usr/openwin/include

#
#	USER MODIFIABLE SECTION
#
# If you want to use fortran innerloops set this to yes
# For most machines this will improve the performance quite a bit
# because C-compilers are not as good as Fortran compilers
USEF77		= yes
SYSDEFS		+= -DF77UNDERSCORE
#
# If you want to run in *** P A R A L L E L ***
# please select either PVM or MPI, check with your local hacker
# to see what's installed at your site. If you have neither,
# set both to no. If you select both, something will break!!!
#
USE_PVM3	= no
USE_MPI		= no
#
# If you want to use compressed data files set this to yes
# This uses the xdr libraries of your UNIX system, which is virtually
# Allways present, because it is necessary for NFS (network file system)
#
USE_XDR		= yes
#
# Graphics Library
# Set this on if you have Open GL and the Viewkit library
# (standard with SGI, available for money elsewhere)
# This is used in the Open GL trajectory viewer.
HAVE_GL		= no
#
# Note that these variables are also used in Makefile.std
# If something does not work, please check out the link command line
# in that file (e.g. for PVM)
#




