# Cray/YMP
#
#	@(#) Makefile.ymp 1.2 19 Nov 1995
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on generic cpus
#
# 	See README file for info
#
SYSDEFS		= -DHAVE_IDENT -DHAVE_ULONG

# Sun C compilers
CC		= cc
CCC		= CC
F77		= f90
CFLAGS		= -O3 -h report=is
CCFLAGS		= -O3
FFLAGS		= -O scalar3 -O vector3 -s default32

# Generic linking stuff
LDFLAGS		= -L$(LIBDIR)
LD		= $(CC)  $(LDFLAGS) 
CCLD		= $(CCC) $(LDFLAGS)
FLD		= $(F77) $(LDFLAGS)

SYSLIBS		= -lgmx.$(CPU) -lm
XLIBS		= $(SYSLIBS) -lX11
AR		= ar ruv
RANLIB		= echo
X11INC		= -I/usr/local/include


#
#	USER MODIFIABLE SECTION
#
# If you want to use fortran innerloops set this to yes
# For most machines this will improve the performance quite a bit
# because C-compilers are not as good as Fortran compilers
USEF77		= yes
#SYSDEFS		+= -DF77UNDERSCORE
#
# If you want to run in *** P A R A L L E L ***
# please select either PVM or MPI, check with your local hacker
# to see what's installed at your site. If you have neither,
# set both to no. If you select both, something will break!!!
#
USE_PVM3	= no
USE_MPI		= yes
#
# If you want to use compressed data files set this to yes
# This uses the xdr libraries of your UNIX system, which is virtually
# Allways present, because it is necessary for NFS (network file system)
#
USE_XDR		= yes
#
# Graphics Library
# Set this on if you have Open GL and the Viewkit library
# (standard with SGI, available for money elsewhere)
# This is used in the Open GL trajectory viewer.
HAVE_GL		= no
#
# Note that these variables are also used in Makefile.std
# If something does not work, please check out the link command line
# in that file (e.g. for PVM)
#

