# Sun/SunOS
#	@(#) Makefile.sun 1.23 5/21/96
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for gromacs on sparc processor
#
# compiler, linker & archiver
#
SYSDEFS		= -DHAVE_IDENT -DHAVE_SEMA
CC		= acc
CPP		= acc -E
CFLAGS		= -fast
#CC		= gcc
#CFLAGS		= -Wall -g
LDFLAGS		= -L$(LIBDIR)
LD		= $(CC) $(LDFLAGS)
SYSLIBS		= -lgmx -lm 
XLIBS		= $(SYSLIBS) -lX11
AR		= ar ruv
RANLIB		= ranlib
X11INC		= -I/usr/local/include
