/*
 *
 *                This source code is part of
 *
 *                 G   R   O   M   A   C   S
 *
 *          GROningen MAchine for Chemical Simulations
 *
 * Written by David van der Spoel, Erik Lindahl, Berk Hess, and others.
 * Copyright (c) 1991-2000, University of Groningen, The Netherlands.
 * Copyright (c) 2001-2009, The GROMACS development team,
 * check out http://www.gromacs.org for more information.

 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * If you want to redistribute modifications, please consider that
 * scientific software is very special. Version control is crucial -
 * bugs must be traceable. We will be happy to consider code for
 * inclusion in the official distribution, but derived work must not
 * be called official GROMACS. Details are found in the README & COPYING
 * files - if they are missing, get the official version at www.gromacs.org.
 *
 * To help us fund GROMACS development, we humbly ask that you cite
 * the papers on the package - you can find them in the top README file.
 *
 * For more info, check our website at http://www.gromacs.org
 */
/*! \internal \file
 * \brief
 * Parser/scanner interaction functions.
 *
 * This is an implementation header: there should be no need to use it outside
 * this directory.
 */
#ifndef SELECTION_SCANNER_H
#define SELECTION_SCANNER_H

#include "parser.h"

struct gmx_ana_selcollection_t;

typedef struct gmx_sel_lexer_t gmx_sel_lexer_t;

//! Initializes the selection scanner.
void
_gmx_sel_init_lexer(gmx_sel_lexer_t **statep,
                    struct gmx_ana_selcollection_t *sc, bool bInteractive);
//! Frees memory allocated for the selection scanner.
void
_gmx_sel_free_lexer(gmx_sel_lexer_t *state);
//! Returns TRUE if the scanner is interactive.
bool
_gmx_sel_is_lexer_interactive(gmx_sel_lexer_t *state);
//! Returns the selection collection for the scanner.
struct gmx_ana_selcollection_t *
_gmx_sel_lexer_selcollection(gmx_sel_lexer_t *state);
//! Notifies the scanner that a complete method expression has been parsed.
void
_gmx_sel_finish_method(gmx_sel_lexer_t *state);
//! Initializes the scanner to scan a file.
void
_gmx_sel_set_lex_input_file(gmx_sel_lexer_t *state, FILE *fp);
//! Initializes the scanner to scan a string.
void
_gmx_sel_set_lex_input_str(gmx_sel_lexer_t *state, const char *str);

//! The scanning function generated by Flex.
int
yylex(YYSTYPE *yylval, gmx_sel_lexer_t *state);
#define YY_DECL int yylex(YYSTYPE *yylval, gmx_sel_lexer_t *state)

#endif
