/*
 * Note: this file was generated by the Gromacs sse2_single kernel generator.
 *
 *                This source code is part of
 *
 *                 G   R   O   M   A   C   S
 *
 * Copyright (c) 2001-2012, The GROMACS Development Team
 *
 * Gromacs is a library for molecular simulation and trajectory analysis,
 * written by Erik Lindahl, David van der Spoel, Berk Hess, and others - for
 * a full list of developers and information, check out http://www.gromacs.org
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option) any
 * later version.
 *
 * To help fund GROMACS development, we humbly ask that you cite
 * the papers people have written on it - you can find them on the website.
 */
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <math.h>

#include "../nb_kernel.h"
#include "types/simple.h"
#include "vec.h"
#include "nrnb.h"

#include "gmx_math_x86_sse2_single.h"
#include "kernelutil_x86_sse2_single.h"

/*
 * Gromacs nonbonded kernel:   nb_kernel_ElecEw_VdwNone_GeomW4P1_VF_sse2_single
 * Electrostatics interaction: Ewald
 * VdW interaction:            None
 * Geometry:                   Water4-Particle
 * Calculate force/pot:        PotentialAndForce
 */
void
nb_kernel_ElecEw_VdwNone_GeomW4P1_VF_sse2_single
                    (t_nblist * gmx_restrict                nlist,
                     rvec * gmx_restrict                    xx,
                     rvec * gmx_restrict                    ff,
                     t_forcerec * gmx_restrict              fr,
                     t_mdatoms * gmx_restrict               mdatoms,
                     nb_kernel_data_t * gmx_restrict        kernel_data,
                     t_nrnb * gmx_restrict                  nrnb)
{
    /* Suffixes 0,1,2,3 refer to particle indices for waters in the inner or outer loop, or 
     * just 0 for non-waters.
     * Suffixes A,B,C,D refer to j loop unrolling done with SSE, e.g. for the four different
     * jnr indices corresponding to data put in the four positions in the SIMD register.
     */
    int              i_shift_offset,i_coord_offset,outeriter,inneriter;
    int              j_index_start,j_index_end,jidx,nri,inr,ggid,iidx;
    int              jnrA,jnrB,jnrC,jnrD;
    int              j_coord_offsetA,j_coord_offsetB,j_coord_offsetC,j_coord_offsetD;
    int              *iinr,*jindex,*jjnr,*shiftidx,*gid;
    real             shX,shY,shZ,rcutoff_scalar;
    real             *shiftvec,*fshift,*x,*f;
    __m128           tx,ty,tz,fscal,rcutoff,rcutoff2;
    int              vdwioffset1;
    __m128           ix1,iy1,iz1,fix1,fiy1,fiz1,iq1,isai1;
    int              vdwioffset2;
    __m128           ix2,iy2,iz2,fix2,fiy2,fiz2,iq2,isai2;
    int              vdwioffset3;
    __m128           ix3,iy3,iz3,fix3,fiy3,fiz3,iq3,isai3;
    int              vdwjidx0A,vdwjidx0B,vdwjidx0C,vdwjidx0D;
    __m128           jx0,jy0,jz0,fjx0,fjy0,fjz0,jq0,isaj0;
    __m128           dx10,dy10,dz10,rsq10,rinv10,rinvsq10,r10,qq10,c6_10,c12_10;
    __m128           dx20,dy20,dz20,rsq20,rinv20,rinvsq20,r20,qq20,c6_20,c12_20;
    __m128           dx30,dy30,dz30,rsq30,rinv30,rinvsq30,r30,qq30,c6_30,c12_30;
    __m128           velec,felec,velecsum,facel,crf,krf,krf2;
    real             *charge;
    __m128i          ewitab;
    __m128           ewtabscale,eweps,sh_ewald,ewrt,ewtabhalfspace,ewtabF,ewtabFn,ewtabD,ewtabV;
    real             *ewtab;
    __m128           mask,cutoff_mask;
    __m128           signbit = _mm_castsi128_ps( _mm_set1_epi32(0x80000000) );
    __m128           mask1   = _mm_castsi128_ps( _mm_set_epi32(0, 0, 0, 0xffffffff) );
    __m128           mask2   = _mm_castsi128_ps( _mm_set_epi32(0, 0, 0xffffffff, 0xffffffff) );
    __m128           mask3   = _mm_castsi128_ps( _mm_set_epi32(0, 0xffffffff, 0xffffffff, 0xffffffff) );
    __m128           one     = _mm_set1_ps(1.0);
    __m128           two     = _mm_set1_ps(2.0);
    x                = xx[0];
    f                = ff[0];

    nri              = nlist->nri;
    iinr             = nlist->iinr;
    jindex           = nlist->jindex;
    jjnr             = nlist->jjnr;
    shiftidx         = nlist->shift;
    gid              = nlist->gid;
    shiftvec         = fr->shift_vec[0];
    fshift           = fr->fshift[0];
    facel            = _mm_set1_ps(fr->epsfac);
    charge           = mdatoms->chargeA;

    sh_ewald         = _mm_set1_ps(fr->ic->sh_ewald);
    ewtab            = fr->ic->tabq_coul_FDV0;
    ewtabscale       = _mm_set1_ps(fr->ic->tabq_scale);
    ewtabhalfspace   = _mm_set1_ps(0.5/fr->ic->tabq_scale);

    /* Setup water-specific parameters */
    inr              = nlist->iinr[0];
    iq1              = _mm_mul_ps(facel,_mm_set1_ps(charge[inr+1]));
    iq2              = _mm_mul_ps(facel,_mm_set1_ps(charge[inr+2]));
    iq3              = _mm_mul_ps(facel,_mm_set1_ps(charge[inr+3]));

    /* Avoid stupid compiler warnings */
    jnrA = jnrB = jnrC = jnrD = 0;
    j_coord_offsetA = 0;
    j_coord_offsetB = 0;
    j_coord_offsetC = 0;
    j_coord_offsetD = 0;
  
    outeriter        = 0;
    inneriter        = 0;

    /* Start outer loop over neighborlists */
    for(iidx=0; iidx<nri; iidx++)
    {
        /* Load shift vector for this list */
        i_shift_offset   = DIM*shiftidx[iidx];
        shX              = shiftvec[i_shift_offset+XX];
        shY              = shiftvec[i_shift_offset+YY];
        shZ              = shiftvec[i_shift_offset+ZZ];

        /* Load limits for loop over neighbors */
        j_index_start    = jindex[iidx];
        j_index_end      = jindex[iidx+1];

        /* Get outer coordinate index */
        inr              = iinr[iidx];
        i_coord_offset   = DIM*inr;

        /* Load i particle coords and add shift vector */
        ix1              = _mm_set1_ps(shX + x[i_coord_offset+DIM*1+XX]);
        iy1              = _mm_set1_ps(shY + x[i_coord_offset+DIM*1+YY]);
        iz1              = _mm_set1_ps(shZ + x[i_coord_offset+DIM*1+ZZ]);
        ix2              = _mm_set1_ps(shX + x[i_coord_offset+DIM*2+XX]);
        iy2              = _mm_set1_ps(shY + x[i_coord_offset+DIM*2+YY]);
        iz2              = _mm_set1_ps(shZ + x[i_coord_offset+DIM*2+ZZ]);
        ix3              = _mm_set1_ps(shX + x[i_coord_offset+DIM*3+XX]);
        iy3              = _mm_set1_ps(shY + x[i_coord_offset+DIM*3+YY]);
        iz3              = _mm_set1_ps(shZ + x[i_coord_offset+DIM*3+ZZ]);

        fix1             = _mm_setzero_ps();
        fiy1             = _mm_setzero_ps();
        fiz1             = _mm_setzero_ps();
        fix2             = _mm_setzero_ps();
        fiy2             = _mm_setzero_ps();
        fiz2             = _mm_setzero_ps();
        fix3             = _mm_setzero_ps();
        fiy3             = _mm_setzero_ps();
        fiz3             = _mm_setzero_ps();

        /* Reset potential sums */
        velecsum         = _mm_setzero_ps();

        /* Start inner kernel loop */
        for(jidx=j_index_start; jidx<j_index_end-3; jidx+=4)
        {
            /* Get j neighbor index, and coordinate index */
            jnrA             = jjnr[jidx];
            jnrB             = jjnr[jidx+1];
            jnrC             = jjnr[jidx+2];
            jnrD             = jjnr[jidx+3];
            j_coord_offsetA  = DIM*jnrA;
            j_coord_offsetB  = DIM*jnrB;
            j_coord_offsetC  = DIM*jnrC;
            j_coord_offsetD  = DIM*jnrD;

            /* load j atom coordinates */
            gmx_mm_load_1rvec_4ptr_swizzle_ps(x+j_coord_offsetA,x+j_coord_offsetB,
                                              x+j_coord_offsetC,x+j_coord_offsetD,
                                              &jx0,&jy0,&jz0);

            /* Calculate displacement vector */
            dx10             = _mm_sub_ps(ix1,jx0);
            dy10             = _mm_sub_ps(iy1,jy0);
            dz10             = _mm_sub_ps(iz1,jz0);
            dx20             = _mm_sub_ps(ix2,jx0);
            dy20             = _mm_sub_ps(iy2,jy0);
            dz20             = _mm_sub_ps(iz2,jz0);
            dx30             = _mm_sub_ps(ix3,jx0);
            dy30             = _mm_sub_ps(iy3,jy0);
            dz30             = _mm_sub_ps(iz3,jz0);

            /* Calculate squared distance and things based on it */
            rsq10            = gmx_mm_calc_rsq_ps(dx10,dy10,dz10);
            rsq20            = gmx_mm_calc_rsq_ps(dx20,dy20,dz20);
            rsq30            = gmx_mm_calc_rsq_ps(dx30,dy30,dz30);

            rinv10           = gmx_mm_invsqrt_ps(rsq10);
            rinv20           = gmx_mm_invsqrt_ps(rsq20);
            rinv30           = gmx_mm_invsqrt_ps(rsq30);

            rinvsq10         = _mm_mul_ps(rinv10,rinv10);
            rinvsq20         = _mm_mul_ps(rinv20,rinv20);
            rinvsq30         = _mm_mul_ps(rinv30,rinv30);

            /* Load parameters for j particles */
            jq0              = gmx_mm_load_4real_swizzle_ps(charge+jnrA+0,charge+jnrB+0,
                                                              charge+jnrC+0,charge+jnrD+0);

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            r10              = _mm_mul_ps(rsq10,rinv10);

            qq10             = _mm_mul_ps(iq1,jq0);

            /* EWALD ELECTROSTATICS */

            /* Calculate Ewald table index by multiplying r with scale and truncate to integer */
            ewrt             = _mm_mul_ps(r10,ewtabscale);
            ewitab           = _mm_cvttps_epi32(ewrt);
            eweps            = _mm_sub_ps(ewrt,_mm_cvtepi32_ps(ewitab));
            ewitab           = _mm_slli_epi32(ewitab,2);
            ewtabF           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,0) );
            ewtabD           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,1) );
            ewtabV           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,2) );
            ewtabFn          = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,3) );
            _MM_TRANSPOSE4_PS(ewtabF,ewtabD,ewtabV,ewtabFn);
            felec            = _mm_add_ps(ewtabF,_mm_mul_ps(eweps,ewtabD));
            velec            = _mm_sub_ps(ewtabV,_mm_mul_ps(_mm_mul_ps(ewtabhalfspace,eweps),_mm_add_ps(ewtabF,felec)));
            velec            = _mm_mul_ps(qq10,_mm_sub_ps(rinv10,velec));
            felec            = _mm_mul_ps(_mm_mul_ps(qq10,rinv10),_mm_sub_ps(rinvsq10,felec));

            /* Update potential sums from outer loop */
            velecsum         = _mm_add_ps(velecsum,velec);

            fscal            = felec;

            /* Calculate temporary vectorial force */
            tx               = _mm_mul_ps(fscal,dx10);
            ty               = _mm_mul_ps(fscal,dy10);
            tz               = _mm_mul_ps(fscal,dz10);

            /* Update vectorial force */
            fix1             = _mm_add_ps(fix1,tx);
            fiy1             = _mm_add_ps(fiy1,ty);
            fiz1             = _mm_add_ps(fiz1,tz);

            gmx_mm_decrement_1rvec_4ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                   f+j_coord_offsetC,f+j_coord_offsetD,
                                                   tx,ty,tz);

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            r20              = _mm_mul_ps(rsq20,rinv20);

            qq20             = _mm_mul_ps(iq2,jq0);

            /* EWALD ELECTROSTATICS */

            /* Calculate Ewald table index by multiplying r with scale and truncate to integer */
            ewrt             = _mm_mul_ps(r20,ewtabscale);
            ewitab           = _mm_cvttps_epi32(ewrt);
            eweps            = _mm_sub_ps(ewrt,_mm_cvtepi32_ps(ewitab));
            ewitab           = _mm_slli_epi32(ewitab,2);
            ewtabF           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,0) );
            ewtabD           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,1) );
            ewtabV           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,2) );
            ewtabFn          = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,3) );
            _MM_TRANSPOSE4_PS(ewtabF,ewtabD,ewtabV,ewtabFn);
            felec            = _mm_add_ps(ewtabF,_mm_mul_ps(eweps,ewtabD));
            velec            = _mm_sub_ps(ewtabV,_mm_mul_ps(_mm_mul_ps(ewtabhalfspace,eweps),_mm_add_ps(ewtabF,felec)));
            velec            = _mm_mul_ps(qq20,_mm_sub_ps(rinv20,velec));
            felec            = _mm_mul_ps(_mm_mul_ps(qq20,rinv20),_mm_sub_ps(rinvsq20,felec));

            /* Update potential sums from outer loop */
            velecsum         = _mm_add_ps(velecsum,velec);

            fscal            = felec;

            /* Calculate temporary vectorial force */
            tx               = _mm_mul_ps(fscal,dx20);
            ty               = _mm_mul_ps(fscal,dy20);
            tz               = _mm_mul_ps(fscal,dz20);

            /* Update vectorial force */
            fix2             = _mm_add_ps(fix2,tx);
            fiy2             = _mm_add_ps(fiy2,ty);
            fiz2             = _mm_add_ps(fiz2,tz);

            gmx_mm_decrement_1rvec_4ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                   f+j_coord_offsetC,f+j_coord_offsetD,
                                                   tx,ty,tz);

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            r30              = _mm_mul_ps(rsq30,rinv30);

            qq30             = _mm_mul_ps(iq3,jq0);

            /* EWALD ELECTROSTATICS */

            /* Calculate Ewald table index by multiplying r with scale and truncate to integer */
            ewrt             = _mm_mul_ps(r30,ewtabscale);
            ewitab           = _mm_cvttps_epi32(ewrt);
            eweps            = _mm_sub_ps(ewrt,_mm_cvtepi32_ps(ewitab));
            ewitab           = _mm_slli_epi32(ewitab,2);
            ewtabF           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,0) );
            ewtabD           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,1) );
            ewtabV           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,2) );
            ewtabFn          = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,3) );
            _MM_TRANSPOSE4_PS(ewtabF,ewtabD,ewtabV,ewtabFn);
            felec            = _mm_add_ps(ewtabF,_mm_mul_ps(eweps,ewtabD));
            velec            = _mm_sub_ps(ewtabV,_mm_mul_ps(_mm_mul_ps(ewtabhalfspace,eweps),_mm_add_ps(ewtabF,felec)));
            velec            = _mm_mul_ps(qq30,_mm_sub_ps(rinv30,velec));
            felec            = _mm_mul_ps(_mm_mul_ps(qq30,rinv30),_mm_sub_ps(rinvsq30,felec));

            /* Update potential sums from outer loop */
            velecsum         = _mm_add_ps(velecsum,velec);

            fscal            = felec;

            /* Calculate temporary vectorial force */
            tx               = _mm_mul_ps(fscal,dx30);
            ty               = _mm_mul_ps(fscal,dy30);
            tz               = _mm_mul_ps(fscal,dz30);

            /* Update vectorial force */
            fix3             = _mm_add_ps(fix3,tx);
            fiy3             = _mm_add_ps(fiy3,ty);
            fiz3             = _mm_add_ps(fiz3,tz);

            gmx_mm_decrement_1rvec_4ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                   f+j_coord_offsetC,f+j_coord_offsetD,
                                                   tx,ty,tz);

            /* Inner loop uses 123 flops */
        }

        /* Treat remaining (non-multiple-of-4) j particles */
        if(jidx<j_index_end)
        {
            if(jidx<j_index_end-2)
            {
                jnrA             = jjnr[jidx];
                jnrB             = jjnr[jidx+1];
                jnrC             = jjnr[jidx+2];
                j_coord_offsetA  = DIM*jnrA;
                j_coord_offsetB  = DIM*jnrB;
                j_coord_offsetC  = DIM*jnrC;
                /* load j atom coordinates */
                gmx_mm_load_1rvec_3ptr_swizzle_ps(x+j_coord_offsetA,x+j_coord_offsetB,
                                                  x+j_coord_offsetC,
                                                  &jx0,&jy0,&jz0);
                /* Load parameters for j particles */
                jq0              = gmx_mm_load_3real_swizzle_ps(charge+jnrA+0,charge+jnrB+0,
                                                                  charge+jnrC+0);
                mask             = mask3;
            }
            else if(jidx<j_index_end-1)
            {
                jnrA             = jjnr[jidx];
                jnrB             = jjnr[jidx+1];
                j_coord_offsetA  = DIM*jnrA;
                j_coord_offsetB  = DIM*jnrB;
                /* load j atom coordinates */
                gmx_mm_load_1rvec_2ptr_swizzle_ps(x+j_coord_offsetA,x+j_coord_offsetB,
                                                  &jx0,&jy0,&jz0);
                /* Load parameters for j particles */
                jq0              = gmx_mm_load_2real_swizzle_ps(charge+jnrA+0,charge+jnrB+0);
                mask             = mask2;
            }
            else
            {
                jnrA             = jjnr[jidx];
                j_coord_offsetA  = DIM*jnrA;
                /* load j atom coordinates */
                gmx_mm_load_1rvec_1ptr_swizzle_ps(x+j_coord_offsetA,
                                                  &jx0,&jy0,&jz0);
                /* Load parameters for j particles */
                jq0              = gmx_mm_load_1real_ps(charge+jnrA+0);
                mask             = mask1;
            }

            /* Get j neighbor index, and coordinate index */

            /* Calculate displacement vector */
            dx10             = _mm_sub_ps(ix1,jx0);
            dy10             = _mm_sub_ps(iy1,jy0);
            dz10             = _mm_sub_ps(iz1,jz0);
            dx20             = _mm_sub_ps(ix2,jx0);
            dy20             = _mm_sub_ps(iy2,jy0);
            dz20             = _mm_sub_ps(iz2,jz0);
            dx30             = _mm_sub_ps(ix3,jx0);
            dy30             = _mm_sub_ps(iy3,jy0);
            dz30             = _mm_sub_ps(iz3,jz0);

            /* Calculate squared distance and things based on it */
            rsq10            = gmx_mm_calc_rsq_ps(dx10,dy10,dz10);
            rsq20            = gmx_mm_calc_rsq_ps(dx20,dy20,dz20);
            rsq30            = gmx_mm_calc_rsq_ps(dx30,dy30,dz30);

            rinv10           = gmx_mm_invsqrt_ps(rsq10);
            rinv20           = gmx_mm_invsqrt_ps(rsq20);
            rinv30           = gmx_mm_invsqrt_ps(rsq30);

            rinvsq10         = _mm_mul_ps(rinv10,rinv10);
            rinvsq20         = _mm_mul_ps(rinv20,rinv20);
            rinvsq30         = _mm_mul_ps(rinv30,rinv30);

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            r10              = _mm_mul_ps(rsq10,rinv10);

            qq10             = _mm_mul_ps(iq1,jq0);

            /* EWALD ELECTROSTATICS */

            /* Calculate Ewald table index by multiplying r with scale and truncate to integer */
            ewrt             = _mm_mul_ps(r10,ewtabscale);
            ewitab           = _mm_cvttps_epi32(ewrt);
            eweps            = _mm_sub_ps(ewrt,_mm_cvtepi32_ps(ewitab));
            ewitab           = _mm_slli_epi32(ewitab,2);
            ewtabF           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,0) );
            ewtabD           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,1) );
            ewtabV           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,2) );
            ewtabFn          = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,3) );
            _MM_TRANSPOSE4_PS(ewtabF,ewtabD,ewtabV,ewtabFn);
            felec            = _mm_add_ps(ewtabF,_mm_mul_ps(eweps,ewtabD));
            velec            = _mm_sub_ps(ewtabV,_mm_mul_ps(_mm_mul_ps(ewtabhalfspace,eweps),_mm_add_ps(ewtabF,felec)));
            velec            = _mm_mul_ps(qq10,_mm_sub_ps(rinv10,velec));
            felec            = _mm_mul_ps(_mm_mul_ps(qq10,rinv10),_mm_sub_ps(rinvsq10,felec));

            /* Update potential sums from outer loop */
            velecsum         = _mm_add_ps(velecsum,_mm_and_ps(velec,mask));

            fscal            = felec;

            fscal            = _mm_and_ps(fscal,mask);

            /* Calculate temporary vectorial force */
            tx               = _mm_mul_ps(fscal,dx10);
            ty               = _mm_mul_ps(fscal,dy10);
            tz               = _mm_mul_ps(fscal,dz10);

            /* Update vectorial force */
            fix1             = _mm_add_ps(fix1,tx);
            fiy1             = _mm_add_ps(fiy1,ty);
            fiz1             = _mm_add_ps(fiz1,tz);

            if(jidx<j_index_end-2)
            {
                gmx_mm_decrement_1rvec_3ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                       f+j_coord_offsetC,
                                                       tx,ty,tz);
            }
            else if(jidx<j_index_end-1)
            {
                gmx_mm_decrement_1rvec_2ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                       tx,ty,tz);
            }
            else
            {
                gmx_mm_decrement_1rvec_1ptr_swizzle_ps(f+j_coord_offsetA,
                                                       tx,ty,tz);
            }

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            r20              = _mm_mul_ps(rsq20,rinv20);

            qq20             = _mm_mul_ps(iq2,jq0);

            /* EWALD ELECTROSTATICS */

            /* Calculate Ewald table index by multiplying r with scale and truncate to integer */
            ewrt             = _mm_mul_ps(r20,ewtabscale);
            ewitab           = _mm_cvttps_epi32(ewrt);
            eweps            = _mm_sub_ps(ewrt,_mm_cvtepi32_ps(ewitab));
            ewitab           = _mm_slli_epi32(ewitab,2);
            ewtabF           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,0) );
            ewtabD           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,1) );
            ewtabV           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,2) );
            ewtabFn          = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,3) );
            _MM_TRANSPOSE4_PS(ewtabF,ewtabD,ewtabV,ewtabFn);
            felec            = _mm_add_ps(ewtabF,_mm_mul_ps(eweps,ewtabD));
            velec            = _mm_sub_ps(ewtabV,_mm_mul_ps(_mm_mul_ps(ewtabhalfspace,eweps),_mm_add_ps(ewtabF,felec)));
            velec            = _mm_mul_ps(qq20,_mm_sub_ps(rinv20,velec));
            felec            = _mm_mul_ps(_mm_mul_ps(qq20,rinv20),_mm_sub_ps(rinvsq20,felec));

            /* Update potential sums from outer loop */
            velecsum         = _mm_add_ps(velecsum,_mm_and_ps(velec,mask));

            fscal            = felec;

            fscal            = _mm_and_ps(fscal,mask);

            /* Calculate temporary vectorial force */
            tx               = _mm_mul_ps(fscal,dx20);
            ty               = _mm_mul_ps(fscal,dy20);
            tz               = _mm_mul_ps(fscal,dz20);

            /* Update vectorial force */
            fix2             = _mm_add_ps(fix2,tx);
            fiy2             = _mm_add_ps(fiy2,ty);
            fiz2             = _mm_add_ps(fiz2,tz);

            if(jidx<j_index_end-2)
            {
                gmx_mm_decrement_1rvec_3ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                       f+j_coord_offsetC,
                                                       tx,ty,tz);
            }
            else if(jidx<j_index_end-1)
            {
                gmx_mm_decrement_1rvec_2ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                       tx,ty,tz);
            }
            else
            {
                gmx_mm_decrement_1rvec_1ptr_swizzle_ps(f+j_coord_offsetA,
                                                       tx,ty,tz);
            }

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            r30              = _mm_mul_ps(rsq30,rinv30);

            qq30             = _mm_mul_ps(iq3,jq0);

            /* EWALD ELECTROSTATICS */

            /* Calculate Ewald table index by multiplying r with scale and truncate to integer */
            ewrt             = _mm_mul_ps(r30,ewtabscale);
            ewitab           = _mm_cvttps_epi32(ewrt);
            eweps            = _mm_sub_ps(ewrt,_mm_cvtepi32_ps(ewitab));
            ewitab           = _mm_slli_epi32(ewitab,2);
            ewtabF           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,0) );
            ewtabD           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,1) );
            ewtabV           = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,2) );
            ewtabFn          = _mm_load_ps( ewtab + gmx_mm_extract_epi32(ewitab,3) );
            _MM_TRANSPOSE4_PS(ewtabF,ewtabD,ewtabV,ewtabFn);
            felec            = _mm_add_ps(ewtabF,_mm_mul_ps(eweps,ewtabD));
            velec            = _mm_sub_ps(ewtabV,_mm_mul_ps(_mm_mul_ps(ewtabhalfspace,eweps),_mm_add_ps(ewtabF,felec)));
            velec            = _mm_mul_ps(qq30,_mm_sub_ps(rinv30,velec));
            felec            = _mm_mul_ps(_mm_mul_ps(qq30,rinv30),_mm_sub_ps(rinvsq30,felec));

            /* Update potential sums from outer loop */
            velecsum         = _mm_add_ps(velecsum,_mm_and_ps(velec,mask));

            fscal            = felec;

            fscal            = _mm_and_ps(fscal,mask);

            /* Calculate temporary vectorial force */
            tx               = _mm_mul_ps(fscal,dx30);
            ty               = _mm_mul_ps(fscal,dy30);
            tz               = _mm_mul_ps(fscal,dz30);

            /* Update vectorial force */
            fix3             = _mm_add_ps(fix3,tx);
            fiy3             = _mm_add_ps(fiy3,ty);
            fiz3             = _mm_add_ps(fiz3,tz);

            if(jidx<j_index_end-2)
            {
                gmx_mm_decrement_1rvec_3ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                       f+j_coord_offsetC,
                                                       tx,ty,tz);
            }
            else if(jidx<j_index_end-1)
            {
                gmx_mm_decrement_1rvec_2ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                       tx,ty,tz);
            }
            else
            {
                gmx_mm_decrement_1rvec_1ptr_swizzle_ps(f+j_coord_offsetA,
                                                       tx,ty,tz);
            }

        }
        /* End of innermost loop */

        gmx_mm_update_iforce_3atom_swizzle_ps(fix1,fiy1,fiz1,fix2,fiy2,fiz2,fix3,fiy3,fiz3,
                                              f+i_coord_offset+DIM,fshift+i_shift_offset);

        ggid                        = gid[iidx];
        /* Update potential energies */
        gmx_mm_update_1pot_ps(velecsum,kernel_data->energygrp_elec+ggid);

        /* Increment number of inner iterations */
        inneriter                  += j_index_end - j_index_start;

        /* Outer loop uses 28 flops */
    }

    /* Increment number of outer iterations */
    outeriter        += nri;

    /* Update outer/inner flops */

    inc_nrnb(nrnb,eNR_NBKERNEL_ELEC_W4_VF,outeriter*28 + inneriter*123);
}
/*
 * Gromacs nonbonded kernel:   nb_kernel_ElecEw_VdwNone_GeomW4P1_F_sse2_single
 * Electrostatics interaction: Ewald
 * VdW interaction:            None
 * Geometry:                   Water4-Particle
 * Calculate force/pot:        Force
 */
void
nb_kernel_ElecEw_VdwNone_GeomW4P1_F_sse2_single
                    (t_nblist * gmx_restrict                nlist,
                     rvec * gmx_restrict                    xx,
                     rvec * gmx_restrict                    ff,
                     t_forcerec * gmx_restrict              fr,
                     t_mdatoms * gmx_restrict               mdatoms,
                     nb_kernel_data_t * gmx_restrict        kernel_data,
                     t_nrnb * gmx_restrict                  nrnb)
{
    /* Suffixes 0,1,2,3 refer to particle indices for waters in the inner or outer loop, or 
     * just 0 for non-waters.
     * Suffixes A,B,C,D refer to j loop unrolling done with SSE, e.g. for the four different
     * jnr indices corresponding to data put in the four positions in the SIMD register.
     */
    int              i_shift_offset,i_coord_offset,outeriter,inneriter;
    int              j_index_start,j_index_end,jidx,nri,inr,ggid,iidx;
    int              jnrA,jnrB,jnrC,jnrD;
    int              j_coord_offsetA,j_coord_offsetB,j_coord_offsetC,j_coord_offsetD;
    int              *iinr,*jindex,*jjnr,*shiftidx,*gid;
    real             shX,shY,shZ,rcutoff_scalar;
    real             *shiftvec,*fshift,*x,*f;
    __m128           tx,ty,tz,fscal,rcutoff,rcutoff2;
    int              vdwioffset1;
    __m128           ix1,iy1,iz1,fix1,fiy1,fiz1,iq1,isai1;
    int              vdwioffset2;
    __m128           ix2,iy2,iz2,fix2,fiy2,fiz2,iq2,isai2;
    int              vdwioffset3;
    __m128           ix3,iy3,iz3,fix3,fiy3,fiz3,iq3,isai3;
    int              vdwjidx0A,vdwjidx0B,vdwjidx0C,vdwjidx0D;
    __m128           jx0,jy0,jz0,fjx0,fjy0,fjz0,jq0,isaj0;
    __m128           dx10,dy10,dz10,rsq10,rinv10,rinvsq10,r10,qq10,c6_10,c12_10;
    __m128           dx20,dy20,dz20,rsq20,rinv20,rinvsq20,r20,qq20,c6_20,c12_20;
    __m128           dx30,dy30,dz30,rsq30,rinv30,rinvsq30,r30,qq30,c6_30,c12_30;
    __m128           velec,felec,velecsum,facel,crf,krf,krf2;
    real             *charge;
    __m128i          ewitab;
    __m128           ewtabscale,eweps,sh_ewald,ewrt,ewtabhalfspace,ewtabF,ewtabFn,ewtabD,ewtabV;
    real             *ewtab;
    __m128           mask,cutoff_mask;
    __m128           signbit = _mm_castsi128_ps( _mm_set1_epi32(0x80000000) );
    __m128           mask1   = _mm_castsi128_ps( _mm_set_epi32(0, 0, 0, 0xffffffff) );
    __m128           mask2   = _mm_castsi128_ps( _mm_set_epi32(0, 0, 0xffffffff, 0xffffffff) );
    __m128           mask3   = _mm_castsi128_ps( _mm_set_epi32(0, 0xffffffff, 0xffffffff, 0xffffffff) );
    __m128           one     = _mm_set1_ps(1.0);
    __m128           two     = _mm_set1_ps(2.0);
    x                = xx[0];
    f                = ff[0];

    nri              = nlist->nri;
    iinr             = nlist->iinr;
    jindex           = nlist->jindex;
    jjnr             = nlist->jjnr;
    shiftidx         = nlist->shift;
    gid              = nlist->gid;
    shiftvec         = fr->shift_vec[0];
    fshift           = fr->fshift[0];
    facel            = _mm_set1_ps(fr->epsfac);
    charge           = mdatoms->chargeA;

    sh_ewald         = _mm_set1_ps(fr->ic->sh_ewald);
    ewtab            = fr->ic->tabq_coul_F;
    ewtabscale       = _mm_set1_ps(fr->ic->tabq_scale);
    ewtabhalfspace   = _mm_set1_ps(0.5/fr->ic->tabq_scale);

    /* Setup water-specific parameters */
    inr              = nlist->iinr[0];
    iq1              = _mm_mul_ps(facel,_mm_set1_ps(charge[inr+1]));
    iq2              = _mm_mul_ps(facel,_mm_set1_ps(charge[inr+2]));
    iq3              = _mm_mul_ps(facel,_mm_set1_ps(charge[inr+3]));

    /* Avoid stupid compiler warnings */
    jnrA = jnrB = jnrC = jnrD = 0;
    j_coord_offsetA = 0;
    j_coord_offsetB = 0;
    j_coord_offsetC = 0;
    j_coord_offsetD = 0;
  
    outeriter        = 0;
    inneriter        = 0;

    /* Start outer loop over neighborlists */
    for(iidx=0; iidx<nri; iidx++)
    {
        /* Load shift vector for this list */
        i_shift_offset   = DIM*shiftidx[iidx];
        shX              = shiftvec[i_shift_offset+XX];
        shY              = shiftvec[i_shift_offset+YY];
        shZ              = shiftvec[i_shift_offset+ZZ];

        /* Load limits for loop over neighbors */
        j_index_start    = jindex[iidx];
        j_index_end      = jindex[iidx+1];

        /* Get outer coordinate index */
        inr              = iinr[iidx];
        i_coord_offset   = DIM*inr;

        /* Load i particle coords and add shift vector */
        ix1              = _mm_set1_ps(shX + x[i_coord_offset+DIM*1+XX]);
        iy1              = _mm_set1_ps(shY + x[i_coord_offset+DIM*1+YY]);
        iz1              = _mm_set1_ps(shZ + x[i_coord_offset+DIM*1+ZZ]);
        ix2              = _mm_set1_ps(shX + x[i_coord_offset+DIM*2+XX]);
        iy2              = _mm_set1_ps(shY + x[i_coord_offset+DIM*2+YY]);
        iz2              = _mm_set1_ps(shZ + x[i_coord_offset+DIM*2+ZZ]);
        ix3              = _mm_set1_ps(shX + x[i_coord_offset+DIM*3+XX]);
        iy3              = _mm_set1_ps(shY + x[i_coord_offset+DIM*3+YY]);
        iz3              = _mm_set1_ps(shZ + x[i_coord_offset+DIM*3+ZZ]);

        fix1             = _mm_setzero_ps();
        fiy1             = _mm_setzero_ps();
        fiz1             = _mm_setzero_ps();
        fix2             = _mm_setzero_ps();
        fiy2             = _mm_setzero_ps();
        fiz2             = _mm_setzero_ps();
        fix3             = _mm_setzero_ps();
        fiy3             = _mm_setzero_ps();
        fiz3             = _mm_setzero_ps();

        /* Start inner kernel loop */
        for(jidx=j_index_start; jidx<j_index_end-3; jidx+=4)
        {
            /* Get j neighbor index, and coordinate index */
            jnrA             = jjnr[jidx];
            jnrB             = jjnr[jidx+1];
            jnrC             = jjnr[jidx+2];
            jnrD             = jjnr[jidx+3];
            j_coord_offsetA  = DIM*jnrA;
            j_coord_offsetB  = DIM*jnrB;
            j_coord_offsetC  = DIM*jnrC;
            j_coord_offsetD  = DIM*jnrD;

            /* load j atom coordinates */
            gmx_mm_load_1rvec_4ptr_swizzle_ps(x+j_coord_offsetA,x+j_coord_offsetB,
                                              x+j_coord_offsetC,x+j_coord_offsetD,
                                              &jx0,&jy0,&jz0);

            /* Calculate displacement vector */
            dx10             = _mm_sub_ps(ix1,jx0);
            dy10             = _mm_sub_ps(iy1,jy0);
            dz10             = _mm_sub_ps(iz1,jz0);
            dx20             = _mm_sub_ps(ix2,jx0);
            dy20             = _mm_sub_ps(iy2,jy0);
            dz20             = _mm_sub_ps(iz2,jz0);
            dx30             = _mm_sub_ps(ix3,jx0);
            dy30             = _mm_sub_ps(iy3,jy0);
            dz30             = _mm_sub_ps(iz3,jz0);

            /* Calculate squared distance and things based on it */
            rsq10            = gmx_mm_calc_rsq_ps(dx10,dy10,dz10);
            rsq20            = gmx_mm_calc_rsq_ps(dx20,dy20,dz20);
            rsq30            = gmx_mm_calc_rsq_ps(dx30,dy30,dz30);

            rinv10           = gmx_mm_invsqrt_ps(rsq10);
            rinv20           = gmx_mm_invsqrt_ps(rsq20);
            rinv30           = gmx_mm_invsqrt_ps(rsq30);

            rinvsq10         = _mm_mul_ps(rinv10,rinv10);
            rinvsq20         = _mm_mul_ps(rinv20,rinv20);
            rinvsq30         = _mm_mul_ps(rinv30,rinv30);

            /* Load parameters for j particles */
            jq0              = gmx_mm_load_4real_swizzle_ps(charge+jnrA+0,charge+jnrB+0,
                                                              charge+jnrC+0,charge+jnrD+0);

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            r10              = _mm_mul_ps(rsq10,rinv10);

            qq10             = _mm_mul_ps(iq1,jq0);

            /* EWALD ELECTROSTATICS */

            /* Calculate Ewald table index by multiplying r with scale and truncate to integer */
            ewrt             = _mm_mul_ps(r10,ewtabscale);
            ewitab           = _mm_cvttps_epi32(ewrt);
            eweps            = _mm_sub_ps(ewrt,_mm_cvtepi32_ps(ewitab));
            gmx_mm_load_4pair_swizzle_ps(ewtab+gmx_mm_extract_epi32(ewitab,0),ewtab+gmx_mm_extract_epi32(ewitab,1),
                                         ewtab+gmx_mm_extract_epi32(ewitab,2),ewtab+gmx_mm_extract_epi32(ewitab,3),
                                         &ewtabF,&ewtabFn);
            felec            = _mm_add_ps(_mm_mul_ps( _mm_sub_ps(one,eweps),ewtabF),_mm_mul_ps(eweps,ewtabFn));
            felec            = _mm_mul_ps(_mm_mul_ps(qq10,rinv10),_mm_sub_ps(rinvsq10,felec));

            fscal            = felec;

            /* Calculate temporary vectorial force */
            tx               = _mm_mul_ps(fscal,dx10);
            ty               = _mm_mul_ps(fscal,dy10);
            tz               = _mm_mul_ps(fscal,dz10);

            /* Update vectorial force */
            fix1             = _mm_add_ps(fix1,tx);
            fiy1             = _mm_add_ps(fiy1,ty);
            fiz1             = _mm_add_ps(fiz1,tz);

            gmx_mm_decrement_1rvec_4ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                   f+j_coord_offsetC,f+j_coord_offsetD,
                                                   tx,ty,tz);

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            r20              = _mm_mul_ps(rsq20,rinv20);

            qq20             = _mm_mul_ps(iq2,jq0);

            /* EWALD ELECTROSTATICS */

            /* Calculate Ewald table index by multiplying r with scale and truncate to integer */
            ewrt             = _mm_mul_ps(r20,ewtabscale);
            ewitab           = _mm_cvttps_epi32(ewrt);
            eweps            = _mm_sub_ps(ewrt,_mm_cvtepi32_ps(ewitab));
            gmx_mm_load_4pair_swizzle_ps(ewtab+gmx_mm_extract_epi32(ewitab,0),ewtab+gmx_mm_extract_epi32(ewitab,1),
                                         ewtab+gmx_mm_extract_epi32(ewitab,2),ewtab+gmx_mm_extract_epi32(ewitab,3),
                                         &ewtabF,&ewtabFn);
            felec            = _mm_add_ps(_mm_mul_ps( _mm_sub_ps(one,eweps),ewtabF),_mm_mul_ps(eweps,ewtabFn));
            felec            = _mm_mul_ps(_mm_mul_ps(qq20,rinv20),_mm_sub_ps(rinvsq20,felec));

            fscal            = felec;

            /* Calculate temporary vectorial force */
            tx               = _mm_mul_ps(fscal,dx20);
            ty               = _mm_mul_ps(fscal,dy20);
            tz               = _mm_mul_ps(fscal,dz20);

            /* Update vectorial force */
            fix2             = _mm_add_ps(fix2,tx);
            fiy2             = _mm_add_ps(fiy2,ty);
            fiz2             = _mm_add_ps(fiz2,tz);

            gmx_mm_decrement_1rvec_4ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                   f+j_coord_offsetC,f+j_coord_offsetD,
                                                   tx,ty,tz);

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            r30              = _mm_mul_ps(rsq30,rinv30);

            qq30             = _mm_mul_ps(iq3,jq0);

            /* EWALD ELECTROSTATICS */

            /* Calculate Ewald table index by multiplying r with scale and truncate to integer */
            ewrt             = _mm_mul_ps(r30,ewtabscale);
            ewitab           = _mm_cvttps_epi32(ewrt);
            eweps            = _mm_sub_ps(ewrt,_mm_cvtepi32_ps(ewitab));
            gmx_mm_load_4pair_swizzle_ps(ewtab+gmx_mm_extract_epi32(ewitab,0),ewtab+gmx_mm_extract_epi32(ewitab,1),
                                         ewtab+gmx_mm_extract_epi32(ewitab,2),ewtab+gmx_mm_extract_epi32(ewitab,3),
                                         &ewtabF,&ewtabFn);
            felec            = _mm_add_ps(_mm_mul_ps( _mm_sub_ps(one,eweps),ewtabF),_mm_mul_ps(eweps,ewtabFn));
            felec            = _mm_mul_ps(_mm_mul_ps(qq30,rinv30),_mm_sub_ps(rinvsq30,felec));

            fscal            = felec;

            /* Calculate temporary vectorial force */
            tx               = _mm_mul_ps(fscal,dx30);
            ty               = _mm_mul_ps(fscal,dy30);
            tz               = _mm_mul_ps(fscal,dz30);

            /* Update vectorial force */
            fix3             = _mm_add_ps(fix3,tx);
            fiy3             = _mm_add_ps(fiy3,ty);
            fiz3             = _mm_add_ps(fiz3,tz);

            gmx_mm_decrement_1rvec_4ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                   f+j_coord_offsetC,f+j_coord_offsetD,
                                                   tx,ty,tz);

            /* Inner loop uses 108 flops */
        }

        /* Treat remaining (non-multiple-of-4) j particles */
        if(jidx<j_index_end)
        {
            if(jidx<j_index_end-2)
            {
                jnrA             = jjnr[jidx];
                jnrB             = jjnr[jidx+1];
                jnrC             = jjnr[jidx+2];
                j_coord_offsetA  = DIM*jnrA;
                j_coord_offsetB  = DIM*jnrB;
                j_coord_offsetC  = DIM*jnrC;
                /* load j atom coordinates */
                gmx_mm_load_1rvec_3ptr_swizzle_ps(x+j_coord_offsetA,x+j_coord_offsetB,
                                                  x+j_coord_offsetC,
                                                  &jx0,&jy0,&jz0);
                /* Load parameters for j particles */
                jq0              = gmx_mm_load_3real_swizzle_ps(charge+jnrA+0,charge+jnrB+0,
                                                                  charge+jnrC+0);
                mask             = mask3;
            }
            else if(jidx<j_index_end-1)
            {
                jnrA             = jjnr[jidx];
                jnrB             = jjnr[jidx+1];
                j_coord_offsetA  = DIM*jnrA;
                j_coord_offsetB  = DIM*jnrB;
                /* load j atom coordinates */
                gmx_mm_load_1rvec_2ptr_swizzle_ps(x+j_coord_offsetA,x+j_coord_offsetB,
                                                  &jx0,&jy0,&jz0);
                /* Load parameters for j particles */
                jq0              = gmx_mm_load_2real_swizzle_ps(charge+jnrA+0,charge+jnrB+0);
                mask             = mask2;
            }
            else
            {
                jnrA             = jjnr[jidx];
                j_coord_offsetA  = DIM*jnrA;
                /* load j atom coordinates */
                gmx_mm_load_1rvec_1ptr_swizzle_ps(x+j_coord_offsetA,
                                                  &jx0,&jy0,&jz0);
                /* Load parameters for j particles */
                jq0              = gmx_mm_load_1real_ps(charge+jnrA+0);
                mask             = mask1;
            }

            /* Get j neighbor index, and coordinate index */

            /* Calculate displacement vector */
            dx10             = _mm_sub_ps(ix1,jx0);
            dy10             = _mm_sub_ps(iy1,jy0);
            dz10             = _mm_sub_ps(iz1,jz0);
            dx20             = _mm_sub_ps(ix2,jx0);
            dy20             = _mm_sub_ps(iy2,jy0);
            dz20             = _mm_sub_ps(iz2,jz0);
            dx30             = _mm_sub_ps(ix3,jx0);
            dy30             = _mm_sub_ps(iy3,jy0);
            dz30             = _mm_sub_ps(iz3,jz0);

            /* Calculate squared distance and things based on it */
            rsq10            = gmx_mm_calc_rsq_ps(dx10,dy10,dz10);
            rsq20            = gmx_mm_calc_rsq_ps(dx20,dy20,dz20);
            rsq30            = gmx_mm_calc_rsq_ps(dx30,dy30,dz30);

            rinv10           = gmx_mm_invsqrt_ps(rsq10);
            rinv20           = gmx_mm_invsqrt_ps(rsq20);
            rinv30           = gmx_mm_invsqrt_ps(rsq30);

            rinvsq10         = _mm_mul_ps(rinv10,rinv10);
            rinvsq20         = _mm_mul_ps(rinv20,rinv20);
            rinvsq30         = _mm_mul_ps(rinv30,rinv30);

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            r10              = _mm_mul_ps(rsq10,rinv10);

            qq10             = _mm_mul_ps(iq1,jq0);

            /* EWALD ELECTROSTATICS */

            /* Calculate Ewald table index by multiplying r with scale and truncate to integer */
            ewrt             = _mm_mul_ps(r10,ewtabscale);
            ewitab           = _mm_cvttps_epi32(ewrt);
            eweps            = _mm_sub_ps(ewrt,_mm_cvtepi32_ps(ewitab));
            gmx_mm_load_4pair_swizzle_ps(ewtab+gmx_mm_extract_epi32(ewitab,0),ewtab+gmx_mm_extract_epi32(ewitab,1),
                                         ewtab+gmx_mm_extract_epi32(ewitab,2),ewtab+gmx_mm_extract_epi32(ewitab,3),
                                         &ewtabF,&ewtabFn);
            felec            = _mm_add_ps(_mm_mul_ps( _mm_sub_ps(one,eweps),ewtabF),_mm_mul_ps(eweps,ewtabFn));
            felec            = _mm_mul_ps(_mm_mul_ps(qq10,rinv10),_mm_sub_ps(rinvsq10,felec));

            fscal            = felec;

            fscal            = _mm_and_ps(fscal,mask);

            /* Calculate temporary vectorial force */
            tx               = _mm_mul_ps(fscal,dx10);
            ty               = _mm_mul_ps(fscal,dy10);
            tz               = _mm_mul_ps(fscal,dz10);

            /* Update vectorial force */
            fix1             = _mm_add_ps(fix1,tx);
            fiy1             = _mm_add_ps(fiy1,ty);
            fiz1             = _mm_add_ps(fiz1,tz);

            if(jidx<j_index_end-2)
            {
                gmx_mm_decrement_1rvec_3ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                       f+j_coord_offsetC,
                                                       tx,ty,tz);
            }
            else if(jidx<j_index_end-1)
            {
                gmx_mm_decrement_1rvec_2ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                       tx,ty,tz);
            }
            else
            {
                gmx_mm_decrement_1rvec_1ptr_swizzle_ps(f+j_coord_offsetA,
                                                       tx,ty,tz);
            }

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            r20              = _mm_mul_ps(rsq20,rinv20);

            qq20             = _mm_mul_ps(iq2,jq0);

            /* EWALD ELECTROSTATICS */

            /* Calculate Ewald table index by multiplying r with scale and truncate to integer */
            ewrt             = _mm_mul_ps(r20,ewtabscale);
            ewitab           = _mm_cvttps_epi32(ewrt);
            eweps            = _mm_sub_ps(ewrt,_mm_cvtepi32_ps(ewitab));
            gmx_mm_load_4pair_swizzle_ps(ewtab+gmx_mm_extract_epi32(ewitab,0),ewtab+gmx_mm_extract_epi32(ewitab,1),
                                         ewtab+gmx_mm_extract_epi32(ewitab,2),ewtab+gmx_mm_extract_epi32(ewitab,3),
                                         &ewtabF,&ewtabFn);
            felec            = _mm_add_ps(_mm_mul_ps( _mm_sub_ps(one,eweps),ewtabF),_mm_mul_ps(eweps,ewtabFn));
            felec            = _mm_mul_ps(_mm_mul_ps(qq20,rinv20),_mm_sub_ps(rinvsq20,felec));

            fscal            = felec;

            fscal            = _mm_and_ps(fscal,mask);

            /* Calculate temporary vectorial force */
            tx               = _mm_mul_ps(fscal,dx20);
            ty               = _mm_mul_ps(fscal,dy20);
            tz               = _mm_mul_ps(fscal,dz20);

            /* Update vectorial force */
            fix2             = _mm_add_ps(fix2,tx);
            fiy2             = _mm_add_ps(fiy2,ty);
            fiz2             = _mm_add_ps(fiz2,tz);

            if(jidx<j_index_end-2)
            {
                gmx_mm_decrement_1rvec_3ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                       f+j_coord_offsetC,
                                                       tx,ty,tz);
            }
            else if(jidx<j_index_end-1)
            {
                gmx_mm_decrement_1rvec_2ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                       tx,ty,tz);
            }
            else
            {
                gmx_mm_decrement_1rvec_1ptr_swizzle_ps(f+j_coord_offsetA,
                                                       tx,ty,tz);
            }

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            r30              = _mm_mul_ps(rsq30,rinv30);

            qq30             = _mm_mul_ps(iq3,jq0);

            /* EWALD ELECTROSTATICS */

            /* Calculate Ewald table index by multiplying r with scale and truncate to integer */
            ewrt             = _mm_mul_ps(r30,ewtabscale);
            ewitab           = _mm_cvttps_epi32(ewrt);
            eweps            = _mm_sub_ps(ewrt,_mm_cvtepi32_ps(ewitab));
            gmx_mm_load_4pair_swizzle_ps(ewtab+gmx_mm_extract_epi32(ewitab,0),ewtab+gmx_mm_extract_epi32(ewitab,1),
                                         ewtab+gmx_mm_extract_epi32(ewitab,2),ewtab+gmx_mm_extract_epi32(ewitab,3),
                                         &ewtabF,&ewtabFn);
            felec            = _mm_add_ps(_mm_mul_ps( _mm_sub_ps(one,eweps),ewtabF),_mm_mul_ps(eweps,ewtabFn));
            felec            = _mm_mul_ps(_mm_mul_ps(qq30,rinv30),_mm_sub_ps(rinvsq30,felec));

            fscal            = felec;

            fscal            = _mm_and_ps(fscal,mask);

            /* Calculate temporary vectorial force */
            tx               = _mm_mul_ps(fscal,dx30);
            ty               = _mm_mul_ps(fscal,dy30);
            tz               = _mm_mul_ps(fscal,dz30);

            /* Update vectorial force */
            fix3             = _mm_add_ps(fix3,tx);
            fiy3             = _mm_add_ps(fiy3,ty);
            fiz3             = _mm_add_ps(fiz3,tz);

            if(jidx<j_index_end-2)
            {
                gmx_mm_decrement_1rvec_3ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                       f+j_coord_offsetC,
                                                       tx,ty,tz);
            }
            else if(jidx<j_index_end-1)
            {
                gmx_mm_decrement_1rvec_2ptr_swizzle_ps(f+j_coord_offsetA,f+j_coord_offsetB,
                                                       tx,ty,tz);
            }
            else
            {
                gmx_mm_decrement_1rvec_1ptr_swizzle_ps(f+j_coord_offsetA,
                                                       tx,ty,tz);
            }

        }
        /* End of innermost loop */

        gmx_mm_update_iforce_3atom_swizzle_ps(fix1,fiy1,fiz1,fix2,fiy2,fiz2,fix3,fiy3,fiz3,
                                              f+i_coord_offset+DIM,fshift+i_shift_offset);

        /* Increment number of inner iterations */
        inneriter                  += j_index_end - j_index_start;

        /* Outer loop uses 27 flops */
    }

    /* Increment number of outer iterations */
    outeriter        += nri;

    /* Update outer/inner flops */

    inc_nrnb(nrnb,eNR_NBKERNEL_ELEC_W4_F,outeriter*27 + inneriter*108);
}
