#!/bin/sh -x
if [ -n "${CMakeVersion}" ] ; then
   export PATH=$HOME/tools/cmake-${CMakeVersion}/bin:$PATH
fi
export CMAKE_LIBRARY_PATH=/usr/lib/atlas-base
if [ $GMX_MPI = on ]; then
    export OMPI_CC=gcc-${CompilerVersion} 
    export OMPI_CXX=g++-${CompilerVersion}
    export OMPI_FC=gfortran-${CompilerVersion}  
    export CC=mpicc
    export CXX=mpic++
    export FC=mpif90
else
    export CC=gcc-${CompilerVersion} 
    export CXX=g++-${CompilerVersion} 
    export FC=gfortran-${CompilerVersion} 
fi
cmake -D GMX_DOUBLE=${GMX_DOUBLE} -D GMX_MPI=${GMX_MPI} -D GMX_OPENMP=${GMX_OPENMP} \
    -DGMX_EXTERNAL_BLAS=${GMX_EXTERNAL} -DGMX_EXTERNAL_LAPACK=${GMX_EXTERNAL} \
    -DGMX_DEFAULT_SUFFIX=off -DCMAKE_BUILD_TYPE=Debug . &&
make &&
ctest -D ExperimentalTest -V
