#!/bin/bash
#
# This file is part of the GROMACS molecular simulation package.
#
# Copyright (c) 2013, by the GROMACS development team, led by
# David van der Spoel, Berk Hess, Erik Lindahl, and including many
# others, as listed in the AUTHORS file in the top-level source
# directory and at http://www.gromacs.org.
#
# GROMACS is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2.1
# of the License, or (at your option) any later version.
#
# GROMACS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with GROMACS; if not, see
# http://www.gnu.org/licenses, or write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA.
#
# If you want to redistribute modifications to GROMACS, please
# consider that scientific software is very special. Version
# control is crucial - bugs must be traceable. We will be happy to
# consider code for inclusion in the official distribution, but
# derived work must not be called official GROMACS. Details are found
# in the README & COPYING files - if they are missing, get the
# official version at http://www.gromacs.org.
#
# To help us fund GROMACS development, we humbly ask that you cite
# the research papers on the package. Check out http://www.gromacs.org.

# This script is intended as a pre-commit hook that optionally runs all
# changes through uncrustify.  By default, it does nothing.  To enable the
# script after copying it to .git/hooks/pre-commit, you need to set
#   git config hooks.uncrustifymode check
#   git config hooks.uncrustifypath /path/to/uncrustify
# With this configuration, all source files modified in the commit are run
# through uncrustify (see admin/uncrustify.sh for how this set of files is
# determined).  If any file is changed by uncrustify, the names of those files
# are reported and the commit is prevented.
# To disable the hook, you can set
#   git config hooks.uncrustifymode off
#
# The actual work is done by the admin/uncrustify.sh script, which gets
# run with the 'check-index' action.
# See the comments in that script for more information.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

uncrustify_mode=`git config hooks.uncrustifymode`

if [ -f admin/uncrustify.sh ] && \
   [ ! -z "$uncrustify_mode" ] && [ "$uncrustify_mode" != "off" ]
then
    uncrustify_path=`git config hooks.uncrustifypath`
    if [ -z "$uncrustify_path" ]
    then
        echo "Please set the path to uncrustify using 'git config hooks.uncrustifypath'."
        echo "Note that you need a custom version of uncrustify."
        exit 1
    fi
    export UNCRUSTIFY="$uncrustify_path"
    case "$uncrustify_mode" in
        check)
            admin/uncrustify.sh check-index --rev=$against
            stat=$?
            if [ $stat -eq 1 ] ; then
                exit 1
            elif [ $stat -ne 0 ] ; then
                echo "Source code formatting check failed"
                exit 1
            fi
            ;;
        *)
            echo "Unknown uncrustify mode: $uncrustify_mode"
            exit 1
            ;;
    esac
fi
