#!/bin/csh -f

if ( $#argv < 1 ) then
  echo "Error: provide the binary directory as first argument."
  exit
endif

set GMXBINDIR = $1

set out = complete
set dir = $cwd

echo Generating tcsh completions

if ( -f $out) then
  mv complete \#complete\#
endif

touch $out

cd $GMXBINDIR
set PROGRAMS = [a-z]*
cd $dir

echo "if ( "'$shell'" == /bin/tcsh ) then" >> $out

foreach program ( $PROGRAMS )
  if ( ( $program != "average" ) && ( $program != "luck" ) && ( $program != mdrun ) && ( $program != nmrun ) && ( $program != xmdrun )) then
    $GMXBINDIR/$program -man completion >& /dev/null
    cat $program.completion >> $out
    \rm $program.completion
  endif
end

echo "endif" >> $out

#last line
