#!/bin/bash

if [[ $# != 1 ]]; then
  echo "Error: usage is 'mkman GMXBIN' where GMXBIN is the .../bin directory where GROMACS binaries are installed"
  exit
fi

GMXBIN=$1

PROGMAN=progman
MANDIR=${PROGMAN}
INDEX=${MANDIR}/all.tex
OPTIONS_PROGRAM_NAME=g_options

PROGRAMS=$(cd ${GMXBIN}; ls)
echo "Generating manpages from GROMACS binaries in ${GMXBIN}"

\rm -rf ${MANDIR}
mkdir ${MANDIR}

touch ${INDEX}
for PROG in $PROGRAMS; do
    # strip off .exe suffixes (good for Cygwin)
    program=${PROG%.exe}

    if [ -x "${GMXBIN}/${PROG}" -a \
	"$PROG" != "GMXRC" -a \
        "$PROG" != "GMXRC.bash" -a \
        "$PROG" != "GMXRC.csh" -a \
        "$PROG" != "GMXRC.zsh" -a \
        "$program" != "average" -a \
        "$program" != "g_luck" -a \
        "$program" != "${OPTIONS_PROGRAM_NAME}" -a \
	"$program" != "my_dssp" -a \
        "$PROG" != "completion.csh" -a \
        "$PROG" != "completion.zsh" -a \
        "$PROG" != "completion.bash" -a \
        "$PROG" != "demux.pl" -a \
        "$PROG" != "xplor2gmx.pl" ]; then
	echo -n "$program "
	${GMXBIN}/$PROG -quiet -man tex >& /dev/null
	if [ -f ${program}.tex ]; then
	    grep -v "Use dialog box GUI to edit command line options" ${program}.tex > mkman_temp.tex
	    grep -v "non blocking priority" mkman_temp.tex > ${program}.tex
	    \rm mkman_temp.tex
	    mv ${program}.tex ${MANDIR}/
	    echo "\input{${MANDIR}/${program}}" >> $INDEX
	else
	    echo
	    echo "${program}.tex was not created"
	fi
    fi
done

INSTALLED_OPTIONS_PROGRAM_NAME=$(find "$GMXBIN" -name "*${OPTIONS_PROGRAM_NAME}*")
if [[ ! ${INSTALLED_OPTIONS_PROGRAM_NAME} ]]; then
    echo "Error: Can't find the executable '${OPTIONS_PROGRAM_NAME}' in GMXBIN directory $GMXBIN"
    echo "I need it to create a LaTeX file."
    exit 1
else
    ${INSTALLED_OPTIONS_PROGRAM_NAME} -hidden -man tex 2> /dev/null
fi

# The text emitted by the above -man tex line goes in the very first
# section of the manual appendix compiled from tool output. That
# section should not be called "g_options_d" (or any such), because it
# documents the standard and hidden options for all tools.
sed -i -e "s/\\\\normindex{${OPTIONS_PROGRAM_NAME}}/Standard options for GROMACS tools\\\\index{options!standard}/g" ${OPTIONS_PROGRAM_NAME}.tex

mv ${OPTIONS_PROGRAM_NAME}.tex ${MANDIR}/

cat > ${PROGMAN}.tex << EOD
\chapter{Manual Pages}
\label{app:progman}

{\small
%${OPTIONS_PROGRAM_NAME}.tex is created by the GROMACS installed binary ${OPTIONS_PROGRAM_NAME}
\input{${MANDIR}/${OPTIONS_PROGRAM_NAME}.tex}
}
{\small
\input{${MANDIR}/all}
}
EOD
echo ""

#last line
