#!/bin/csh -f

if ($#argv >= 1) then
  set FILES = $1
else
  set FILES = *.html
endif

echo Will process $FILES

foreach file ( $FILES )
  if ($file != "include_top.html") then
    echo Processing $file
    
    grep -v "<\!--I-->" $file >! tmp1
    
    awk '{ printf "%s\n", $0 ;if (($1=="<body>")||($1=="<BODY>")||($1=="<body")||($1=="<BODY")) exit; }' tmp1 >! tmp 
    
    awk '{ printf "<\!--I-->%s\n", $0 }' include_top.html >> tmp
    
    awk '{ if (($1=="</body>")||($1=="</BODY>")) exit; if (doit==1) printf "%s\n", $0; if (($1=="<body>")||($1=="<BODY>")||($1=="<body")||($1=="<BODY")) doit=1; }' tmp1 >> tmp
    
    awk '{ printf "<\!--I-->%s\n", $0 }' include_bot.html >> tmp
    
    awk '{ if (($1=="</body>")||($1=="</BODY>")) doit=1; if (doit==1) printf "%s\n", $0; }' tmp1 >> tmp
    
    \rm tmp1
    if ( -f \#$file\# ) \rm \#$file\#
    mv $file \#$file\#
    mv tmp $file
  endif
end

#last line


