/*
 * This file is part of the GROMACS molecular simulation package.
 *
 * Copyright (c) 2012, by the GROMACS development team, led by
 * David van der Spoel, Berk Hess, Erik Lindahl, and including many
 * others, as listed in the AUTHORS file in the top-level source
 * directory and at http://www.gromacs.org.
 *
 * GROMACS is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * GROMACS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with GROMACS; if not, see
 * http://www.gnu.org/licenses, or write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA.
 *
 * If you want to redistribute modifications to GROMACS, please
 * consider that scientific software is very special. Version
 * control is crucial - bugs must be traceable. We will be happy to
 * consider code for inclusion in the official distribution, but
 * derived work must not be called official GROMACS. Details are found
 * in the README & COPYING files - if they are missing, get the
 * official version at http://www.gromacs.org.
 *
 * To help us fund GROMACS development, we humbly ask that you cite
 * the research papers on the package. Check out http://www.gromacs.org.
 */
/*
 * Note: this file was generated by the GROMACS ibm_qpx kernel generator.
 */
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <math.h>

#include "../nb_kernel.h"
#include "types/simple.h"
#include "vec.h"
#include "nrnb.h"

#ifdef GMX_DOUBLE
#  include "gmx_math_ibm_qpx_double.h"
#else
#  include "gmx_math_ibm_qpx_single.h"
#endif

#include "kernelutil_ibm_qpx.h"

/*
 * Gromacs nonbonded kernel:   nb_kernel_ElecNone_VdwLJ_GeomP1P1_VF_ibm_qpx
 * Electrostatics interaction: None
 * VdW interaction:            LennardJones
 * Geometry:                   Particle-Particle
 * Calculate force/pot:        PotentialAndForce
 */
void
nb_kernel_ElecNone_VdwLJ_GeomP1P1_VF_ibm_qpx
                    (t_nblist * gmx_restrict                nlist,
                     rvec * gmx_restrict                    xx,
                     rvec * gmx_restrict                    ff,
                     t_forcerec * gmx_restrict              fr,
                     t_mdatoms * gmx_restrict               mdatoms,
                     nb_kernel_data_t * gmx_restrict        kernel_data,
                     t_nrnb * gmx_restrict                  nrnb)
{
    /* Suffixes 0,1,2,3 refer to particle indices for waters in the inner or outer loop, or
     * just 0 for non-waters.
     * Suffixes A,B,C,D refer to j loop unrolling done with AVX_128, e.g. for the four different
     * jnr indices corresponding to data put in the four positions in the SIMD register.
     */
    int              i_shift_offset,i_coord_offset,outeriter,inneriter;
    int              j_index_start,j_index_end,jidx,nri,inr,ggid,iidx;
    int              jnrA,jnrB,jnrC,jnrD;
    int              jnrlistA,jnrlistB,jnrlistC,jnrlistD;
    int              j_coord_offsetA,j_coord_offsetB,j_coord_offsetC,j_coord_offsetD;
    int              *iinr,*jindex,*jjnr,*shiftidx,*gid;
    real             rcutoff_scalar;
    real             *shiftvec,*fshift,*x,*f;
    real             *fjptrA,*fjptrB,*fjptrC,*fjptrD;
    real             scratch[4*DIM];
    vector4double    fscal,rcutoff,rcutoff2,jidxall;
    int              vdwioffset0;
    vector4double    ix0,iy0,iz0,fix0,fiy0,fiz0,iq0,isai0;
    int              vdwjidx0A,vdwjidx0B,vdwjidx0C,vdwjidx0D;
    vector4double    jx0,jy0,jz0,fjx0,fjy0,fjz0,jq0,isaj0;
    vector4double    dx00,dy00,dz00,rsq00,rinv00,rinvsq00,r00,qq00,c6_00,c12_00;
    int              nvdwtype;
    vector4double    rinvsix,rvdw,vvdw,vvdw6,vvdw12,fvdw,fvdw6,fvdw12,vvdwsum,sh_vdw_invrcut6;
    int              *vdwtype;
    real             *vdwparam;
    vector4double    one_sixth   = vec_splats(1.0/6.0);
    vector4double    one_twelfth = vec_splats(1.0/12.0);
    vector4double    dummy_mask,cutoff_mask;
    vector4double    zero    = vec_splats(0.0);
    vector4double    one     = vec_splats(1.0);
    vector4double    two     = vec_splats(2.0);
    x                = xx[0];
    f                = ff[0];

    nri              = nlist->nri;
    iinr             = nlist->iinr;
    jindex           = nlist->jindex;
    jjnr             = nlist->jjnr;
    shiftidx         = nlist->shift;
    gid              = nlist->gid;
    shiftvec         = fr->shift_vec[0];
    fshift           = fr->fshift[0];
    nvdwtype         = fr->ntype;
    vdwparam         = fr->nbfp;
    vdwtype          = mdatoms->typeA;

    /* Avoid stupid compiler warnings */
    jnrA = jnrB = jnrC = jnrD = 0;
    j_coord_offsetA = 0;
    j_coord_offsetB = 0;
    j_coord_offsetC = 0;
    j_coord_offsetD = 0;

    outeriter        = 0;
    inneriter        = 0;

    for(iidx=0;iidx<4*DIM;iidx++)
    {
        scratch[iidx] = 0.0;
    }

    /* Start outer loop over neighborlists */
    for(iidx=0; iidx<nri; iidx++)
    {
        /* Load shift vector for this list */
        i_shift_offset   = DIM*shiftidx[iidx];

        /* Load limits for loop over neighbors */
        j_index_start    = jindex[iidx];
        j_index_end      = jindex[iidx+1];

        /* Get outer coordinate index */
        inr              = iinr[iidx];
        i_coord_offset   = DIM*inr;

        /* Load i particle coords and add shift vector */
        gmx_ibm_qpx_load_shift_and_1rvec_broadcast(shiftvec+i_shift_offset,x+i_coord_offset,&ix0,&iy0,&iz0);

        fix0             = zero;
        fiy0             = zero;
        fiz0             = zero;

        /* Load parameters for i particles */
        vdwioffset0      = 2*nvdwtype*vdwtype[inr+0];

        /* Reset potential sums */
        vvdwsum          = zero;

        /* Start inner kernel loop */
        for(jidx=j_index_start; jidx<j_index_end && jjnr[jidx+3]>=0; jidx+=4)
        {

            /* Get j neighbor index, and coordinate index */
            jnrA             = jjnr[jidx];
            jnrB             = jjnr[jidx+1];
            jnrC             = jjnr[jidx+2];
            jnrD             = jjnr[jidx+3];
            j_coord_offsetA  = DIM*jnrA;
            j_coord_offsetB  = DIM*jnrB;
            j_coord_offsetC  = DIM*jnrC;
            j_coord_offsetD  = DIM*jnrD;

            /* load j atom coordinates */
            gmx_ibm_qpx_load_1rvec_4ptr_swizzle(x+j_coord_offsetA,x+j_coord_offsetB,
                                                x+j_coord_offsetC,x+j_coord_offsetD,
                                                &jx0,&jy0,&jz0);

            /* Calculate displacement vector */
            dx00             = vec_sub(ix0,jx0);
            dy00             = vec_sub(iy0,jy0);
            dz00             = vec_sub(iz0,jz0);

            /* Calculate squared distance and things based on it */
            rsq00            = gmx_ibm_qpx_calc_rsq(dx00,dy00,dz00);

            rinvsq00         = gmx_ibm_qpx_inv(rsq00);

            /* Load parameters for j particles */
            vdwjidx0A        = 2*vdwtype[jnrA+0];
            vdwjidx0B        = 2*vdwtype[jnrB+0];
            vdwjidx0C        = 2*vdwtype[jnrC+0];
            vdwjidx0D        = 2*vdwtype[jnrD+0];

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            /* Compute parameters for interactions between i and j atoms */
            gmx_ibm_qpx_load_4pair_swizzle(vdwparam+vdwioffset0+vdwjidx0A,
                                           vdwparam+vdwioffset0+vdwjidx0B,
                                           vdwparam+vdwioffset0+vdwjidx0C,
                                           vdwparam+vdwioffset0+vdwjidx0D,
                                           &c6_00,&c12_00);

            /* LENNARD-JONES DISPERSION/REPULSION */

            rinvsix          = vec_mul(vec_mul(rinvsq00,rinvsq00),rinvsq00);
            vvdw6            = vec_mul(c6_00,rinvsix);
            vvdw12           = vec_mul(c12_00,vec_mul(rinvsix,rinvsix));
            vvdw             = vec_msub(vvdw12,one_twelfth,vec_mul(vvdw6,one_sixth));
            fvdw             = vec_mul(vec_sub(vvdw12,vvdw6),rinvsq00);

            /* Update potential sum for this i atom from the interaction with this j atom. */
            vvdwsum          = vec_add(vvdwsum,vvdw);

            fscal            = fvdw;

             /* Update vectorial force */
            fix0             = vec_madd(dx00,fscal,fix0);
            fiy0             = vec_madd(dy00,fscal,fiy0);
            fiz0             = vec_madd(dz00,fscal,fiz0);

            fjptrA             = f+j_coord_offsetA;
            fjptrB             = f+j_coord_offsetB;
            fjptrC             = f+j_coord_offsetC;
            fjptrD             = f+j_coord_offsetD;
            gmx_ibm_qpx_decrement_1rvec_4ptr_swizzle(fjptrA,fjptrB,fjptrC,fjptrD,
                                                     vec_mul(dx00,fscal),
                                                     vec_mul(dy00,fscal),
                                                     vec_mul(dz00,fscal));

            /* Inner loop uses 35 flops */
        }

        if(jidx<j_index_end)
        {

            /* Get j neighbor index, and coordinate index */
            jnrlistA         = jjnr[jidx];
            jnrlistB         = jjnr[jidx+1];
            jnrlistC         = jjnr[jidx+2];
            jnrlistD         = jjnr[jidx+3];
            /* Sign of each element will be negative for non-real atoms. */
            dummy_mask = vec_ldia(jidx,jjnr);
            jnrA       = (jnrlistA>=0) ? jnrlistA : 0;
            jnrB       = (jnrlistB>=0) ? jnrlistB : 0;
            jnrC       = (jnrlistC>=0) ? jnrlistC : 0;
            jnrD       = (jnrlistD>=0) ? jnrlistD : 0;
            j_coord_offsetA  = DIM*jnrA;
            j_coord_offsetB  = DIM*jnrB;
            j_coord_offsetC  = DIM*jnrC;
            j_coord_offsetD  = DIM*jnrD;

            /* load j atom coordinates */
            gmx_ibm_qpx_load_1rvec_4ptr_swizzle(x+j_coord_offsetA,x+j_coord_offsetB,
                                                x+j_coord_offsetC,x+j_coord_offsetD,
                                                &jx0,&jy0,&jz0);

            /* Calculate displacement vector */
            dx00             = vec_sub(ix0,jx0);
            dy00             = vec_sub(iy0,jy0);
            dz00             = vec_sub(iz0,jz0);

            /* Calculate squared distance and things based on it */
            rsq00            = gmx_ibm_qpx_calc_rsq(dx00,dy00,dz00);

            rinvsq00         = gmx_ibm_qpx_inv(rsq00);

            /* Load parameters for j particles */
            vdwjidx0A        = 2*vdwtype[jnrA+0];
            vdwjidx0B        = 2*vdwtype[jnrB+0];
            vdwjidx0C        = 2*vdwtype[jnrC+0];
            vdwjidx0D        = 2*vdwtype[jnrD+0];

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            /* Compute parameters for interactions between i and j atoms */
            gmx_ibm_qpx_load_4pair_swizzle(vdwparam+vdwioffset0+vdwjidx0A,
                                           vdwparam+vdwioffset0+vdwjidx0B,
                                           vdwparam+vdwioffset0+vdwjidx0C,
                                           vdwparam+vdwioffset0+vdwjidx0D,
                                           &c6_00,&c12_00);

            /* LENNARD-JONES DISPERSION/REPULSION */

            rinvsix          = vec_mul(vec_mul(rinvsq00,rinvsq00),rinvsq00);
            vvdw6            = vec_mul(c6_00,rinvsix);
            vvdw12           = vec_mul(c12_00,vec_mul(rinvsix,rinvsix));
            vvdw             = vec_msub(vvdw12,one_twelfth,vec_mul(vvdw6,one_sixth));
            fvdw             = vec_mul(vec_sub(vvdw12,vvdw6),rinvsq00);

            /* Update potential sum for this i atom from the interaction with this j atom. */
            vvdw             = vec_sel(zero,vvdw,dummy_mask);
            vvdwsum          = vec_add(vvdwsum,vvdw);

            fscal            = fvdw;

            fscal            = vec_sel(zero,fscal,dummy_mask);

             /* Update vectorial force */
            fix0             = vec_madd(dx00,fscal,fix0);
            fiy0             = vec_madd(dy00,fscal,fiy0);
            fiz0             = vec_madd(dz00,fscal,fiz0);

            fjptrA             = (jnrlistA>=0) ? f+j_coord_offsetA : scratch;
            fjptrB             = (jnrlistB>=0) ? f+j_coord_offsetB : scratch;
            fjptrC             = (jnrlistC>=0) ? f+j_coord_offsetC : scratch;
            fjptrD             = (jnrlistD>=0) ? f+j_coord_offsetD : scratch;
            gmx_ibm_qpx_decrement_1rvec_4ptr_swizzle(fjptrA,fjptrB,fjptrC,fjptrD,
                                                     vec_mul(dx00,fscal),
                                                     vec_mul(dy00,fscal),
                                                     vec_mul(dz00,fscal));

            /* Inner loop uses 35 flops */
        }

        /* End of innermost loop */

        gmx_ibm_qpx_update_iforce_1atom_swizzle(fix0,fiy0,fiz0,
                                                f+i_coord_offset,fshift+i_shift_offset);

        ggid                        = gid[iidx];
        /* Update potential energies */
        gmx_ibm_qpx_update_1pot(vvdwsum,kernel_data->energygrp_vdw+ggid);

        /* Increment number of inner iterations */
        inneriter                  += j_index_end - j_index_start;

        /* Outer loop uses 7 flops */
    }

    /* Increment number of outer iterations */
    outeriter        += nri;

    /* Update outer/inner flops */

    inc_nrnb(nrnb,eNR_NBKERNEL_VDW_VF,outeriter*7 + inneriter*35);
}
/*
 * Gromacs nonbonded kernel:   nb_kernel_ElecNone_VdwLJ_GeomP1P1_F_ibm_qpx
 * Electrostatics interaction: None
 * VdW interaction:            LennardJones
 * Geometry:                   Particle-Particle
 * Calculate force/pot:        Force
 */
void
nb_kernel_ElecNone_VdwLJ_GeomP1P1_F_ibm_qpx
                    (t_nblist * gmx_restrict                nlist,
                     rvec * gmx_restrict                    xx,
                     rvec * gmx_restrict                    ff,
                     t_forcerec * gmx_restrict              fr,
                     t_mdatoms * gmx_restrict               mdatoms,
                     nb_kernel_data_t * gmx_restrict        kernel_data,
                     t_nrnb * gmx_restrict                  nrnb)
{
    /* Suffixes 0,1,2,3 refer to particle indices for waters in the inner or outer loop, or
     * just 0 for non-waters.
     * Suffixes A,B,C,D refer to j loop unrolling done with AVX_128, e.g. for the four different
     * jnr indices corresponding to data put in the four positions in the SIMD register.
     */
    int              i_shift_offset,i_coord_offset,outeriter,inneriter;
    int              j_index_start,j_index_end,jidx,nri,inr,ggid,iidx;
    int              jnrA,jnrB,jnrC,jnrD;
    int              jnrlistA,jnrlistB,jnrlistC,jnrlistD;
    int              j_coord_offsetA,j_coord_offsetB,j_coord_offsetC,j_coord_offsetD;
    int              *iinr,*jindex,*jjnr,*shiftidx,*gid;
    real             rcutoff_scalar;
    real             *shiftvec,*fshift,*x,*f;
    real             *fjptrA,*fjptrB,*fjptrC,*fjptrD;
    real             scratch[4*DIM];
    vector4double    fscal,rcutoff,rcutoff2,jidxall;
    int              vdwioffset0;
    vector4double    ix0,iy0,iz0,fix0,fiy0,fiz0,iq0,isai0;
    int              vdwjidx0A,vdwjidx0B,vdwjidx0C,vdwjidx0D;
    vector4double    jx0,jy0,jz0,fjx0,fjy0,fjz0,jq0,isaj0;
    vector4double    dx00,dy00,dz00,rsq00,rinv00,rinvsq00,r00,qq00,c6_00,c12_00;
    int              nvdwtype;
    vector4double    rinvsix,rvdw,vvdw,vvdw6,vvdw12,fvdw,fvdw6,fvdw12,vvdwsum,sh_vdw_invrcut6;
    int              *vdwtype;
    real             *vdwparam;
    vector4double    one_sixth   = vec_splats(1.0/6.0);
    vector4double    one_twelfth = vec_splats(1.0/12.0);
    vector4double    dummy_mask,cutoff_mask;
    vector4double    zero    = vec_splats(0.0);
    vector4double    one     = vec_splats(1.0);
    vector4double    two     = vec_splats(2.0);
    x                = xx[0];
    f                = ff[0];

    nri              = nlist->nri;
    iinr             = nlist->iinr;
    jindex           = nlist->jindex;
    jjnr             = nlist->jjnr;
    shiftidx         = nlist->shift;
    gid              = nlist->gid;
    shiftvec         = fr->shift_vec[0];
    fshift           = fr->fshift[0];
    nvdwtype         = fr->ntype;
    vdwparam         = fr->nbfp;
    vdwtype          = mdatoms->typeA;

    /* Avoid stupid compiler warnings */
    jnrA = jnrB = jnrC = jnrD = 0;
    j_coord_offsetA = 0;
    j_coord_offsetB = 0;
    j_coord_offsetC = 0;
    j_coord_offsetD = 0;

    outeriter        = 0;
    inneriter        = 0;

    for(iidx=0;iidx<4*DIM;iidx++)
    {
        scratch[iidx] = 0.0;
    }

    /* Start outer loop over neighborlists */
    for(iidx=0; iidx<nri; iidx++)
    {
        /* Load shift vector for this list */
        i_shift_offset   = DIM*shiftidx[iidx];

        /* Load limits for loop over neighbors */
        j_index_start    = jindex[iidx];
        j_index_end      = jindex[iidx+1];

        /* Get outer coordinate index */
        inr              = iinr[iidx];
        i_coord_offset   = DIM*inr;

        /* Load i particle coords and add shift vector */
        gmx_ibm_qpx_load_shift_and_1rvec_broadcast(shiftvec+i_shift_offset,x+i_coord_offset,&ix0,&iy0,&iz0);

        fix0             = zero;
        fiy0             = zero;
        fiz0             = zero;

        /* Load parameters for i particles */
        vdwioffset0      = 2*nvdwtype*vdwtype[inr+0];

        /* Start inner kernel loop */
        for(jidx=j_index_start; jidx<j_index_end && jjnr[jidx+3]>=0; jidx+=4)
        {

            /* Get j neighbor index, and coordinate index */
            jnrA             = jjnr[jidx];
            jnrB             = jjnr[jidx+1];
            jnrC             = jjnr[jidx+2];
            jnrD             = jjnr[jidx+3];
            j_coord_offsetA  = DIM*jnrA;
            j_coord_offsetB  = DIM*jnrB;
            j_coord_offsetC  = DIM*jnrC;
            j_coord_offsetD  = DIM*jnrD;

            /* load j atom coordinates */
            gmx_ibm_qpx_load_1rvec_4ptr_swizzle(x+j_coord_offsetA,x+j_coord_offsetB,
                                                x+j_coord_offsetC,x+j_coord_offsetD,
                                                &jx0,&jy0,&jz0);

            /* Calculate displacement vector */
            dx00             = vec_sub(ix0,jx0);
            dy00             = vec_sub(iy0,jy0);
            dz00             = vec_sub(iz0,jz0);

            /* Calculate squared distance and things based on it */
            rsq00            = gmx_ibm_qpx_calc_rsq(dx00,dy00,dz00);

            rinvsq00         = gmx_ibm_qpx_inv(rsq00);

            /* Load parameters for j particles */
            vdwjidx0A        = 2*vdwtype[jnrA+0];
            vdwjidx0B        = 2*vdwtype[jnrB+0];
            vdwjidx0C        = 2*vdwtype[jnrC+0];
            vdwjidx0D        = 2*vdwtype[jnrD+0];

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            /* Compute parameters for interactions between i and j atoms */
            gmx_ibm_qpx_load_4pair_swizzle(vdwparam+vdwioffset0+vdwjidx0A,
                                           vdwparam+vdwioffset0+vdwjidx0B,
                                           vdwparam+vdwioffset0+vdwjidx0C,
                                           vdwparam+vdwioffset0+vdwjidx0D,
                                           &c6_00,&c12_00);

            /* LENNARD-JONES DISPERSION/REPULSION */

            rinvsix          = vec_mul(vec_mul(rinvsq00,rinvsq00),rinvsq00);
            fvdw             = vec_mul(vec_msub(c12_00,rinvsix,c6_00),vec_mul(rinvsix,rinvsq00));

            fscal            = fvdw;

             /* Update vectorial force */
            fix0             = vec_madd(dx00,fscal,fix0);
            fiy0             = vec_madd(dy00,fscal,fiy0);
            fiz0             = vec_madd(dz00,fscal,fiz0);

            fjptrA             = f+j_coord_offsetA;
            fjptrB             = f+j_coord_offsetB;
            fjptrC             = f+j_coord_offsetC;
            fjptrD             = f+j_coord_offsetD;
            gmx_ibm_qpx_decrement_1rvec_4ptr_swizzle(fjptrA,fjptrB,fjptrC,fjptrD,
                                                     vec_mul(dx00,fscal),
                                                     vec_mul(dy00,fscal),
                                                     vec_mul(dz00,fscal));

            /* Inner loop uses 30 flops */
        }

        if(jidx<j_index_end)
        {

            /* Get j neighbor index, and coordinate index */
            jnrlistA         = jjnr[jidx];
            jnrlistB         = jjnr[jidx+1];
            jnrlistC         = jjnr[jidx+2];
            jnrlistD         = jjnr[jidx+3];
            /* Sign of each element will be negative for non-real atoms. */
            dummy_mask = vec_ldia(jidx,jjnr);
            jnrA       = (jnrlistA>=0) ? jnrlistA : 0;
            jnrB       = (jnrlistB>=0) ? jnrlistB : 0;
            jnrC       = (jnrlistC>=0) ? jnrlistC : 0;
            jnrD       = (jnrlistD>=0) ? jnrlistD : 0;
            j_coord_offsetA  = DIM*jnrA;
            j_coord_offsetB  = DIM*jnrB;
            j_coord_offsetC  = DIM*jnrC;
            j_coord_offsetD  = DIM*jnrD;

            /* load j atom coordinates */
            gmx_ibm_qpx_load_1rvec_4ptr_swizzle(x+j_coord_offsetA,x+j_coord_offsetB,
                                                x+j_coord_offsetC,x+j_coord_offsetD,
                                                &jx0,&jy0,&jz0);

            /* Calculate displacement vector */
            dx00             = vec_sub(ix0,jx0);
            dy00             = vec_sub(iy0,jy0);
            dz00             = vec_sub(iz0,jz0);

            /* Calculate squared distance and things based on it */
            rsq00            = gmx_ibm_qpx_calc_rsq(dx00,dy00,dz00);

            rinvsq00         = gmx_ibm_qpx_inv(rsq00);

            /* Load parameters for j particles */
            vdwjidx0A        = 2*vdwtype[jnrA+0];
            vdwjidx0B        = 2*vdwtype[jnrB+0];
            vdwjidx0C        = 2*vdwtype[jnrC+0];
            vdwjidx0D        = 2*vdwtype[jnrD+0];

            /**************************
             * CALCULATE INTERACTIONS *
             **************************/

            /* Compute parameters for interactions between i and j atoms */
            gmx_ibm_qpx_load_4pair_swizzle(vdwparam+vdwioffset0+vdwjidx0A,
                                           vdwparam+vdwioffset0+vdwjidx0B,
                                           vdwparam+vdwioffset0+vdwjidx0C,
                                           vdwparam+vdwioffset0+vdwjidx0D,
                                           &c6_00,&c12_00);

            /* LENNARD-JONES DISPERSION/REPULSION */

            rinvsix          = vec_mul(vec_mul(rinvsq00,rinvsq00),rinvsq00);
            fvdw             = vec_mul(vec_msub(c12_00,rinvsix,c6_00),vec_mul(rinvsix,rinvsq00));

            fscal            = fvdw;

            fscal            = vec_sel(zero,fscal,dummy_mask);

             /* Update vectorial force */
            fix0             = vec_madd(dx00,fscal,fix0);
            fiy0             = vec_madd(dy00,fscal,fiy0);
            fiz0             = vec_madd(dz00,fscal,fiz0);

            fjptrA             = (jnrlistA>=0) ? f+j_coord_offsetA : scratch;
            fjptrB             = (jnrlistB>=0) ? f+j_coord_offsetB : scratch;
            fjptrC             = (jnrlistC>=0) ? f+j_coord_offsetC : scratch;
            fjptrD             = (jnrlistD>=0) ? f+j_coord_offsetD : scratch;
            gmx_ibm_qpx_decrement_1rvec_4ptr_swizzle(fjptrA,fjptrB,fjptrC,fjptrD,
                                                     vec_mul(dx00,fscal),
                                                     vec_mul(dy00,fscal),
                                                     vec_mul(dz00,fscal));

            /* Inner loop uses 30 flops */
        }

        /* End of innermost loop */

        gmx_ibm_qpx_update_iforce_1atom_swizzle(fix0,fiy0,fiz0,
                                                f+i_coord_offset,fshift+i_shift_offset);

        /* Increment number of inner iterations */
        inneriter                  += j_index_end - j_index_start;

        /* Outer loop uses 6 flops */
    }

    /* Increment number of outer iterations */
    outeriter        += nri;

    /* Update outer/inner flops */

    inc_nrnb(nrnb,eNR_NBKERNEL_VDW_F,outeriter*6 + inneriter*30);
}
