set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_OSX_ARCHITECTURES arm64)
set(CMAKE_C_COMPILER /usr/bin/clang)
set(CMAKE_CXX_COMPILER /usr/bin/clang++)
set(HB /opt/homebrew)
set(OpenMP_C_FLAGS "-Xpreprocessor -fopenmp -I${HB}/opt/libomp/include")
set(OpenMP_CXX_FLAGS "${OpenMP_C_FLAGS}")
set(OpenMP_C_LIB_NAMES "omp")
set(OpenMP_CXX_LIB_NAMES "omp")
set(OpenMP_omp_LIBRARY "${HB}/opt/libomp/lib/libomp.dylib")
set(OpenCL_INCLUDE_DIR "${HB}/opt/opencl-headers/include")
set(OpenCL_LIBRARY "/System/Library/Frameworks/OpenCL.framework")
set(CMAKE_PREFIX_PATH "${HB}")
set(CMAKE_INCLUDE_PATH "${HB}/include")
set(CMAKE_LIBRARY_PATH "${HB}/lib")
set(CMAKE_IGNORE_PATH "/usr/local")
set(CMAKE_C_FLAGS "-I${HB}/opt/opencl-headers/include -I${HB}/opt/libomp/include -DCL_TARGET_OPENCL_VERSION=120 -DCL_SILENCE_DEPRECATION=1")
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "-L${HB}/opt/libomp/lib")
set(CMAKE_SHARED_LINKER_FLAGS "-L${HB}/opt/libomp/lib")
