compctl  -x 's[-]' -s " f ox od of g h nice noxvgr free norms cutoff" - 'c[-1,-f]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-ox]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-of]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' -- anadock
compctl  -x 's[-]' -s " s g q d o n dom h nice noengh bm am pm rr ar er vm lm il dm im nm hm hb nobon nonb measure maxdist add vir sm" - 'c[-1,-sm]' -s " none tri tetra" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-q]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-d]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-dom]' -g '*.ndx(|.gz|.Z) *(/)' -- cdist
compctl  -x 's[-]' -s " g f d do c center n o keep viol h nice nf nit nov nochiral nopep lower weighted dump cubic explicit fit nbcheck nstprint ranlist noranlistfirst lowdev seed box grow" - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-d]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-do]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' - 'c[-1,-center]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-keep]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-viol]' -g '*.pdb(|.gz|.Z) *(/)' -- disco
compctl  -x 's[-]' -s " f s n ssdump map o sc a ta aa h nice b e dt tu w noxvgr sss" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-ssdump]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-map]' -g '*.map(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-sc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-a]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-ta]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-aa]' -g '*.xvg(|.gz|.Z) *(/)' -- do_dssp
compctl  -x 's[-]' -s " f n o mead bf h nice w ndef bt box angles d c center translate rotate princ scale density novol pbc grasp rvdw sig56 vdwread atom legend label" - 'c[-1,-bt]' -s " tric cubic dodecahedron octahedron" - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' - 'c[-1,-mead]' -g '*.pqr(|.gz|.Z) *(/)' - 'c[-1,-bf]' -g '*.dat(|.gz|.Z) *(/)' -- editconf
compctl  -x 's[-]' -s " f o h nice b e dt offset settime nosort scalefac noerror" - 'c[-1,-f]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(edr|ene)(|.gz|.Z) *(/)' -- eneconv
compctl  -x 's[-]' -s " s g table parm ga c e o h nice noxvgr tol fmax nocomb npow logeps v epot fepot pres fpres fmsf molsize nmol" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-table]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-parm]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-ga]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.gro(|.gz|.Z) *(/)' - 'c[-1,-e]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(trr|trj)(|.gz|.Z) *(/)' -- ffscan
compctl  -x 's[-]' -s " v v2 f s n eig eig2 comp rmsf proj 2d 3d filt extr over inpr h nice b e dt tu w noxvgr first last skip max nframes split" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-v]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-v2]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-eig]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-eig2]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-comp]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-rmsf]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-proj]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-2d]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-3d]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' - 'c[-1,-filt]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-extr]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-over]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-inpr]' -g '*.xpm(|.gz|.Z) *(/)' -- g_anaeig
compctl  -x 's[-]' -s " f ac msd cc dist av ee g h nice w noxvgr notime b e n d bw errbar integrate aver_start xydy filter power nosubav oneacf acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-errbar]' -s " none stddev error 90" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7 exp9" - 'c[-1,-f]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ac]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-msd]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-cc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dist]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-av]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ee]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' -- g_analyze
compctl  -x 's[-]' -s " f s n od ov of ot oh oc or h nice b e dt w noxvgr type all binwidth chandler avercorr acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-type]' -s " angle dihedral improper ryckaert-bellemans" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7 exp9" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ov]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-of]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ot]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oh]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-or]' -g '*.trr(|.gz|.Z) *(/)' -- g_angle
compctl  -x 's[-]' -s " f n s o l d h nice b e dt w noxvgr blen tol noaver noaverdist" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-l]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-d]' -g '*.xvg(|.gz|.Z) *(/)' -- g_bond
compctl  -x 's[-]' -s " f s n ol od oz ot otr otl ok okr okl oa h nice b e dt tu noxvgr na z" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-ol]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oz]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ot]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-otr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-otl]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ok]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-okr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-okl]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oa]' -g '*.pdb(|.gz|.Z) *(/)' -- g_bundle
compctl  -x 's[-]' -s " s f o p ss jc corr g ot oh rt cp h nice b e dt w noxvgr r0 phi psi omega rama viol all rad shift binwidth core_rotamer maxchi nonormhisto ramomega bfact chi_prod HChi bmax acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-maxchi]' -s " 0 1 2 3 4 5 6" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7 exp9" - 'c[-1,-s]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-p]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-ss]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-jc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-corr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-ot]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oh]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-rt]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-cp]' -g '*.xvg(|.gz|.Z) *(/)' -- g_chi
compctl  -x 's[-]' -s " f s n dm o g dist ev sz tr ntr clid cl h nice b e dt tu w noxvgr dista nlevels cutoff nofit max skip av wcl nst rmsmin method minstruct binary M P seed niter kT" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-method]' -s " linkage jarvis-patrick monte-carlo diagonalization gromos" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-dm]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-dist]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ev]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-sz]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-tr]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-ntr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-clid]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-cl]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' -- g_cluster
compctl  -x 's[-]' -s " f s n o ow nc mc ac hc temp mcn h nice b e dt tu w noxvgr cut mol nopbc nskip nlevels ndf rgblo rgbhi" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.tpr(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-ow]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-nc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-mc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ac]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-hc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-temp]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-mcn]' -g '*.ndx(|.gz|.Z) *(/)' -- g_clustsize
compctl  -x 's[-]' -s " f1 f2 o n1 n2 no h nice w one nomw pbc nofit name bfac" - 'c[-1,-f1]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-f2]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' - 'c[-1,-n1]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-n2]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-no]' -g '*.ndx(|.gz|.Z) *(/)' -- g_confrms
compctl  -x 's[-]' -s " f s n o v av l ascii xpm xpma h nice b e dt tu noxvgr nofit ref mwa last nopbc" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-v]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-av]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' - 'c[-1,-l]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-ascii]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-xpm]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-xpma]' -g '*.xpm(|.gz|.Z) *(/)' -- g_covar
compctl  -x 's[-]' -s " f n s ei o h nice b e dt w noxvgr d sl number ed count ng symm center" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-ei]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_density
compctl  -x 's[-]' -s " f s n o h nice b e dt w bin nx nz amax rmax mirror dmax" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xpm(|.gz|.Z) *(/)' -- g_densmap
compctl  -x 's[-]' -s " f d o c h nice b e dt w noxvgr fft nox1 eint bfit efit tail A tau1 tau2 eps0 epsRF fix ffn nsmooth" - 'c[-1,-ffn]' -s " none exp aexp exp_exp vac exp5 exp7 exp9" - 'c[-1,-f]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-d]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.xvg(|.gz|.Z) *(/)' -- g_dielectric
compctl  -x 's[-]' -s " f s o h nice b e dt w sa mult" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.out(|.gz|.Z) *(/)' -- g_dih
compctl  -x 's[-]' -s " enx f s n o eps a d c g adip dip3d cos q slab h nice b e dt w noxvgr mu mumax epsilonRF skip temp avercorr nopairs axis sl gkratom acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7 exp9" - 'c[-1,-enx]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-eps]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-a]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-d]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-adip]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dip3d]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-cos]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-q]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-slab]' -g '*.xvg(|.gz|.Z) *(/)' -- g_dipoles
compctl  -x 's[-]' -s " s f ds da dn dm dr l n q c h nice b e dt w noxvgr ntop" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-ds]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-da]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dn]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dm]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-l]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-q]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.ndx(|.gz|.Z) *(/)' -- g_disre
compctl  -x 's[-]' -s " f s n o h nice b e dt noxvgr dist" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_dist
compctl  -x 's[-]' -s " f o n h nice firstangle lastangle nframe maxangle trans head tail" - 'c[-1,-f]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' -- g_dyndom
compctl  -x 's[-]' -s " f groups eref emat etot h nice b e dt w noxvgr sum skip nomean nlevels max min nocoul coulr coul14 nolj lj lj14 bhamsr bhamlr nofree temp" - 'c[-1,-f]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-groups]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-eref]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-emat]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-etot]' -g '*.xvg(|.gz|.Z) *(/)' -- g_enemat
compctl  -x 's[-]' -s " f f2 s o viol pairs ora ort oda odr odt oten corr vis ravg h nice b e w noxvgr fee fetemp zero sum dp mutot skip aver nmol ndf fluc orinst ovec acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7 exp9" - 'c[-1,-f]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-f2]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-viol]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-pairs]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ora]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ort]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oda]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-odr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-odt]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oten]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-corr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-vis]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ravg]' -g '*.xvg(|.gz|.Z) *(/)' -- g_energy
compctl  -x 's[-]' -s " f s n ol oh h nice b e dt w nf all nonojump fit" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-ol]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-oh]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' -- g_filter
compctl  -x 's[-]' -s " f s n o acf h nice b e dt w noxvgr nmol q p moi acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7 exp9" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-acf]' -g '*.xvg(|.gz|.Z) *(/)' -- g_gyrate
compctl  -x 's[-]' -s " f n nm s o h nice b e dt w noxvgr d sl" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-nm]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_h2order
compctl  -x 's[-]' -s " f s n g sel num ac dist ang hx hbn hbm don dan life h nice b e dt noxvgr ins a r noda abin rbin nonitacc contact shell fitstart temp dump max_hb nomerge acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7 exp9" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-sel]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-num]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ac]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dist]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ang]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-hx]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-hbn]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-hbm]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-don]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dan]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-life]' -g '*.xvg(|.gz|.Z) *(/)' -- g_hbond
compctl  -x 's[-]' -s " s n f to cz co h nice b e dt w r0 q noF db prop ev ahxstart ahxend" - 'c[-1,-prop]' -s " RAD TWIST RISE LEN NHX DIP RMS CPHI RMSA PHI PSI HB3 HB4 HB5 CD222" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-to]' -g '*.g87(|.gz|.Z) *(/)' - 'c[-1,-cz]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' - 'c[-1,-co]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' -- g_helix
compctl  -x 's[-]' -s " f o h nice b e dt w noxvgr Elj Eqq Clj Cqq ligand" - 'c[-1,-f]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_lie
compctl  -x 's[-]' -s " f s n mean frames no h nice b e dt noxvgr t nlevels" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-mean]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-frames]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-no]' -g '*.xvg(|.gz|.Z) *(/)' -- g_mdmat
compctl  -x 's[-]' -s " f s n od on o ox or h nice b e dt tu w noxvgr matrix max d pi split ng" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-on]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.out(|.gz|.Z) *(/)' - 'c[-1,-ox]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-or]' -g '*.xvg(|.gz|.Z) *(/)' -- g_mindist
compctl  -x 's[-]' -s " f1 f2 o or n h nice w noxvgr ninterm first last nofit" - 'c[-1,-f1]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-f2]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-or]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' -- g_morph
compctl  -x 's[-]' -s " f s n o mol h nice b e dt tu w noxvgr type lateral ngroup nomw trestart beginfit endfit" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-type]' -s " no x y z" - 'c[-1,-lateral]' -s " no x y z" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-mol]' -g '*.xvg(|.gz|.Z) *(/)' -- g_msd
compctl  -x 's[-]' -s " f s of ol v h nice noxvgr nom first last" - 'c[-1,-f]' -g '*.mtx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-of]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ol]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-v]' -g '*.(trr|trj)(|.gz|.Z) *(/)' -- g_nmeig
compctl  -x 's[-]' -s " v e s n o h nice noxvgr temp seed num first last" - 'c[-1,-v]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-e]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' -- g_nmens
compctl  -x 's[-]' -s " s v o h nice eignr temp amplitude nframes" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-v]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' -- g_nmtraj
compctl  -x 's[-]' -s " f n s o od os h nice b e dt w noxvgr d sl szonly unsat" - 'c[-1,-d]' -s " z x y" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-os]' -g '*.xvg(|.gz|.Z) *(/)' -- g_order
compctl  -x 's[-]' -s " f n s o oc of h nice b e dt w noxvgr d sl cb ce tz spherical ng" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-of]' -g '*.xvg(|.gz|.Z) *(/)' -- g_potential
compctl  -x 's[-]' -s " f s o h nice b e dt w noxvgr" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_rama
compctl  -x 's[-]' -s " f s n o sq cn hq h nice b e dt w noxvgr bin com nopbc xy cut ng fade nlevel startq endq energy" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-sq]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-cn]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-hq]' -g '*.xvg(|.gz|.Z) *(/)' -- g_rdf
compctl  -x 's[-]' -s " s f f2 n o mir a dist m bin bm h nice b e dt tu w noxvgr what nopbc fit prev split skip skip2 max min bmax bmin nlevels ng" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-what]' -s " rmsd rho rhosc" - 'c[-1,-fit]' -s " rot+trans translation none" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-f2]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-mir]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-a]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dist]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-m]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-bin]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-bm]' -g '*.xpm(|.gz|.Z) *(/)' -- g_rms
compctl  -x 's[-]' -s " f s n equiv o rms scl mean nmr3 nmr6 noe h nice b e dt w noxvgr nlevels max nosumh" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-equiv]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-rms]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-scl]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-mean]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-nmr3]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-nmr6]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-noe]' -g '*.dat(|.gz|.Z) *(/)' -- g_rmsdist
compctl  -x 's[-]' -s " f s n q oq ox o od oc dir h nice b e dt w noxvgr res aniso" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-q]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-oq]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-ox]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dir]' -g '*.log(|.gz|.Z) *(/)' -- g_rmsf
compctl  -x 's[-]' -s " f s n o h nice b e dt w noxvgr d noaver acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7 exp9" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_rotacf
compctl  -x 's[-]' -s " f s h nice b e dt t sep" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' -- g_saltbr
compctl  -x 's[-]' -s " f s o or oa q n i h nice b e dt w noxvgr solsize ndots qmax f_index minarea nopbc noprot dgs" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-or]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oa]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-q]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-i]' -g '*.itp(|.gz|.Z) *(/)' -- g_sas
compctl  -x 's[-]' -s " f n s oa od od1 od2 h nice b e dt w noxvgr pbc one z" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-oa]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-od1]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-od2]' -g '*.xvg(|.gz|.Z) *(/)' -- g_sgangle
compctl  -x 's[-]' -s " f ge ene dist histo bin ls lsh lss map ls3 mdata g h nice w noxvgr notime b e ttol n d bw nosham tsham pmin dim ngrid xmin xmax gmax nlevels mname" - 'c[-1,-f]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ge]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ene]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dist]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-histo]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-bin]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-ls]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-lsh]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-lss]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-map]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-ls3]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-mdata]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' -- g_sham
compctl  -x 's[-]' -s " f s n o no ro co h nice b e dt w noxvgr com rmin rmax bin pbc" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-no]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ro]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-co]' -g '*.xvg(|.gz|.Z) *(/)' -- g_sorient
compctl  -x 's[-]' -s " f s n ot oa o of oc ov h nice b e dt w noxvgr mol k34 wt acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7 exp9" - 'c[-1,-f]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-ot]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oa]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-of]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ov]' -g '*.xvg(|.gz|.Z) *(/)' -- g_tcaf
compctl  -x 's[-]' -s " f s n ox ov of ob ot ekt ekr vd cv cf h nice b e dt tu w noxvgr com mol nojump nox noy noz ng len bin scale" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-ox]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ov]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-of]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ob]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ot]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ekt]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ekr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-vd]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-cv]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-cf]' -g '*.pdb(|.gz|.Z) *(/)' -- g_traj
compctl  -x 's[-]' -s " f s n o h nice b e dt w noxvgr mol acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7 exp9" - 'c[-1,-f]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_velacc
compctl  -x 's[-]' -s " o hist h nice w noxvgr min max bins noprof temp flip tol" - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-hist]' -g '*.xvg(|.gz|.Z) *(/)' -- g_wham
compctl  -x 's[-]' -s " cp cs ci o p h nice box nmol try seed vdwd shell" - 'c[-1,-cp]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-cs]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-ci]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' - 'c[-1,-p]' -g '*.top(|.gz|.Z) *(/)' -- genbox
compctl  -x 's[-]' -s " f o trj h nice nbox dist seed rot shuffle sort block nmolat maxrot norenumber" - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' - 'c[-1,-trj]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' -- genconf
compctl  -x 's[-]' -s " s table n o g pot h nice noxvgr np pname pq nn nname nq rmin random seed scale" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-table]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-pot]' -g '*.pdb(|.gz|.Z) *(/)' -- genion
compctl  -x 's[-]' -s " f n o of h nice fc freeze" - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.itp(|.gz|.Z) *(/)' - 'c[-1,-of]' -g '*.ndx(|.gz|.Z) *(/)' -- genpr
compctl  -x 's[-]' -s " f f2 s1 s2 c e e2 n h nice vdwfac bonlo bonhi tol lastener" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-f2]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s1]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-s2]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-e]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-e2]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' -- gmxcheck
compctl  -x 's[-]' -s " s f e h nice nonr" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-e]' -g '*.(edr|ene)(|.gz|.Z) *(/)' -- gmxdump
compctl  -x 's[-]' -s " f po c r rb n deshuf p pp o t e h nice nov time np shuffle sort normvsbds load maxwarn check14 norenum" - 'c[-1,-f]' -g '*.mdp(|.gz|.Z) *(/)' - 'c[-1,-po]' -g '*.mdp(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-r]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-rb]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-deshuf]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-p]' -g '*.top(|.gz|.Z) *(/)' - 'c[-1,-pp]' -g '*.top(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-t]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-e]' -g '*.(edr|ene)(|.gz|.Z) *(/)' -- grompp
compctl  -x 's[-]' -s " f h nice" - 'c[-1,-f]' -g '*.dat(|.gz|.Z) *(/)' -- highway
compctl  -x 's[-]' -s " f eig s n tar ori o h nice noxvgr mon linfix linacc radfix radacc radcon flood outfrq logfrq slope maxedsteps deltaF0 deltaF tau eqsteps Eflnull T alpha linstep accdir radstep restrain hesse harmonic" - 'c[-1,-f]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-eig]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-tar]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-ori]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.edi(|.gz|.Z) *(/)' -- make_edi
compctl  -x 's[-]' -s " f n o h nice natoms" - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.ndx(|.gz|.Z) *(/)' -- make_ndx
compctl  -x 's[-]' -s " s o x c e g dgdl field table tablep rerun tpi ei eo j jo ffout devout runav pi po pd pn mtx dn h nice deffnm noxvgr np nt v nocompact sepdvdl multi replex reseed glas ionize" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-x]' -g '*.xtc(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' - 'c[-1,-e]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-dgdl]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-field]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-table]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-tablep]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-rerun]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-tpi]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ei]' -g '*.edi(|.gz|.Z) *(/)' - 'c[-1,-eo]' -g '*.edo(|.gz|.Z) *(/)' - 'c[-1,-j]' -g '*.gct(|.gz|.Z) *(/)' - 'c[-1,-jo]' -g '*.gct(|.gz|.Z) *(/)' - 'c[-1,-ffout]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-devout]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-runav]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-pi]' -g '*.ppa(|.gz|.Z) *(/)' - 'c[-1,-po]' -g '*.ppa(|.gz|.Z) *(/)' - 'c[-1,-pd]' -g '*.pdo(|.gz|.Z) *(/)' - 'c[-1,-pn]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-mtx]' -g '*.mtx(|.gz|.Z) *(/)' - 'c[-1,-dn]' -g '*.ndx(|.gz|.Z) *(/)' -- mdrun
compctl  -x 's[-]' -s " s n h nice type" - 'c[-1,-type]' -s " angle g96-angle dihedral improper ryckaert-bellemans phi-psi" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' -- mk_angndx
compctl  -x 's[-]' -s " f s n h nice b e dt" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' -- ngmx
compctl  -x 's[-]' -s " f o p i n q h nice merge ff water inter ss ter lys asp glu his angle dist una ignh missing v posrefc vsite heavyh deuterate" - 'c[-1,-water]' -s " spc spce tip3p tip4p tip5p f3c" - 'c[-1,-vsite]' -s " none hydrogens aromatics" - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' - 'c[-1,-p]' -g '*.top(|.gz|.Z) *(/)' - 'c[-1,-i]' -g '*.itp(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-q]' -g '*.(gro|g96|pdb|brk|ent|esp)(|.gz|.Z) *(/)' -- pdb2gmx
compctl  -x 's[-]' -s " s f n o h nice b e dt" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' -- protonate
compctl  -x 's[-]' -s " s f e n o h nice time extend until zeroq nounconstrained" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-e]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' -- tpbconv
compctl  -x 's[-]' -s " f o n demux h nice tu noxvgr b e dt prec novel settime nosort keeplast cat" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-demux]' -g '*.xvg(|.gz|.Z) *(/)' -- trjcat
compctl  -x 's[-]' -s " f o s n fr sub drop h nice b e tu w noxvgr skip dt dump t0 timestep pbc ur center box shift fit ndec novel force trunc exec app split sep ter dropunder dropover" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-pbc]' -s " none whole inbox nojump cluster com" - 'c[-1,-ur]' -s " rect tric compact" - 'c[-1,-center]' -s " no tric rect zero" - 'c[-1,-fit]' -s " none rot+trans translation progressive" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-fr]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-sub]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-drop]' -g '*.xvg(|.gz|.Z) *(/)' -- trjconv
compctl  -x 's[-]' -s " f s n o nshell h nice b e dt noxvgr na da com r" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-nshell]' -g '*.xvg(|.gz|.Z) *(/)' -- trjorder
compctl  -x 's[-]' -s " f o h nice r0 rot0 T nonn" - 'c[-1,-f]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.eps(|.gz|.Z) *(/)' -- wheel
compctl  -x 's[-]' -s " f o r h nice scale ff nexcl noH14 alldih remdih nopairs name nopbc param noround kb kt kp" - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|esp|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.top(|.gz|.Z) *(/)' - 'c[-1,-r]' -g '*.rtp(|.gz|.Z) *(/)' -- x2top
compctl  -x 's[-]' -s " f f2 di do o xpm h nice w noframe title yonce legend diag combine size bx by rainbow gradient skip zeroline legoffset" - 'c[-1,-title]' -s " top once ylabel none" - 'c[-1,-legend]' -s " both first second none" - 'c[-1,-diag]' -s " first second none" - 'c[-1,-combine]' -s " halves add sub mult div" - 'c[-1,-rainbow]' -s " no blue red" - 'c[-1,-f]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-f2]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-di]' -g '*.m2p(|.gz|.Z) *(/)' - 'c[-1,-do]' -g '*.m2p(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.eps(|.gz|.Z) *(/)' - 'c[-1,-xpm]' -g '*.xpm(|.gz|.Z) *(/)' -- xpm2ps
compctl  -x 's[-]' -s " f s h nice b e dt" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' -- xrama
