compctl  -x 's[-]' -s " f s n ssdump map o sc a ta aa h X nice b e dt tu w sss" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-ssdump]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-map]' -g '*.map(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-sc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-a]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-ta]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-aa]' -g '*.xvg(|.gz|.Z) *(/)' -- do_dssp
compctl  -x 's[-]' -s " f n o bf h X nice w ndef bt box angles d c center rotate princ scale density pbc mead grasp rvdw atom legend label" - 'c[-1,-bt]' -s " tric cubic dodecahedron octahedron" - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-bf]' -g '*.dat(|.gz|.Z) *(/)' -- editconf
compctl  -x 's[-]' -s " f o h X nice b e dt offset settime nosort scalefac noerror" - 'c[-1,-f]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(edr|ene)(|.gz|.Z) *(/)' -- eneconv
compctl  -x 's[-]' -s " s g table parm ga h X nice tol fmax epot nocomb npow ratio logeps nov" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-table]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-parm]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-ga]' -g '*.dat(|.gz|.Z) *(/)' -- ffscan
compctl  -x 's[-]' -s " v v2 f s n eig1 eig2 disp proj 2d 3d filt extr over inpr h X nice b e dt tu w first last skip max nframes split" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-v]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-v2]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-eig1]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-eig2]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-disp]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-proj]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-2d]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-3d]' -g '*.(gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-filt]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-extr]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-over]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-inpr]' -g '*.xpm(|.gz|.Z) *(/)' -- g_anaeig
compctl  -x 's[-]' -s " f ac msd cc dist av ee g h X nice w notime b e n d bw errbar power nosubav oneacf acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-errbar]' -s " none stddev error 90" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7" - 'c[-1,-f]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ac]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-msd]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-cc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dist]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-av]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ee]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' -- g_analyze
compctl  -x 's[-]' -s " f s n od ov of ot oh oc h X nice b e dt w type all binwidth chandler avercorr acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-type]' -s " angle dihedral improper ryckaert-bellemans" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ov]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-of]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ot]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oh]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oc]' -g '*.xvg(|.gz|.Z) *(/)' -- g_angle
compctl  -x 's[-]' -s " f n s o l d h X nice b e dt w blen tol noaver" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-l]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-d]' -g '*.xvg(|.gz|.Z) *(/)' -- g_bond
compctl  -x 's[-]' -s " f s n ol od oz ot otr otl ok okr okl oa h X nice b e dt tu na z" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-ol]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oz]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ot]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-otr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-otl]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ok]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-okr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-okl]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oa]' -g '*.pdb(|.gz|.Z) *(/)' -- g_bundle
compctl  -x 's[-]' -s " c f o p ss jc corr g h X nice b e dt w r0 phi psi omega rama viol all shift run maxchi nonormhisto ramomega bfact bmax acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-maxchi]' -s " 0 1 2 3 4 5 6" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7" - 'c[-1,-c]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-p]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-ss]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-jc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-corr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' -- g_chi
compctl  -x 's[-]' -s " f s n dm o g dist ev sz tr ntr clid cl h X nice b e dt tu w dista nlevels keepfree cutoff nofit max skip av wcl nst rmsmin method binary M P seed niter kT" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-method]' -s " linkage jarvis-patrick monte-carlo diagonalization gromos" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-dm]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-dist]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ev]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-sz]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-tr]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-ntr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-clid]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-cl]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' -- g_cluster
compctl  -x 's[-]' -s " f n o nc mc ac h X nice b e dt w cut nskip nlevels rgblo rgbhi" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-nc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-mc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ac]' -g '*.xvg(|.gz|.Z) *(/)' -- g_clustsize
compctl  -x 's[-]' -s " f1 f2 o n1 n2 h X nice one pbc" - 'c[-1,-f1]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-f2]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n1]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-n2]' -g '*.ndx(|.gz|.Z) *(/)' -- g_confrms
compctl  -x 's[-]' -s " f s n o v av l xpm xpma h X nice b e dt tu nofit ref mwa last" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-v]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-av]' -g '*.(gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-l]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-xpm]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-xpma]' -g '*.xpm(|.gz|.Z) *(/)' -- g_covar
compctl  -x 's[-]' -s " f n s ei o h X nice b e dt w d sl number ed count" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-ei]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_density
compctl  -x 's[-]' -s " f d o c h X nice b e dt w fft nox1 eint bfit efit tail A tau1 tau2 eps0 epsRF fix ffn nsmooth" - 'c[-1,-ffn]' -s " none exp aexp exp_exp vac exp5 exp7" - 'c[-1,-f]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-d]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.xvg(|.gz|.Z) *(/)' -- g_dielectric
compctl  -x 's[-]' -s " f s o h X nice b e dt w sa mult" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.out(|.gz|.Z) *(/)' -- g_dih
compctl  -x 's[-]' -s " enx f s n o e a d c g q h X nice b e dt w mu mumax epsilonRF skip temp avercorr gkratom acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7" - 'c[-1,-enx]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-e]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-a]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-d]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-q]' -g '*.xvg(|.gz|.Z) *(/)' -- g_dipoles
compctl  -x 's[-]' -s " s f ds da dn dm dr l n h X nice b e dt w ntop" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-ds]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-da]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dn]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dm]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-l]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' -- g_disre
compctl  -x 's[-]' -s " f s n o h X nice b e dt dist" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_dist
compctl  -x 's[-]' -s " f o n h X nice firstangle lastangle nframe maxangle trans head tail" - 'c[-1,-f]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' -- g_dyndom
compctl  -x 's[-]' -s " cp cs ci o p h X nice box nmol try seed vdwd shell" - 'c[-1,-cp]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-cs]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-ci]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-p]' -g '*.top(|.gz|.Z) *(/)' -- genbox
compctl  -x 's[-]' -s " f o trj h X nice nbox dist seed rot shuffle sort block nmolat maxrot renumber" - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-trj]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' -- genconf
compctl  -x 's[-]' -s " f groups eref emat etot h X nice b e dt w sum skip nomean nlevels max min nocoul coulr coul14 nolj lj14 bham nofree temp" - 'c[-1,-f]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-groups]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-eref]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-emat]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-etot]' -g '*.xvg(|.gz|.Z) *(/)' -- g_enemat
compctl  -x 's[-]' -s " f f2 s o viol pairs ora ort oda odr odt corr vis ravg h X nice b e w fee fetemp zero sum dp mutot skip aver nmol ndf fluc orinst acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7" - 'c[-1,-f]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-f2]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-viol]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-pairs]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ora]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ort]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oda]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-odr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-odt]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-corr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-vis]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ravg]' -g '*.xvg(|.gz|.Z) *(/)' -- g_energy
compctl  -x 's[-]' -s " s n o g pot h X nice np pname pq nn nname nq rmin random seed" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-pot]' -g '*.pdb(|.gz|.Z) *(/)' -- genion
compctl  -x 's[-]' -s " f n o h X nice fc" - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.itp(|.gz|.Z) *(/)' -- genpr
compctl  -x 's[-]' -s " f s o n h X nice b e dt w q p" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' -- g_gyrate
compctl  -x 's[-]' -s " f n nm s o h X nice b e dt w d sl" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-nm]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_h2order
compctl  -x 's[-]' -s " f s n g sel num ac dist ang hx hbn hbm da h X nice b e dt ins a r abin rbin nonitacc shell" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-sel]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-num]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ac]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dist]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ang]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-hx]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-hbn]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-hbm]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-da]' -g '*.xvg(|.gz|.Z) *(/)' -- g_hbond
compctl  -x 's[-]' -s " s n f to cz co h X nice b e dt w r0 q noF db ev ahxstart ahxend" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-to]' -g '*.g87(|.gz|.Z) *(/)' - 'c[-1,-cz]' -g '*.(gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-co]' -g '*.(gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' -- g_helix
compctl  -x 's[-]' -s " f o h X nice b e dt w Elj Eqq Clj Cqq ligand" - 'c[-1,-f]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_lie
compctl  -x 's[-]' -s " f s n mean frames no h X nice b e dt t nlevels" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-mean]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-frames]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-no]' -g '*.xvg(|.gz|.Z) *(/)' -- g_mdmat
compctl  -x 's[-]' -s " f s n od on o h X nice b e dt w matrix d pi" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-on]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.out(|.gz|.Z) *(/)' -- g_mindist
compctl  -x 's[-]' -s " f1 f2 o or n h X nice w ninterm first last nofit" - 'c[-1,-f1]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-f2]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-or]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' -- g_morph
compctl  -x 's[-]' -s " f s n o mol h X nice b e dt tu w type lateral ngroup nomw trestart beginfit endfit" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-type]' -s " no x y z" - 'c[-1,-lateral]' -s " no x y z" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-mol]' -g '*.xvg(|.gz|.Z) *(/)' -- g_msd
compctl  -x 's[-]' -s " f f2 s1 s2 c e e2 h X nice vdwfac bonlo bonhi tol lastener" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-f2]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s1]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-s2]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-e]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-e2]' -g '*.(edr|ene)(|.gz|.Z) *(/)' -- gmxcheck
compctl  -x 's[-]' -s " s f e h X nice nonr" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-e]' -g '*.(edr|ene)(|.gz|.Z) *(/)' -- gmxdump
compctl  -x 's[-]' -s " f s o v h X nice nom first last" - 'c[-1,-f]' -g '*.mtx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-v]' -g '*.(trr|trj)(|.gz|.Z) *(/)' -- g_nmeig
compctl  -x 's[-]' -s " v e s n o h X nice temp seed num first last" - 'c[-1,-v]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-e]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' -- g_nmens
compctl  -x 's[-]' -s " f n s o od os h X nice b e dt w d sl szonly unsat" - 'c[-1,-d]' -s " z x y" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-os]' -g '*.xvg(|.gz|.Z) *(/)' -- g_order
compctl  -x 's[-]' -s " f n s o oc of h X nice b e dt w d sl cb ce tz spherical" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-of]' -g '*.xvg(|.gz|.Z) *(/)' -- g_potential
compctl  -x 's[-]' -s " f s o h X nice b e dt w" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_rama
compctl  -x 's[-]' -s " f s n o sq cn hq image h X nice b e dt w bin com cut fade grid nlevel wave" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-sq]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-cn]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-hq]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-image]' -g '*.xpm(|.gz|.Z) *(/)' -- g_rdf
compctl  -x 's[-]' -s " s f f2 n o mir a dist m bin bm h X nice b e dt tu w what nopbc nofit prev split skip skip2 max min bmax bmin nlevels" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-what]' -s " rmsd rho rhosc" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-f2]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-mir]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-a]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dist]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-m]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-bin]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-bm]' -g '*.xpm(|.gz|.Z) *(/)' -- g_rms
compctl  -x 's[-]' -s " f s n equiv o rms scl mean nmr3 nmr6 noe h X nice b e dt w nlevels max nosumh" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-equiv]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-rms]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-scl]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-mean]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-nmr3]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-nmr6]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-noe]' -g '*.dat(|.gz|.Z) *(/)' -- g_rmsdist
compctl  -x 's[-]' -s " f s n q oq ox o od oc dir h X nice b e dt w res aniso" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-q]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-oq]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-ox]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-dir]' -g '*.log(|.gz|.Z) *(/)' -- g_rmsf
compctl  -x 's[-]' -s " f po c r n deshuf p pp o t h X nice nov time np shuffle sort normdumbds load maxwarn check14" - 'c[-1,-f]' -g '*.mdp(|.gz|.Z) *(/)' - 'c[-1,-po]' -g '*.mdp(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-r]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-deshuf]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-p]' -g '*.top(|.gz|.Z) *(/)' - 'c[-1,-pp]' -g '*.top(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-t]' -g '*.(trr|trj)(|.gz|.Z) *(/)' -- grompp
compctl  -x 's[-]' -s " f s n o h X nice b e dt w d noaver acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_rotacf
compctl  -x 's[-]' -s " f s h X nice b e dt t sep" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' -- g_saltbr
compctl  -x 's[-]' -s " f s o r q ao n i h X nice b e dt w solsize ndots qmax minarea skip nopbc noprot dgs" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-r]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-q]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-ao]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-i]' -g '*.itp(|.gz|.Z) *(/)' -- g_sas
compctl  -x 's[-]' -s " f n s oa od od1 od2 h X nice b e dt w" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-oa]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-od]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-od1]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-od2]' -g '*.xvg(|.gz|.Z) *(/)' -- g_sgangle
compctl  -x 's[-]' -s " f s n o no ro co h X nice b e dt w com rmin rmax nbin" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-no]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ro]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-co]' -g '*.xvg(|.gz|.Z) *(/)' -- g_sorient
compctl  -x 's[-]' -s " f s n ot oa o of oc ov h X nice b e dt w mol k34 wt" - 'c[-1,-f]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-ot]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oa]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-of]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-oc]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ov]' -g '*.xvg(|.gz|.Z) *(/)' -- g_tcaf
compctl  -x 's[-]' -s " f s n ox ov of ob ot ekt ekr cv cf h X nice b e dt tu w com mol nojump nox noy noz len" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-ox]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ov]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-of]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ob]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ot]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ekt]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-ekr]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-cv]' -g '*.pdb(|.gz|.Z) *(/)' - 'c[-1,-cf]' -g '*.pdb(|.gz|.Z) *(/)' -- g_traj
compctl  -x 's[-]' -s " f s n o h X nice b e dt w mol acflen nonormalize P fitfn ncskip beginfit endfit" - 'c[-1,-P]' -s " 0 1 2 3" - 'c[-1,-fitfn]' -s " none exp aexp exp_exp vac exp5 exp7" - 'c[-1,-f]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.xvg(|.gz|.Z) *(/)' -- g_velacc
compctl  -x 's[-]' -s " f a h X nice b e dt" - 'c[-1,-f]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-a]' -g '*.dat(|.gz|.Z) *(/)' -- highway
compctl  -x 's[-]' -s " f n o h X nice" - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.ndx(|.gz|.Z) *(/)' -- make_ndx
compctl  -x 's[-]' -s " s o x c e g dgdl table rerun ei eo j jo ffout devout runav pi po pd pn mtx h X nice deffnm np v nocompact multi glas ionize" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-x]' -g '*.xtc(|.gz|.Z) *(/)' - 'c[-1,-c]' -g '*.(gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-e]' -g '*.(edr|ene)(|.gz|.Z) *(/)' - 'c[-1,-g]' -g '*.log(|.gz|.Z) *(/)' - 'c[-1,-dgdl]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-table]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-rerun]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-ei]' -g '*.edi(|.gz|.Z) *(/)' - 'c[-1,-eo]' -g '*.edo(|.gz|.Z) *(/)' - 'c[-1,-j]' -g '*.gct(|.gz|.Z) *(/)' - 'c[-1,-jo]' -g '*.gct(|.gz|.Z) *(/)' - 'c[-1,-ffout]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-devout]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-runav]' -g '*.xvg(|.gz|.Z) *(/)' - 'c[-1,-pi]' -g '*.ppa(|.gz|.Z) *(/)' - 'c[-1,-po]' -g '*.ppa(|.gz|.Z) *(/)' - 'c[-1,-pd]' -g '*.pdo(|.gz|.Z) *(/)' - 'c[-1,-pn]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-mtx]' -g '*.mtx(|.gz|.Z) *(/)' -- mdrun
compctl  -x 's[-]' -s " s n h X nice type" - 'c[-1,-type]' -s " angle g96-angle dihedral improper ryckaert-bellemans phi-psi" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' -- mk_angndx
compctl  -x 's[-]' -s " f s n h X nice b e dt" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' -- ngmx
compctl  -x 's[-]' -s " f o p i n q h X nice merge inter ss ter lys asp glu his angle dist posrefc una nosort H14 ignh alldih dummy heavyh deuterate" - 'c[-1,-dummy]' -s " none hydrogens aromatics" - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-p]' -g '*.top(|.gz|.Z) *(/)' - 'c[-1,-i]' -g '*.itp(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-q]' -g '*.(gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' -- pdb2gmx
compctl  -x 's[-]' -s " s f n o h X nice b e dt" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' -- protonate
compctl  -x 's[-]' -s " s f n o h X nice time extend until zeroq nounconstrained" - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-f]' -g '*.(trr|trj)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' -- tpbconv
compctl  -x 's[-]' -s " o n h X nice tu b e dt prec novel settime nosort cat" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' -- trjcat
compctl  -x 's[-]' -s " f o s n fr h X nice b e tu w skip dt dump t0 timestep pbc ur center box shift fit pfit ndec novel force trunc exec app split sep" - 'c[-1,-tu]' -s " ps fs ns us ms s m h" - 'c[-1,-pbc]' -s " none whole inbox nojump" - 'c[-1,-ur]' -s " rect tric compact" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-fr]' -g '*.ndx(|.gz|.Z) *(/)' -- trjconv
compctl  -x 's[-]' -s " f s n o h X nice b e dt na da" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa|gro|g96|pdb|brk|ent)(|.gz|.Z) *(/)' - 'c[-1,-n]' -g '*.ndx(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' -- trjorder
compctl  -x 's[-]' -s " f o h X nice r0 rot0 T nonn" - 'c[-1,-f]' -g '*.dat(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.eps(|.gz|.Z) *(/)' -- wheel
compctl  -x 's[-]' -s " f o r h X nice scale nexcl H14 alldih nopairs name nopbc param noround kb kt kp" - 'c[-1,-f]' -g '*.(gro|g96|pdb|brk|ent|tpr|tpb|tpa)(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.top(|.gz|.Z) *(/)' - 'c[-1,-r]' -g '*.rtp(|.gz|.Z) *(/)' -- x2top
compctl  -x 's[-]' -s " f f2 di do o xpm h X nice w noframe title yonce legend diag combine bx by rainbow gradient skip zeroline" - 'c[-1,-title]' -s " top once ylabel none" - 'c[-1,-legend]' -s " both first second none" - 'c[-1,-diag]' -s " first second none" - 'c[-1,-combine]' -s " halves add sub mult div" - 'c[-1,-rainbow]' -s " no blue red" - 'c[-1,-f]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-f2]' -g '*.xpm(|.gz|.Z) *(/)' - 'c[-1,-di]' -g '*.m2p(|.gz|.Z) *(/)' - 'c[-1,-do]' -g '*.m2p(|.gz|.Z) *(/)' - 'c[-1,-o]' -g '*.eps(|.gz|.Z) *(/)' - 'c[-1,-xpm]' -g '*.xpm(|.gz|.Z) *(/)' -- xpm2ps
compctl  -x 's[-]' -s " f s h X nice b e dt" - 'c[-1,-f]' -g '*.(xtc|trr|trj|gro|g96|pdb|g87)(|.gz|.Z) *(/)' - 'c[-1,-s]' -g '*.(tpr|tpb|tpa)(|.gz|.Z) *(/)' -- xrama
