#!/bin/sh
# Select which mode of gmx-ana to use in this script
type=nmens
# Create gmx-ana path from our name. Two cases:
# 1. $0 contains slash = a full or relative path
# 2. $0 without slash = gmx-ana must be in our path
case $0 in
  */*) gmxana=${0%/*}/gmx-ana ;;
  *)   gmxana=gmx-ana ;;
esac
# Check that the file is there
if [ ! -x $gmxana ]; then
  echo Cannot find executable $gmxana
    exit
fi
$gmxana -type $type $*
