#!/bin/bash

# TODO: (FR1+) Get script or script directory through repository or package infrastructure? (dependencies)
cd $HOME/acceptance
jupyter nbconvert RequiredFunctionality.ipynb --to python
python -c '
import gmxapi.version
try:
    import RequiredFunctionality
except gmxapi.version.FeatureError:
    pass'
