#!/bin/bash
# Entry point script for Docker containers.
# Additional arguments are passed along to pytest.
# See README.md and the gmxapi/ci-<option> Docker images.

# TODO: (#2756) Centrally manage dependencies on the GROMACS installation.
#  The gmxapi package, virtualenv, or test  infrastructure should have an
#  internal mechanism for tracking the correct GROMACS installation.
source /usr/local/gromacs/bin/GMXRC

pytest $HOME/gmxapi/test $@
