#!gmake
#
#	@(#) Makefile 1.85 9/30/97
#
#
#	GROMACS - Groningen Machine for Chemical Simulation
#	Copyright (c) 1990, 1991, 1992, Groningen University
#
#	Makefile for the Gromacs include file directory
#
all:


dep:

clean:
	$(RM) *~ #*# 

oclean:	clean
