.TH anadock 1 "Mon 29 Aug 2005"
.SH NAME
anadock
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3anadock\fP
.BI "-f" " eiwit.pdb "
.BI "-ox" " cluster.pdb "
.BI "-od" " edocked.xvg "
.BI "-of" " efree.xvg "
.BI "-g" " anadock.log "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-[no]xvgr" ""
.BI "-[no]free" ""
.BI "-[no]rms" ""
.BI "-cutoff" " real "
.SH DESCRIPTION
anadock analyses the results of an Autodock run and clusters the
structures together, based on distance or RMSD. The docked energy
and free energy estimates are analysed, and for each cluster the
energy statistics are printed.


An alternative approach to this is to cluster the structures first
(using 
.B g_cluster
and then sort the clusters on either lowest
energy or average energy.
.SH FILES
.BI "-f" " eiwit.pdb" 
.B Input
 Protein data bank file 

.BI "-ox" " cluster.pdb" 
.B Output
 Protein data bank file 

.BI "-od" " edocked.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-of" " efree.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-g" " anadock.log" 
.B Output
 Log file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-[no]free"  "    no"
 Use Free energy estimate from autodock for sorting the classes

.BI "-[no]rms"  "   yes"
 Cluster on RMS or distance

.BI "-cutoff"  " real" "    0.2" 
 Maximum RMSD/distance for belonging to the same cluster

