.TH editconf 1 "Mon 29 Aug 2005"
.SH NAME
editconf
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3editconf\fP
.BI "-f" " conf.gro "
.BI "-n" " index.ndx "
.BI "-o" " out.gro "
.BI "-mead" " mead.pqr "
.BI "-bf" " bfact.dat "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-[no]w" ""
.BI "-[no]ndef" ""
.BI "-bt" " enum "
.BI "-box" " vector "
.BI "-angles" " vector "
.BI "-d" " real "
.BI "-[no]c" ""
.BI "-center" " vector "
.BI "-translate" " vector "
.BI "-rotate" " vector "
.BI "-[no]princ" ""
.BI "-scale" " vector "
.BI "-density" " real "
.BI "-[no]vol" ""
.BI "-[no]pbc" ""
.BI "-[no]grasp" ""
.BI "-rvdw" " real "
.BI "-sig56" " real "
.BI "-[no]vdwread" ""
.BI "-[no]atom" ""
.BI "-[no]legend" ""
.BI "-label" " string "
.SH DESCRIPTION
editconf converts generic structure format to 
.B .gro
, 
.B .g96

or 
.B .pdb
.



The box can be modified with options 
.B -box
, 
.B -d
and

.B -angles
. Both 
.B -box
and 
.B -d

will center the system in the box.



Option 
.B -bt
determines the box type: 
.B tric
is a
triclinic box, 
.B cubic
is a cubic box, 
.B dodecahedron
is
a rhombic dodecahedron and 
.B octahedron
is a truncated octahedron.
The last two are special cases of a triclinic box.
The length of the three box vectors of the truncated octahedron is the
shortest distance between two opposite hexagons.
The volume of a dodecahedron is 0.71 and that of a truncated octahedron
is 0.77 of that of a cubic box with the same periodic image distance.



Option 
.B -box
requires only
one value for a cubic box, dodecahedron and a truncated octahedron.
With 
.B -d
and 
.B tric
the size of the system in the x, y
and z directions is used. With 
.B -d
and 
.B cubic
,

.B dodecahedron
or 
.B octahedron
the diameter of the system
is used, which is the largest distance between two atoms.



Option 
.B -angles
is only meaningful with option 
.B -box
and
a triclinic box and can not be used with option 
.B -d
.



When 
.B -n
or 
.B -ndef
is set, a group
can be selected for calculating the size and the geometric center,
otherwise the whole system is used.




.B -rotate
rotates the coordinates and velocities.




.B -princ
aligns the principal axes of the system along the
coordinate axes, this may allow you to decrease the box volume,
but beware that molecules can rotate significantly in a nanosecond.



Scaling is applied before any of the other operations are
performed. Boxes can be scaled to give a certain density (option

.B -density
). A special feature of the scaling option, when the
factor -1 is given in one dimension, one obtains a mirror image,
mirrored in one of the plains, when one uses -1 in three dimensions
a point-mirror image is obtained.


Groups are selected after all operations have been applied.


Periodicity can be removed in a crude manner.
It is important that the box sizes at the bottom of your input file
are correct when the periodicity is to be removed.



When writing 
.B .pdb
files, B-factors can be
added with the 
.B -bf
option. B-factors are read
from a file with with following format: first line states number of
entries in the file, next lines state an index
followed by a B-factor. The B-factors will be attached per residue
unless an index is larger than the number of residues or unless the

.B -atom
option is set. Obviously, any type of numeric data can
be added instead of B-factors. 
.B -legend
will produce
a row of CA atoms with B-factors ranging from the minimum to the
maximum value found, effectively making a legend for viewing.



With the option -mead a special pdb (pqr) file for the MEAD electrostatics
program (Poisson-Boltzmann solver) can be made. A further prerequisite
is that the input file is a run input file.
The B-factor field is then filled with the Van der Waals radius
of the atoms while the occupancy field will hold the charge.



The option -grasp is similar, but it puts the charges in the B-factor
and the radius in the occupancy.



Finally with option 
.B -label
editconf can add a chain identifier
to a pdb file, which can be useful for analysis with e.g. rasmol.


To convert a truncated octrahedron file produced by a package which uses
a cubic box with the corners cut off (such as Gromos) use:


.B editconf -f in -rotate 0 45 35.264 -bt o -box veclen -o out


where 
.B veclen
is the size of the cubic box times sqrt(3)/2.
.SH FILES
.BI "-f" " conf.gro" 
.B Input
 Generic structure: gro g96 pdb tpr tpb tpa xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-o" " out.gro" 
.B Output, Opt.
 Generic structure: gro g96 pdb xml 

.BI "-mead" " mead.pqr" 
.B Output, Opt.
 Coordinate file for MEAD 

.BI "-bf" " bfact.dat" 
.B Input, Opt.
 Generic data file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]ndef"  "    no"
 Choose output from default index groups

.BI "-bt"  " enum" " tric" 
 Box type for -box and -d: 
.B tric
, 
.B cubic
, 
.B dodecahedron
or 
.B octahedron


.BI "-box"  " vector" " 0 0 0" 
 Box vector lengths (a,b,c)

.BI "-angles"  " vector" " 90 90 90" 
 Angles between the box vectors (bc,ac,ab)

.BI "-d"  " real" "      0" 
 Distance between the solute and the box

.BI "-[no]c"  "    no"
 Center molecule in box (implied by -box and -d)

.BI "-center"  " vector" " 0 0 0" 
 Coordinates of geometrical center

.BI "-translate"  " vector" " 0 0 0" 
 Translation

.BI "-rotate"  " vector" " 0 0 0" 
 Rotation around the X, Y and Z axes in degrees

.BI "-[no]princ"  "    no"
 Orient molecule(s) along their principal axes

.BI "-scale"  " vector" " 1 1 1" 
 Scaling factor

.BI "-density"  " real" "   1000" 
 Density (g/l) of the output box achieved by scaling

.BI "-[no]vol"  "   yes"
 Compute and print volume of the box

.BI "-[no]pbc"  "    no"
 Remove the periodicity (make molecule whole again)

.BI "-[no]grasp"  "    no"
 Store the charge of the atom in the B-factor field and the radius of the atom in the occupancy field

.BI "-rvdw"  " real" "   0.12" 
 Default Van der Waals radius (in nm) if one can not be found in the database or if no parameters are present in the topology file

.BI "-sig56"  " real" "      0" 
 Use rmin/2 (minimum in the Van der Waals potential) rather than sigma/2 

.BI "-[no]vdwread"  "    no"
 Read the Van der Waals radii from the file vdwradii.dat rather than computing the radii based on the force field

.BI "-[no]atom"  "    no"
 Force B-factor attachment per atom

.BI "-[no]legend"  "    no"
 Make B-factor legend

.BI "-label"  " string" " A" 
 Add chain label for all residues

\- For complex molecules, the periodicity removal routine may break down, in that case you can use trjconv

