.TH g_anaeig 1 "Mon 29 Aug 2005"
.SH NAME
g_anaeig
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_anaeig\fP
.BI "-v" " eigenvec.trr "
.BI "-v2" " eigenvec2.trr "
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-eig" " eigenval.xvg "
.BI "-eig2" " eigenval2.xvg "
.BI "-comp" " eigcomp.xvg "
.BI "-rmsf" " eigrmsf.xvg "
.BI "-proj" " proj.xvg "
.BI "-2d" " 2dproj.xvg "
.BI "-3d" " 3dproj.pdb "
.BI "-filt" " filtered.xtc "
.BI "-extr" " extreme.pdb "
.BI "-over" " overlap.xvg "
.BI "-inpr" " inprod.xpm "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-tu" " enum "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-first" " int "
.BI "-last" " int "
.BI "-skip" " int "
.BI "-max" " real "
.BI "-nframes" " int "
.BI "-[no]split" ""
.SH DESCRIPTION

.B g_anaeig
analyzes eigenvectors. The eigenvectors can be of a
covariance matrix (
.B g_covar
) or of a Normal Modes anaysis
(
.B g_nmeig
).


When a trajectory is projected on eigenvectors, all structures are
fitted to the structure in the eigenvector file, if present, otherwise
to the structure in the structure file. When no run input file is
supplied, periodicity will not be taken into account. Most analyses
are performed on eigenvectors 
.B -first
to 
.B -last
, but when

.B -first
is set to -1 you will be prompted for a selection.



.B -comp
: plot the vector components per atom of eigenvectors

.B -first
to 
.B -last
.



.B -rmsf
: plot the RMS fluctuation per atom of eigenvectors

.B -first
to 
.B -last
(requires 
.B -eig
).



.B -proj
: calculate projections of a trajectory on eigenvectors

.B -first
to 
.B -last
.
The projections of a trajectory on the eigenvectors of its
covariance matrix are called principal components (pc's).
It is often useful to check the cosine content the pc's,
since the pc's of random diffusion are cosines with the number
of periods equal to half the pc index.
The cosine content of the pc's can be calculated with the program

.B g_analyze
.



.B -2d
: calculate a 2d projection of a trajectory on eigenvectors

.B -first
and 
.B -last
.



.B -3d
: calculate a 3d projection of a trajectory on the first
three selected eigenvectors.



.B -filt
: filter the trajectory to show only the motion along
eigenvectors 
.B -first
to 
.B -last
.



.B -extr
: calculate the two extreme projections along a trajectory
on the average structure and interpolate 
.B -nframes
frames
between them, or set your own extremes with 
.B -max
. The
eigenvector 
.B -first
will be written unless 
.B -first
and

.B -last
have been set explicitly, in which case all eigenvectors
will be written to separate files. Chain identifiers will be added
when writing a 
.B .pdb
file with two or three structures (you
can use 
.B rasmol -nmrpdb
to view such a pdb file).


  Overlap calculations between covariance analysis:

  NOTE: the analysis should use the same fitting structure



.B -over
: calculate the subspace overlap of the eigenvectors in
file 
.B -v2
with eigenvectors 
.B -first
to 
.B -last

in file 
.B -v
.



.B -inpr
: calculate a matrix of inner-products between
eigenvectors in files 
.B -v
and 
.B -v2
. All eigenvectors
of both files will be used unless 
.B -first
and 
.B -last

have been set explicitly.


When 
.B -v
, 
.B -eig
, 
.B -v2
and 
.B -eig2
are given,
a single number for the overlap between the covariance matrices is
generated. The formulas are:

        difference = sqrt(tr((sqrt(M1) - sqrt(M2))2))

normalized overlap = 1 - difference/sqrt(tr(M1) + tr(M2))

     shape overlap = 1 - sqrt(tr((sqrt(M1/tr(M1)) - sqrt(M2/tr(M2)))2))

where M1 and M2 are the two covariance matrices and tr is the trace
of a matrix. The numbers are proportional to the overlap of the square
root of the fluctuations. The normalized overlap is the most useful
number, it is 1 for identical matrices and 0 when the sampled
subspaces are orthogonal.
.SH FILES
.BI "-v" " eigenvec.trr" 
.B Input
 Full precision trajectory: trr trj 

.BI "-v2" " eigenvec2.trr" 
.B Input, Opt.
 Full precision trajectory: trr trj 

.BI "-f" " traj.xtc" 
.B Input, Opt.
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input, Opt.
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-eig" " eigenval.xvg" 
.B Input, Opt.
 xvgr/xmgr file 

.BI "-eig2" " eigenval2.xvg" 
.B Input, Opt.
 xvgr/xmgr file 

.BI "-comp" " eigcomp.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-rmsf" " eigrmsf.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-proj" " proj.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-2d" " 2dproj.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-3d" " 3dproj.pdb" 
.B Output, Opt.
 Generic structure: gro g96 pdb xml 

.BI "-filt" " filtered.xtc" 
.B Output, Opt.
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-extr" " extreme.pdb" 
.B Output, Opt.
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-over" " overlap.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-inpr" " inprod.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-tu"  " enum" " ps" 
 Time unit: 
.B ps
, 
.B fs
, 
.B ns
, 
.B us
, 
.B ms
, 
.B s
, 
.B m
or 
.B h


.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-first"  " int" " 1" 
 First eigenvector for analysis (-1 is select)

.BI "-last"  " int" " 8" 
 Last eigenvector for analysis (-1 is till the last)

.BI "-skip"  " int" " 1" 
 Only analyse every nr-th frame

.BI "-max"  " real" "      0" 
 Maximum for projection of the eigenvector on the average structure, max=0 gives the extremes

.BI "-nframes"  " int" " 2" 
 Number of frames for the extremes output

.BI "-[no]split"  "    no"
 Split eigenvector projections where time is zero

