.TH g_analyze 1 "Mon 29 Aug 2005"
.SH NAME
g_analyze
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_analyze\fP
.BI "-f" " graph.xvg "
.BI "-ac" " autocorr.xvg "
.BI "-msd" " msd.xvg "
.BI "-cc" " coscont.xvg "
.BI "-dist" " distr.xvg "
.BI "-av" " average.xvg "
.BI "-ee" " errest.xvg "
.BI "-g" " fitlog.log "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-[no]time" ""
.BI "-b" " real "
.BI "-e" " real "
.BI "-n" " int "
.BI "-[no]d" ""
.BI "-bw" " real "
.BI "-errbar" " enum "
.BI "-[no]integrate" ""
.BI "-aver_start" " real "
.BI "-[no]xydy" ""
.BI "-filter" " real "
.BI "-[no]power" ""
.BI "-[no]subav" ""
.BI "-[no]oneacf" ""
.BI "-acflen" " int "
.BI "-[no]normalize" ""
.BI "-P" " enum "
.BI "-fitfn" " enum "
.BI "-ncskip" " int "
.BI "-beginfit" " real "
.BI "-endfit" " real "
.SH DESCRIPTION
g_analyze reads an ascii file and analyzes data sets.
A line in the input file may start with a time
(see option 
.B -time
) and any number of y values may follow.
Multiple sets can also be
read when they are seperated by & (option 
.B -n
),
in this case only one y value is read from each line.
All lines starting with  and @ are skipped.
All analyses can also be done for the derivative of a set
(option 
.B -d
).


All options, except for 
.B -av
and 
.B -power
assume that the
points are equidistant in time.


g_analyze always shows the average and standard deviation of each
set. For each set it also shows the relative deviation of the third
and forth cumulant from those of a Gaussian distribution with the same
standard deviation.


Option 
.B -ac
produces the autocorrelation function(s).


Option 
.B -cc
plots the resemblance of set i with a cosine of
i/2 periods. The formula is:
2 (int0-T y(t) cos(pi t/i) dt)2 / int0-T y(t) y(t) dt

This is useful for principal components obtained from covariance
analysis, since the principal components of random diffusion are
pure cosines.


Option 
.B -msd
produces the mean square displacement(s).


Option 
.B -dist
produces distribution plot(s).


Option 
.B -av
produces the average over the sets.
Error bars can be added with the option 
.B -errbar
.
The errorbars can represent the standard deviation, the error
(assuming the points are independent) or the interval containing
90% of the points, by discarding 5% of the points at the top and
the bottom.


Option 
.B -ee
produces error estimates using block averaging.
A set is divided in a number of blocks and averages are calculated for
each block. The error for the total average is calculated from
the variance between averages of the m blocks B_i as follows:
error2 = Sum (B_i - B)2 / (m*(m-1)).
These errors are plotted as a function of the block size.
Also an analytical block average curve is plotted, assuming
that the autocorrelation is a sum of two exponentials.
The analytical curve for the block average is:

f(t) = sigma sqrt(2/T (  a   (tau1 ((exp(-t/tau1) - 1) tau1/t + 1)) +

                       (1-a) (tau2 ((exp(-t/tau2) - 1) tau2/t + 1)))),
where T is the total time.
a, tau1 and tau2 are obtained by fitting f2(t) to error2.
When the actual block average is very close to the analytical curve,
the error is sigma*sqrt(2/T (a tau1 + (1-a) tau2)).
The complete derivation is given in
B. Hess, J. Chem. Phys. 116:209-217, 2002.


Option 
.B -filter
prints the RMS high-frequency fluctuation
of each set and over all sets with respect to a filtered average.
The filter is proportional to cos(pi t/len) where t goes from -len/2
to len/2. len is supplied with the option 
.B -filter
.
This filter reduces oscillations with period len/2 and len by a factor
of 0.79 and 0.33 respectively.


Option 
.B -power
fits the data to b ta, which is accomplished
by fitting to a t + b on log-log scale. All points after the first
zero or negative value are ignored.
.SH FILES
.BI "-f" " graph.xvg" 
.B Input
 xvgr/xmgr file 

.BI "-ac" " autocorr.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-msd" " msd.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-cc" " coscont.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-dist" " distr.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-av" " average.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-ee" " errest.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-g" " fitlog.log" 
.B Output, Opt.
 Log file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-[no]time"  "   yes"
 Expect a time in the input

.BI "-b"  " real" "     -1" 
 First time to read from set

.BI "-e"  " real" "     -1" 
 Last time to read from set

.BI "-n"  " int" " 1" 
 Read  sets seperated by &

.BI "-[no]d"  "    no"
 Use the derivative

.BI "-bw"  " real" "    0.1" 
 Binwidth for the distribution

.BI "-errbar"  " enum" " none" 
 Error bars for -av: 
.B none
, 
.B stddev
, 
.B error
or 
.B 90


.BI "-[no]integrate"  "    no"
 Integrate data function(s) numerically using trapezium rule

.BI "-aver_start"  " real" "      0" 
 Start averaging the integral from here

.BI "-[no]xydy"  "    no"
 Interpret second data set as error in the y values for integrating

.BI "-filter"  " real" "      0" 
 Print the high-frequency fluctuation after filtering with a cosine filter of length 

.BI "-[no]power"  "    no"
 Fit data to: b ta

.BI "-[no]subav"  "   yes"
 Subtract the average before autocorrelating

.BI "-[no]oneacf"  "    no"
 Calculate one ACF over all sets

.BI "-acflen"  " int" " -1" 
 Length of the ACF, default is half the number of frames

.BI "-[no]normalize"  "   yes"
 Normalize ACF

.BI "-P"  " enum" " 0" 
 Order of Legendre polynomial for ACF (0 indicates none): 
.B 0
, 
.B 1
, 
.B 2
or 
.B 3


.BI "-fitfn"  " enum" " none" 
 Fit function: 
.B none
, 
.B exp
, 
.B aexp
, 
.B exp_exp
, 
.B vac
, 
.B exp5
, 
.B exp7
or 
.B exp9


.BI "-ncskip"  " int" " 0" 
 Skip N points in the output file of correlation functions

.BI "-beginfit"  " real" "      0" 
 Time where to begin the exponential fit of the correlation function

.BI "-endfit"  " real" "     -1" 
 Time where to end the exponential fit of the correlation function, -1 is till the end

