.TH g_anadock 1 "Fri 18 Jan 2013" "" "GROMACS suite, VERSION 4.5.6"
.SH NAME
g_anadock - cluster structures from Autodock runs

.B VERSION 4.5.6
.SH SYNOPSIS
\f3g_anadock\fP
.BI "\-f" " eiwit.pdb "
.BI "\-ox" " cluster.pdb "
.BI "\-od" " edocked.xvg "
.BI "\-of" " efree.xvg "
.BI "\-g" " anadock.log "
.BI "\-[no]h" ""
.BI "\-[no]version" ""
.BI "\-nice" " int "
.BI "\-xvg" " enum "
.BI "\-[no]free" ""
.BI "\-[no]rms" ""
.BI "\-cutoff" " real "
.SH DESCRIPTION
\&\fB g_anadock\fR analyses the results of an Autodock run and clusters the
\&structures together, based on distance or RMSD. The docked energy
\&and free energy estimates are analysed, and for each cluster the
\&energy statistics are printed.


\&An alternative approach to this is to cluster the structures first
\&using \fB g_cluster\fR and then sort the clusters on either lowest
\&energy or average energy.
.SH FILES
.BI "\-f" " eiwit.pdb" 
.B Input
 Protein data bank file 

.BI "\-ox" " cluster.pdb" 
.B Output
 Protein data bank file 

.BI "\-od" " edocked.xvg" 
.B Output
 xvgr/xmgr file 

.BI "\-of" " efree.xvg" 
.B Output
 xvgr/xmgr file 

.BI "\-g" " anadock.log" 
.B Output
 Log file 

.SH OTHER OPTIONS
.BI "\-[no]h"  "no    "
 Print help info and quit

.BI "\-[no]version"  "no    "
 Print version info and quit

.BI "\-nice"  " int" " 0" 
 Set the nicelevel

.BI "\-xvg"  " enum" " xmgrace" 
 xvg plot formatting: \fB xmgrace\fR, \fB xmgr\fR or \fB none\fR

.BI "\-[no]free"  "no    "
 Use Free energy estimate from autodock for sorting the classes

.BI "\-[no]rms"  "yes   "
 Cluster on RMS or distance

.BI "\-cutoff"  " real" " 0.2   " 
 Maximum RMSD/distance for belonging to the same cluster

.SH SEE ALSO
.BR gromacs(7)

More information about \fBGROMACS\fR is available at <\fIhttp://www.gromacs.org/\fR>.
