.TH g_bond 1 "Mon 29 Aug 2005"
.SH NAME
g_bond
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_bond\fP
.BI "-f" " traj.xtc "
.BI "-n" " index.ndx "
.BI "-s" " topol.tpr "
.BI "-o" " bonds.xvg "
.BI "-l" " bonds.log "
.BI "-d" " distance.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-blen" " real "
.BI "-tol" " real "
.BI "-[no]aver" ""
.BI "-[no]averdist" ""
.SH DESCRIPTION
g_bond makes a distribution of bond lengths. If all is well a
gaussian distribution should be made when using a harmonic potential.
bonds are read from a single group in the index file in order i1-j1
i2-j2 thru in-jn.



.B -tol
gives the half-width of the distribution as a fraction
of the bondlength (
.B -blen
). That means, for a bond of 0.2
a tol of 0.1 gives a distribution from 0.18 to 0.22.


Option 
.B -d
plots all the distances as a function of time.
This requires a structure file for the atom and residue names in
the output. If however the option 
.B -averdist
is given (as well
or separately) the average bond length is plotted instead.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-n" " index.ndx" 
.B Input
 Index file 

.BI "-s" " topol.tpr" 
.B Input, Opt.
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-o" " bonds.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-l" " bonds.log" 
.B Output, Opt.
 Log file 

.BI "-d" " distance.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-blen"  " real" "     -1" 
 Bond length. By default length of first bond

.BI "-tol"  " real" "    0.1" 
 Half width of distribution as fraction of blen

.BI "-[no]aver"  "   yes"
 Average bond length distributions

.BI "-[no]averdist"  "   yes"
 Average distances (turns on -d)

\- It should be possible to get bond information from the topology.

