.TH g_cluster 1 "Mon 29 Aug 2005"
.SH NAME
g_cluster
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_cluster\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-dm" " rmsd.xpm "
.BI "-o" " rmsd-clust.xpm "
.BI "-g" " cluster.log "
.BI "-dist" " rmsd-dist.xvg "
.BI "-ev" " rmsd-eig.xvg "
.BI "-sz" " clust-size.xvg "
.BI "-tr" " clust-trans.xpm "
.BI "-ntr" " clust-trans.xvg "
.BI "-clid" " clust-id.xvg "
.BI "-cl" " clusters.pdb "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-tu" " enum "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-[no]dista" ""
.BI "-nlevels" " int "
.BI "-cutoff" " real "
.BI "-[no]fit" ""
.BI "-max" " real "
.BI "-skip" " int "
.BI "-[no]av" ""
.BI "-wcl" " int "
.BI "-nst" " int "
.BI "-rmsmin" " real "
.BI "-method" " enum "
.BI "-minstruct" " int "
.BI "-[no]binary" ""
.BI "-M" " int "
.BI "-P" " int "
.BI "-seed" " int "
.BI "-niter" " int "
.BI "-kT" " real "
.SH DESCRIPTION
g_cluster can cluster structures with several different methods.
Distances between structures can be determined from a trajectory
or read from an XPM matrix file with the 
.B -dm
option.
RMS deviation after fitting or RMS deviation of atom-pair distances
can be used to define the distance between structures.


single linkage: add a structure to a cluster when its distance to any
element of the cluster is less than 
.B cutoff
.


Jarvis Patrick: add a structure to a cluster when this structure
and a structure in the cluster have each other as neighbors and
they have a least 
.B P
neighbors in common. The neighbors
of a structure are the M closest structures or all structures within

.B cutoff
.


Monte Carlo: reorder the RMSD matrix using Monte Carlo.


diagonalization: diagonalize the RMSD matrix.

gromos: use algorithm as described in Daura 
.I et al.

(
.I Angew. Chem. Int. Ed.

.B 1999
, 
.I 38
, pp 236-240).
Count number of neighbors using cut-off, take structure with
largest number of neighbors with all its neighbors as cluster
and eleminate it from the pool of clusters. Repeat for remaining
structures in pool.


When the clustering algorithm assigns each structure to exactly one
cluster (single linkage, Jarvis Patrick and gromos) and a trajectory
file is supplied, the structure with
the smallest average distance to the others or the average structure
or all structures for each cluster will be written to a trajectory
file. When writing all structures, separate numbered files are made
for each cluster.

Two output files are always written:


.B -o
writes the RMSD values in the upper left half of the matrix
and a graphical depiction of the clusters in the lower right half
When 
.B -minstruct
= 1 the graphical depiction is black
when two structures are in the same cluster.
When 
.B -minstruct
 1 different colors will be used for each
cluster.


.B -g
writes information on the options used and a detailed list
of all clusters and their members.


Additionally, a number of optional output files can be written:


.B -dist
writes the RMSD distribution.


.B -ev
writes the eigenvectors of the RMSD matrix
diagonalization.


.B -sz
writes the cluster sizes.


.B -tr
writes a matrix of the number transitions between
cluster pairs.


.B -ntr
writes the total number of transitions to or from
each cluster.


.B -clid
writes the cluster number as a function of time.


.B -cl
writes average (with option 
.B -av
) or central
structure of each cluster or writes numbered files with cluster members
for a selected set of clusters (with option 
.B -wcl
, depends on

.B -nst
and 
.B -rmsmin
).

.SH FILES
.BI "-f" " traj.xtc" 
.B Input, Opt.
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input, Opt.
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-dm" " rmsd.xpm" 
.B Input, Opt.
 X PixMap compatible matrix file 

.BI "-o" " rmsd-clust.xpm" 
.B Output
 X PixMap compatible matrix file 

.BI "-g" " cluster.log" 
.B Output
 Log file 

.BI "-dist" " rmsd-dist.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-ev" " rmsd-eig.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-sz" " clust-size.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-tr" " clust-trans.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.BI "-ntr" " clust-trans.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-clid" " clust-id.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-cl" " clusters.pdb" 
.B Output, Opt.
 Generic trajectory: xtc trr trj gro g96 pdb 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-tu"  " enum" " ps" 
 Time unit: 
.B ps
, 
.B fs
, 
.B ns
, 
.B us
, 
.B ms
, 
.B s
, 
.B m
or 
.B h


.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-[no]dista"  "    no"
 Use RMSD of distances instead of RMS deviation

.BI "-nlevels"  " int" " 40" 
 Discretize RMSD matrix in  levels

.BI "-cutoff"  " real" "    0.1" 
 RMSD cut-off (nm) for two structures to be neighbor

.BI "-[no]fit"  "   yes"
 Use least squares fitting before RMSD calculation

.BI "-max"  " real" "     -1" 
 Maximum level in RMSD matrix

.BI "-skip"  " int" " 1" 
 Only analyze every nr-th frame

.BI "-[no]av"  "    no"
 Write average iso middle structure for each cluster

.BI "-wcl"  " int" " 0" 
 Write all structures for first  clusters to numbered files

.BI "-nst"  " int" " 1" 
 Only write all structures if more than  per cluster

.BI "-rmsmin"  " real" "      0" 
 minimum rms difference with rest of cluster for writing structures

.BI "-method"  " enum" " linkage" 
 Method for cluster determination: 
.B linkage
, 
.B jarvis-patrick
, 
.B monte-carlo
, 
.B diagonalization
or 
.B gromos


.BI "-minstruct"  " int" " 1" 
 Minimum number of structures in cluster for coloring in the xpm file

.BI "-[no]binary"  "    no"
 Treat the RMSD matrix as consisting of 0 and 1, where the cut-off is given by -cutoff

.BI "-M"  " int" " 10" 
 Number of nearest neighbors considered for Jarvis-Patrick algorithm, 0 is use cutoff

.BI "-P"  " int" " 3" 
 Number of identical nearest neighbors required to form a cluster

.BI "-seed"  " int" " 1993" 
 Random number seed for Monte Carlo clustering algorithm

.BI "-niter"  " int" " 10000" 
 Number of iterations for MC

.BI "-kT"  " real" "  0.001" 
 Boltzmann weighting factor for Monte Carlo optimization (zero turns off uphill steps)

