.TH g_covar 1 "Mon 29 Aug 2005"
.SH NAME
g_covar
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_covar\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-o" " eigenval.xvg "
.BI "-v" " eigenvec.trr "
.BI "-av" " average.pdb "
.BI "-l" " covar.log "
.BI "-ascii" " covar.dat "
.BI "-xpm" " covar.xpm "
.BI "-xpma" " covara.xpm "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-tu" " enum "
.BI "-[no]xvgr" ""
.BI "-[no]fit" ""
.BI "-[no]ref" ""
.BI "-[no]mwa" ""
.BI "-last" " int "
.BI "-[no]pbc" ""
.SH DESCRIPTION

.B g_covar
calculates and diagonalizes the (mass-weighted)
covariance matrix.
All structures are fitted to the structure in the structure file.
When this is not a run input file periodicity will not be taken into
account. When the fit and analysis groups are identical and the analysis
is non mass-weighted, the fit will also be non mass-weighted.



The eigenvectors are written to a trajectory file (
.B -v
).
When the same atoms are used for the fit and the covariance analysis,
the reference structure for the fit is written first with t=-1.
The average (or reference when 
.B -ref
is used) structure is
written with t=0, the eigenvectors
are written as frames with the eigenvector number as timestamp.



The eigenvectors can be analyzed with 
.B g_anaeig
.



Option 
.B -ascii
writes the whole covariance matrix to
an ASCII file. The order of the elements is: x1x1, x1y1, x1z1, x1x2, ...



Option 
.B -xpm
writes the whole covariance matrix to an xpm file.



Option 
.B -xpma
writes the atomic covariance matrix to an xpm file,
i.e. for each atom pair the sum of the xx, yy and zz covariances is
written.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-o" " eigenval.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-v" " eigenvec.trr" 
.B Output
 Full precision trajectory: trr trj 

.BI "-av" " average.pdb" 
.B Output
 Generic structure: gro g96 pdb xml 

.BI "-l" " covar.log" 
.B Output
 Log file 

.BI "-ascii" " covar.dat" 
.B Output, Opt.
 Generic data file 

.BI "-xpm" " covar.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.BI "-xpma" " covara.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-tu"  " enum" " ps" 
 Time unit: 
.B ps
, 
.B fs
, 
.B ns
, 
.B us
, 
.B ms
, 
.B s
, 
.B m
or 
.B h


.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-[no]fit"  "   yes"
 Fit to a reference structure

.BI "-[no]ref"  "    no"
 Use the deviation from the conformation in the structure file instead of from the average

.BI "-[no]mwa"  "    no"
 Mass-weighted covariance analysis

.BI "-last"  " int" " -1" 
 Last eigenvector to write away (-1 is till the last)

.BI "-[no]pbc"  "   yes"
 Apply corrections for periodic boundary conditions

