.TH g_confrms 1 "Mon 29 Aug 2005"
.SH NAME
g_confrms
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_confrms\fP
.BI "-f1" " conf1.gro "
.BI "-f2" " conf2.gro "
.BI "-o" " fit.pdb "
.BI "-n1" " fit1.ndx "
.BI "-n2" " fit2.ndx "
.BI "-no" " match.ndx "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-[no]w" ""
.BI "-[no]one" ""
.BI "-[no]mw" ""
.BI "-[no]pbc" ""
.BI "-[no]fit" ""
.BI "-[no]name" ""
.BI "-[no]bfac" ""
.SH DESCRIPTION
g_confrms computes the root mean square deviation (RMSD) of two
structures after LSQ fitting the second structure on the first one.
The two structures do NOT need to have the same number of atoms,
only the two index groups used for the fit need to be identical.
With 
.B -name
only matching atom names from the selected groups
will be used for the fit and RMSD calculation. This can be useful 
when comparing mutants of a protein.


The superimposed structures are written to file. In a 
.B .pdb
file
the two structures will be written as separate models
(use 
.B rasmol -nmrpdb
). Also in a 
.B .pdb
file, B-factors
calculated from the atomic MSD values can be written with 
.B -bfac
.
.SH FILES
.BI "-f1" " conf1.gro" 
.B Input
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-f2" " conf2.gro" 
.B Input
 Generic structure: gro g96 pdb tpr tpb tpa xml 

.BI "-o" " fit.pdb" 
.B Output
 Generic structure: gro g96 pdb xml 

.BI "-n1" " fit1.ndx" 
.B Input, Opt.
 Index file 

.BI "-n2" " fit2.ndx" 
.B Input, Opt.
 Index file 

.BI "-no" " match.ndx" 
.B Output, Opt.
 Index file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]one"  "    no"
 Only write the fitted structure to file

.BI "-[no]mw"  "   yes"
 Mass-weighted fitting and RMSD

.BI "-[no]pbc"  "    no"
 Try to make molecules whole again

.BI "-[no]fit"  "   yes"
 Do least squares superposition of the target structure to the reference

.BI "-[no]name"  "    no"
 Only compare matching atom names

.BI "-[no]bfac"  "    no"
 Output B-factors from atomic MSD values

