.TH g_confrms 1 "Thu 28 Feb 2002"
.SH NAME
g_confrms
.B VERSION 3.1
.SH SYNOPSIS
\f3g_confrms\fP
.BI "-f1" " conf1.gro "
.BI "-f2" " conf2.gro "
.BI "-o" " fit.pdb "
.BI "-n1" " fit1.ndx "
.BI "-n2" " fit2.ndx "
.BI "-[no]h" ""
.BI "-[no]X" ""
.BI "-nice" " int "
.BI "-[no]one" ""
.BI "-[no]pbc" ""
.SH DESCRIPTION
g_confrms computes the root mean square deviation (RMSD) of two
structures after LSQ fitting the second structure on the first one.
The two structures do NOT need to have the same number of atoms,
only the two index groups used for the fit need to be identical.



The superimposed structures are written to file. In a 
.B .pdb
file
the two structures will be written as separate models
(use 
.B rasmol -nmrpdb
).
.SH FILES
.BI "-f1" " conf1.gro" 
.B Input
 Structure+mass(db): tpr tpb tpa gro g96 pdb 

.BI "-f2" " conf2.gro" 
.B Input
 Generic structure: gro g96 pdb tpr tpb tpa 

.BI "-o" " fit.pdb" 
.B Output
 Generic structure: gro g96 pdb 

.BI "-n1" " fit1.ndx" 
.B Input, Opt.
 Index file 

.BI "-n2" " fit2.ndx" 
.B Input, Opt.
 Index file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-[no]X"  "    no"
 Use dialog box GUI to edit command line options

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-[no]one"  "    no"
 Only write the fitted structure to file

.BI "-[no]pbc"  "    no"
 Try to make molecules whole again

