.TH g_densmap 1 "Mon 22 Sep 2008"
.SH NAME
g_densmap
.B VERSION 4.0_rc1
.SH SYNOPSIS
\f3g_densmap\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-o" " densmap.xpm "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-bin" " real "
.BI "-aver" " enum "
.BI "-xmin" " real "
.BI "-xmax" " real "
.BI "-n1" " int "
.BI "-n2" " int "
.BI "-amax" " real "
.BI "-rmax" " real "
.BI "-[no]mirror" ""
.BI "-unit" " enum "
.BI "-dmin" " real "
.BI "-dmax" " real "
.SH DESCRIPTION
g_densmap computes 2D number-density maps.
It can make planar and axial-radial density maps.
The output 
.B .xpm
file can be visualized with for instance xv
and can be converted to postscript with xpm2ps.



The default analysis is a 2-D number-density map for a selected
group of atoms in the x-y plane.
The averaging direction can be changed with the option 
.B -aver
.
When 
.B -xmin
and/or 
.B -xmax
are set only atoms that are
within the limit(s) in the averaging direction are taken into account.
The grid spacing is set with the option 
.B -bin
.
When 
.B -n1
or 
.B -n2
is non-zero, the grid
size is set by this option.
Box size fluctuations are properly taken into account.



When options 
.B -amax
and 
.B -rmax
are set, an axial-radial
number-density map is made. Three groups should be supplied, the centers
of mass of the first two groups define the axis, the third defines the
analysis group. The axial direction goes from -amax to +amax, where
the center is defined as the midpoint between the centers of mass and
the positive direction goes from the first to the second center of mass.
The radial direction goes from 0 to rmax or from -rmax to +rmax
when the 
.B -mirror
option has been set.



The normalization of the output is set with the 
.B -unit
option.
The default produces a true number density. Unit 
.B nm-2
leaves out
the normalization for the averaging or the angular direction.
Option 
.B count
produces the count for each grid cell.
When you do not want the scale in the output to go
from zero to the maximum density, you can set the maximum
with the option 
.B -dmax
.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Trajectory: xtc trr trj gro g96 pdb cpt 

.BI "-s" " topol.tpr" 
.B Input, Opt.
 Structure+mass(db): tpr tpb tpa gro g96 pdb 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-o" " densmap.xpm" 
.B Output
 X PixMap compatible matrix file 

.SH OTHER OPTIONS
.BI "-[no]h"  "no    "
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" " 0     " 
 First frame (ps) to read from trajectory

.BI "-e"  " time" " 0     " 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" " 0     " 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "no    "
 View output xvg, xpm, eps and pdb files

.BI "-bin"  " real" " 0.02  " 
 Grid size (nm)

.BI "-aver"  " enum" " z" 
 The direction to average over: 
.B z
, 
.B y
or 
.B x


.BI "-xmin"  " real" " -1    " 
 Minimum coordinate for averaging

.BI "-xmax"  " real" " -1    " 
 Maximum coordinate for averaging

.BI "-n1"  " int" " 0" 
 Number of grid cells in the first direction

.BI "-n2"  " int" " 0" 
 Number of grid cells in the second direction

.BI "-amax"  " real" " 0     " 
 Maximum axial distance from the center

.BI "-rmax"  " real" " 0     " 
 Maximum radial distance

.BI "-[no]mirror"  "no    "
 Add the mirror image below the axial axis

.BI "-unit"  " enum" " nm-3" 
 Unit for the output: 
.B nm-3
, 
.B nm-2
or 
.B count


.BI "-dmin"  " real" " 0     " 
 Minimum density in output

.BI "-dmax"  " real" " 0     " 
 Maximum density in output (0 means calculate it)

