.TH g_density 1 "Mon 29 Aug 2005"
.SH NAME
g_density
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_density\fP
.BI "-f" " traj.xtc "
.BI "-n" " index.ndx "
.BI "-s" " topol.tpr "
.BI "-ei" " electrons.dat "
.BI "-o" " density.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-d" " string "
.BI "-sl" " int "
.BI "-[no]number" ""
.BI "-[no]ed" ""
.BI "-[no]count" ""
.BI "-ng" " int "
.BI "-[no]symm" ""
.BI "-[no]center" ""
.SH DESCRIPTION
Compute partial densities across the box, using an index file. Densities
in kg/m3, number densities or electron densities can be
calculated. For electron densities, a file describing the number of
electrons for each type of atom should be provided using 
.B -ei
.
It should look like:

   2

   atomname = nrelectrons

   atomname = nrelectrons

The first line contains the number of lines to read from the file.
There should be one line for each unique atom name in your system.
The number of electrons for each atom is modified by its atomic
partial charge.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-s" " topol.tpr" 
.B Input
 Generic run input: tpr tpb tpa xml 

.BI "-ei" " electrons.dat" 
.B Input, Opt.
 Generic data file 

.BI "-o" " density.xvg" 
.B Output
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-d"  " string" " Z" 
 Take the normal on the membrane in direction X, Y or Z.

.BI "-sl"  " int" " 10" 
 Divide the box in nr slices.

.BI "-[no]number"  "    no"
 Calculate number density instead of mass density. Hydrogens are not counted!

.BI "-[no]ed"  "    no"
 Calculate electron density instead of mass density

.BI "-[no]count"  "    no"
 Only count atoms in slices, no densities. Hydrogens are not counted

.BI "-ng"  " int" " 0" 
 Number of groups to compute densities of

.BI "-[no]symm"  "    no"
 Symmetrize the density along the axis, with respect to the center. Useful for bilayers.

.BI "-[no]center"  "    no"
 Shift the center of mass along the axis to zero. This means if your axis is Z and your box is bX, bY, bZ, the center of mass will be at bX/2, bY/2, 0.

\- When calculating electron densities, atomnames are used instead of types. This is bad.

\- When calculating number densities, atoms with names that start with H are not counted. This may be surprising if you use hydrogens with names like OP3.

