.TH g_disre 1 "Mon 29 Aug 2005"
.SH NAME
g_disre
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_disre\fP
.BI "-s" " topol.tpr "
.BI "-f" " traj.xtc "
.BI "-ds" " drsum.xvg "
.BI "-da" " draver.xvg "
.BI "-dn" " drnum.xvg "
.BI "-dm" " drmax.xvg "
.BI "-dr" " restr.xvg "
.BI "-l" " disres.log "
.BI "-n" " viol.ndx "
.BI "-q" " viol.pdb "
.BI "-c" " clust.ndx "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-ntop" " int "
.SH DESCRIPTION
g_disre computes violations of distance restraints.
If necessary all protons can be added to a protein molecule 
using the protonate program.


The program allways
computes the instantaneous violations rather than time-averaged,
because this analysis is done from a trajectory file afterwards
it does not make sense to use time averaging. However,
the time averaged values per restraint are given in the log file.


An index file may be used to select specific restraints for
printing.


When the optional
.B -q
flag is given a pdb file coloured by the
amount of average violations.


When the 
.B -c
option is given, an index file will be read
containing the frames in your trajectory corresponding to the clusters
(defined in another manner) that you want to analyze. For these clusters
the program will compute average violations using the thisd power
averaging algorithm and print them in the log file.
.SH FILES
.BI "-s" " topol.tpr" 
.B Input
 Generic run input: tpr tpb tpa xml 

.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-ds" " drsum.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-da" " draver.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-dn" " drnum.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-dm" " drmax.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-dr" " restr.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-l" " disres.log" 
.B Output
 Log file 

.BI "-n" " viol.ndx" 
.B Input, Opt.
 Index file 

.BI "-q" " viol.pdb" 
.B Output, Opt.
 Protein data bank file 

.BI "-c" " clust.ndx" 
.B Input, Opt.
 Index file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-ntop"  " int" " 0" 
 Number of large violations that are stored in the log file every step

