.TH g_dih 1 "Mon 29 Aug 2005"
.SH NAME
g_dih
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_dih\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-o" " hello.out "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]sa" ""
.BI "-mult" " int "
.SH DESCRIPTION
g_dih can do two things. The default is to analyze dihedral transitions
by merely computing all the dihedral angles defined in your topology
for the whole trajectory. When a dihedral flips over to another minimum
an angle/time plot is made.


The opther option is to discretize the dihedral space into a number of
bins, and group each conformation in dihedral space in the
appropriate bin. The output is then given as a number of dihedral
conformations sorted according to occupancy.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input
 Generic run input: tpr tpb tpa xml 

.BI "-o" " hello.out" 
.B Output
 Generic output file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]sa"  "    no"
 Perform cluster analysis in dihedral space instead of analysing dihedral transitions.

.BI "-mult"  " int" " -1" 
 mulitiplicity for dihedral angles (by default read from topology)

