.TH g_dipoles 1 "Mon 29 Aug 2005"
.SH NAME
g_dipoles
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_dipoles\fP
.BI "-enx" " ener.edr "
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-o" " Mtot.xvg "
.BI "-eps" " epsilon.xvg "
.BI "-a" " aver.xvg "
.BI "-d" " dipdist.xvg "
.BI "-c" " dipcorr.xvg "
.BI "-g" " gkr.xvg "
.BI "-adip" " adip.xvg "
.BI "-dip3d" " dip3d.xvg "
.BI "-cos" " cosaver.xvg "
.BI "-q" " quadrupole.xvg "
.BI "-slab" " slab.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-mu" " real "
.BI "-mumax" " real "
.BI "-epsilonRF" " real "
.BI "-skip" " int "
.BI "-temp" " real "
.BI "-[no]avercorr" ""
.BI "-[no]pairs" ""
.BI "-axis" " string "
.BI "-sl" " int "
.BI "-gkratom" " int "
.BI "-acflen" " int "
.BI "-[no]normalize" ""
.BI "-P" " enum "
.BI "-fitfn" " enum "
.BI "-ncskip" " int "
.BI "-beginfit" " real "
.BI "-endfit" " real "
.SH DESCRIPTION
g_dipoles computes the total dipole plus fluctuations of a simulation
system. From this you can compute e.g. the dielectric constant for
low dielectric media


The file Mtot.xvg contains the total dipole moment of a frame, the
components as well as the norm of the vector.
The file aver.xvg contains  |Mu|2  and  |Mu| 2 during the
simulation.
The file dipdist.xvg contains the distribution of dipole moments during
the simulation
The mu_max is used as the highest value in the distribution graph.


Furthermore the dipole autocorrelation function will be computed, when
option -c is used. It can be averaged over all molecules, 
or (with option -avercorr) it can be computed as the autocorrelation
of the total dipole moment of the simulation box.


At the moment the dielectric constant is calculated only correct if
a rectangular or cubic simulation box is used.


Option 
.B -g
produces a plot of the distance dependent Kirkwood
G-factor, as well as the average cosine of the angle between the dipoles
as a function of the distance. The plot also includes gOO and hOO
according to Nymand & Linse, JCP 112 (2000) pp 6386-6395. In the same plot
we also include the energy per scale computed by taking the inner product of
the dipoles divided by the distance to the third power.





EXAMPLES


g_dipoles -P1 -n mols -o dip_sqr -mu 2.273 -mumax 5.0
-nofft


This will calculate the autocorrelation function of the molecular
dipoles using a first order Legendre polynomial of the angle of the
dipole vector and itself a time t later. For this calculation 1001
frames will be used. Further the dielectric constant will be calculated
using an epsilonRF of infinity (default), temperature of 300 K (default) and
an average dipole moment of the molecule of 2.273 (SPC). For the
distribution function a maximum of 5.0 will be used.
.SH FILES
.BI "-enx" " ener.edr" 
.B Input, Opt.
 Generic energy: edr ene 

.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input
 Generic run input: tpr tpb tpa xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-o" " Mtot.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-eps" " epsilon.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-a" " aver.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-d" " dipdist.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-c" " dipcorr.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-g" " gkr.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-adip" " adip.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-dip3d" " dip3d.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-cos" " cosaver.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-q" " quadrupole.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-slab" " slab.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-mu"  " real" "     -1" 
 dipole of a single molecule (in Debye)

.BI "-mumax"  " real" "      5" 
 max dipole in Debye (for histrogram)

.BI "-epsilonRF"  " real" "      0" 
 epsilon of the reaction field used during the simulation, needed for dieclectric constant calculation. WARNING: 0.0 means infinity (default)

.BI "-skip"  " int" " 0" 
 Skip steps in the output (but not in the computations)

.BI "-temp"  " real" "    300" 
 average temperature of the simulation (needed for dielectric constant calculation)

.BI "-[no]avercorr"  "    no"
 calculate AC function of average dipole moment of the simulation box rather than average of AC function per molecule

.BI "-[no]pairs"  "   yes"
 Calculate |cos theta| between all pairs of molecules. May be slow

.BI "-axis"  " string" " Z" 
 Take the normal on the computational box in direction X, Y or Z.

.BI "-sl"  " int" " 10" 
 Divide the box in nr slices.

.BI "-gkratom"  " int" " 0" 
 Use the n-th atom of a molecule (starting from 1) to calculate the distance between molecules rather than the center of charge (when 0) in the calculation of distance dependent Kirkwood factors

.BI "-acflen"  " int" " -1" 
 Length of the ACF, default is half the number of frames

.BI "-[no]normalize"  "   yes"
 Normalize ACF

.BI "-P"  " enum" " 0" 
 Order of Legendre polynomial for ACF (0 indicates none): 
.B 0
, 
.B 1
, 
.B 2
or 
.B 3


.BI "-fitfn"  " enum" " none" 
 Fit function: 
.B none
, 
.B exp
, 
.B aexp
, 
.B exp_exp
, 
.B vac
, 
.B exp5
, 
.B exp7
or 
.B exp9


.BI "-ncskip"  " int" " 0" 
 Skip N points in the output file of correlation functions

.BI "-beginfit"  " real" "      0" 
 Time where to begin the exponential fit of the correlation function

.BI "-endfit"  " real" "     -1" 
 Time where to end the exponential fit of the correlation function, -1 is till the end

