.TH g_dyndom 1 "Mon 29 Aug 2005"
.SH NAME
g_dyndom
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_dyndom\fP
.BI "-f" " dyndom.pdb "
.BI "-o" " rotated.xtc "
.BI "-n" " domains.ndx "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-firstangle" " real "
.BI "-lastangle" " real "
.BI "-nframe" " int "
.BI "-maxangle" " real "
.BI "-trans" " real "
.BI "-head" " vector "
.BI "-tail" " vector "
.SH DESCRIPTION
g_dyndom reads a pdb file output from DynDom
http://md.chem.rug.nl/~steve/DynDom/dyndom.home.html
It reads the coordinates, and the coordinates of the rotation axis
furthermore it reads an index file containing the domains.
Furthermore it takes the first and last atom of the arrow file
as command line arguments (head and tail) and
finally it takes the translation vector (given in DynDom info file)
and the angle of rotation (also as command line arguments). If the angle
determined by DynDom is given, one should be able to recover the
second structure used for generating the DynDom output.
Because of limited numerical accuracy this should be verified by
computing an all-atom RMSD (using 
.B g_confrms
) rather than by file
comparison (using diff).


The purpose of this program is to interpolate and extrapolate the
rotation as found by DynDom. As a result unphysical structures with
long or short bonds, or overlapping atoms may be produced. Visual
inspection, and energy minimization may be necessary to
validate the structure.
.SH FILES
.BI "-f" " dyndom.pdb" 
.B Input
 Protein data bank file 

.BI "-o" " rotated.xtc" 
.B Output
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-n" " domains.ndx" 
.B Input
 Index file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-firstangle"  " real" "      0" 
 Angle of rotation about rotation vector

.BI "-lastangle"  " real" "      0" 
 Angle of rotation about rotation vector

.BI "-nframe"  " int" " 11" 
 Number of steps on the pathway

.BI "-maxangle"  " real" "      0" 
 DymDom dtermined angle of rotation about rotation vector

.BI "-trans"  " real" "      0" 
 Translation (Aangstroem) along rotation vector (see DynDom info file)

.BI "-head"  " vector" " 0 0 0" 
 First atom of the arrow vector

.BI "-tail"  " vector" " 0 0 0" 
 Last atom of the arrow vector

