.TH g_enemat 1 "Mon 29 Aug 2005"
.SH NAME
g_enemat
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_enemat\fP
.BI "-f" " ener.edr "
.BI "-groups" " groups.dat "
.BI "-eref" " eref.dat "
.BI "-emat" " emat.xpm "
.BI "-etot" " energy.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-[no]sum" ""
.BI "-skip" " int "
.BI "-[no]mean" ""
.BI "-nlevels" " int "
.BI "-max" " real "
.BI "-min" " real "
.BI "-[no]coul" ""
.BI "-[no]coulr" ""
.BI "-[no]coul14" ""
.BI "-[no]lj" ""
.BI "-[no]lj" ""
.BI "-[no]lj14" ""
.BI "-[no]bhamsr" ""
.BI "-[no]bhamlr" ""
.BI "-[no]free" ""
.BI "-temp" " real "
.SH DESCRIPTION
g_enemat extracts an energy matrix from the energy file (
.B -f
).
With 
.B -groups
a file must be supplied with on each
line a group of atoms to be used. For these groups matrix of
interaction energies will be extracted from the energy file
by looking for energy groups with names corresponding to pairs
of groups of atoms. E.g. if your 
.B -groups
file contains:


.B 2



.B Protein



.B SOL


then energy groups with names like 'Coul-SR:Protein-SOL' and 
'LJ:Protein-SOL' are expected in the energy file (although

.B g_enemat
is most useful if many groups are analyzed
simultaneously). Matrices for different energy types are written
out separately, as controlled by the

.B -[no]coul
, 
.B -[no]coulr
, 
.B -[no]coul14
, 

.B -[no]lj
, 
.B -[no]lj14
, 

.B -[no]bham
and 
.B -[no]free
options.
Finally, the total interaction energy energy per group can be 
calculated (
.B -etot
).


An approximation of the free energy can be calculated using:
E(free) = E0 + kT log( exp((E-E0)/kT) ), where ''
stands for time-average. A file with reference free energies
can be supplied to calculate the free energy difference
with some reference state. Group names (e.g. residue names)
in the reference file should correspond to the group names
as used in the 
.B -groups
file, but a appended number
(e.g. residue number) in the 
.B -groups
will be ignored
in the comparison.
.SH FILES
.BI "-f" " ener.edr" 
.B Input, Opt.
 Generic energy: edr ene 

.BI "-groups" " groups.dat" 
.B Input
 Generic data file 

.BI "-eref" " eref.dat" 
.B Input, Opt.
 Generic data file 

.BI "-emat" " emat.xpm" 
.B Output
 X PixMap compatible matrix file 

.BI "-etot" " energy.xvg" 
.B Output
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-[no]sum"  "    no"
 Sum the energy terms selected rather than display them all

.BI "-skip"  " int" " 0" 
 Skip number of frames between data points

.BI "-[no]mean"  "   yes"
 with -groups extracts matrix of mean energies in stead of matrix for each timestep

.BI "-nlevels"  " int" " 20" 
 number of levels for matrix colors

.BI "-max"  " real" "  1e+20" 
 max value for energies

.BI "-min"  " real" " -1e+20" 
 min value for energies

.BI "-[no]coul"  "   yes"
 extract Coulomb SR energies

.BI "-[no]coulr"  "    no"
 extract Coulomb LR energies

.BI "-[no]coul14"  "    no"
 extract Coulomb 1-4 energies

.BI "-[no]lj"  "   yes"
 extract Lennard-Jones SR energies

.BI "-[no]lj"  "    no"
 extract Lennard-Jones LR energies

.BI "-[no]lj14"  "    no"
 extract Lennard-Jones 1-4 energies

.BI "-[no]bhamsr"  "    no"
 extract Buckingham SR energies

.BI "-[no]bhamlr"  "    no"
 extract Buckingham LR energies

.BI "-[no]free"  "   yes"
 calculate free energy

.BI "-temp"  " real" "    300" 
 reference temperature for free energy calculation

