.TH g_filter 1 "Mon 29 Aug 2005"
.SH NAME
g_filter
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_filter\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-ol" " lowpass.xtc "
.BI "-oh" " highpass.xtc "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-nf" " int "
.BI "-[no]all" ""
.BI "-[no]nojump" ""
.BI "-[no]fit" ""
.SH DESCRIPTION
g_filter performs frequency filtering on a trajectory.
The filter shape is cos(pi t/A) + 1 from -A to +A, where A is given
by the option 
.B -nf
times the time step in the input trajectory.
This filter reduces fluctuations with period A by 85%, with period
2*A by 50% and with period 3*A by 17% for low-pass filtering.
Both a low-pass and high-pass filtered trajectory can be written.


Option 
.B -ol
writes a low-pass filtered trajectory.
A frame is written every 
.B nf
input frames.
This ratio of filter length and output interval ensures a good
suppression of aliasing of high-frequency motion, which is useful for
making smooth movies. Also averages of properties which are linear
in the coordinates are preserved, since all input frames are weighted
equally in the output.
When all frames are needed, use the 
.B -all
option.


Option 
.B -oh
writes a high-pass filtered trajectory.
The high-pass filtered coordinates are added to the coordinates
from the structure file. When using high-pass filtering use 
.B -fit

or make sure you use a trajectory which has been fitted on
the coordinates in the structure file.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input, Opt.
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-ol" " lowpass.xtc" 
.B Output, Opt.
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-oh" " highpass.xtc" 
.B Output, Opt.
 Generic trajectory: xtc trr trj gro g96 pdb 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-nf"  " int" " 10" 
 Sets the filter length as well as the output interval for low-pass filtering

.BI "-[no]all"  "    no"
 Write all low-pass filtered frames

.BI "-[no]nojump"  "   yes"
 Remove jumps of atoms across the box

.BI "-[no]fit"  "    no"
 Fit all frames to a reference structure

