.TH g_lie 1 "Mon 29 Aug 2005"
.SH NAME
g_lie
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_lie\fP
.BI "-f" " ener.edr "
.BI "-o" " lie.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-Elj" " real "
.BI "-Eqq" " real "
.BI "-Clj" " real "
.BI "-Cqq" " real "
.BI "-ligand" " string "
.SH DESCRIPTION
g_lie computes a free energy estimate based on an energy analysis
from. One needs an energy file with the following components:
Coul (A-B) LJ-SR (A-B) etc.
.SH FILES
.BI "-f" " ener.edr" 
.B Input
 Generic energy: edr ene 

.BI "-o" " lie.xvg" 
.B Output
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-Elj"  " real" "      0" 
 Lennard-Jones interaction between ligand and solvent

.BI "-Eqq"  " real" "      0" 
 Coulomb interaction between ligand and solvent

.BI "-Clj"  " real" "  0.181" 
 Factor in the LIE equation for Lennard-Jones component of energy

.BI "-Cqq"  " real" "    0.5" 
 Factor in the LIE equation for Coulomb component of energy

.BI "-ligand"  " string" " none" 
 Name of the ligand in the energy file

