.TH g_mindist 1 "Mon 29 Aug 2005"
.SH NAME
g_mindist
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_mindist\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-od" " mindist.xvg "
.BI "-on" " numcont.xvg "
.BI "-o" " atm-pair.out "
.BI "-ox" " mindist.xtc "
.BI "-or" " mindistres.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-tu" " enum "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-[no]matrix" ""
.BI "-[no]max" ""
.BI "-d" " real "
.BI "-[no]pi" ""
.BI "-[no]split" ""
.BI "-ng" " int "
.SH DESCRIPTION
g_mindist computes the distance between one group and a number of
other groups. Both the minimum distance
(between any pair of atoms from the respective groups)
and the number of contacts within a given
distance are written to two separate output files.
With 
.B -or
, minimum distances to each residue in the first
group are determined and plotted as a function of reisdue number.


With option 
.B -pi
the minimum distance of a group to its
periodic image is plotted. This is useful for checking if a protein
has seen its periodic image during a simulation. Only one shift in
each direction is considered, giving a total of 26 shifts.
It also plots the maximum distance within the group and the lengths
of the three box vectors.


Other programs that calculate distances are 
.B g_dist

and 
.B g_bond
.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input, Opt.
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-od" " mindist.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-on" " numcont.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-o" " atm-pair.out" 
.B Output, Opt.
 Generic output file 

.BI "-ox" " mindist.xtc" 
.B Output, Opt.
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-or" " mindistres.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-tu"  " enum" " ps" 
 Time unit: 
.B ps
, 
.B fs
, 
.B ns
, 
.B us
, 
.B ms
, 
.B s
, 
.B m
or 
.B h


.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-[no]matrix"  "    no"
 Calculate half a matrix of group-group distances

.BI "-[no]max"  "    no"
 Calculate *maximum* distance instead of minimum

.BI "-d"  " real" "    0.6" 
 Distance for contacts

.BI "-[no]pi"  "    no"
 Calculate minimum distance with periodic images

.BI "-[no]split"  "    no"
 Split graph where time is zero

.BI "-ng"  " int" " 1" 
 Number of secondary groups to compute distance to a central group

