.TH g_morph 1 "Mon 29 Aug 2005"
.SH NAME
g_morph
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_morph\fP
.BI "-f1" " conf1.gro "
.BI "-f2" " conf2.gro "
.BI "-o" " interm.xtc "
.BI "-or" " rms-interm.xvg "
.BI "-n" " index.ndx "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-ninterm" " int "
.BI "-first" " real "
.BI "-last" " real "
.BI "-[no]fit" ""
.SH DESCRIPTION
g_morph does a linear interpolation of conformations in order to
create intermediates. Of course these are completely unphysical, but
that you may try to justify yourself. Output is in the form of a 
generic trajectory. The number of intermediates can be controlled with
the -ninterm flag. The first and last flag correspond to the way of
interpolating: 0 corresponds to input structure 1 while
1 corresponds to input strucutre 2.
If you specify first  0 or last  1 extrapolation will be
on the path from input structure x1 to x2. In general the coordinates
of the intermediate x(i) out of N total intermidates correspond to:


x(i) = x1 + (first+(i/(N-1))*(last-first))*(x2-x1)


Finally the RMSD with respect to both input structures can be computed
if explicitly selected (-or option). In that case an index file may be
read to select what group RMS is computed from.
.SH FILES
.BI "-f1" " conf1.gro" 
.B Input
 Generic structure: gro g96 pdb tpr tpb tpa xml 

.BI "-f2" " conf2.gro" 
.B Input
 Generic structure: gro g96 pdb tpr tpb tpa xml 

.BI "-o" " interm.xtc" 
.B Output
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-or" " rms-interm.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-ninterm"  " int" " 11" 
 Number of intermediates

.BI "-first"  " real" "      0" 
 Corresponds to first generated structure (0 is input x0, see above)

.BI "-last"  " real" "      1" 
 Corresponds to last generated structure (1 is input x1, see above)

.BI "-[no]fit"  "   yes"
 Do a least squares fit of the second to the first structure before interpolating

