.TH g_nmens 1 "Mon 29 Aug 2005"
.SH NAME
g_nmens
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_nmens\fP
.BI "-v" " eigenvec.trr "
.BI "-e" " eigenval.xvg "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-o" " ensemble.xtc "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-[no]xvgr" ""
.BI "-temp" " real "
.BI "-seed" " int "
.BI "-num" " int "
.BI "-first" " int "
.BI "-last" " int "
.SH DESCRIPTION

.B g_nmens
generates an ensemble around an average structure
in a subspace which is defined by a set of normal modes (eigenvectors).
The eigenvectors are assumed to be mass-weighted.
The position along each eigenvector is randomly taken from a Gaussian
distribution with variance kT/eigenvalue.


By default the starting eigenvector is set to 7, since the first six
normal modes are the translational and rotational degrees of freedom.
.SH FILES
.BI "-v" " eigenvec.trr" 
.B Input
 Full precision trajectory: trr trj 

.BI "-e" " eigenval.xvg" 
.B Input
 xvgr/xmgr file 

.BI "-s" " topol.tpr" 
.B Input
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-o" " ensemble.xtc" 
.B Output
 Generic trajectory: xtc trr trj gro g96 pdb 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-temp"  " real" "    300" 
 Temperature in Kelvin

.BI "-seed"  " int" " -1" 
 Random seed, -1 generates a seed from time and pid

.BI "-num"  " int" " 100" 
 Number of structures to generate

.BI "-first"  " int" " 7" 
 First eigenvector to use (-1 is select)

.BI "-last"  " int" " -1" 
 Last eigenvector to use (-1 is till the last)

