.TH g_potential 1 "Mon 29 Aug 2005"
.SH NAME
g_potential
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_potential\fP
.BI "-f" " traj.xtc "
.BI "-n" " index.ndx "
.BI "-s" " topol.tpr "
.BI "-o" " potential.xvg "
.BI "-oc" " charge.xvg "
.BI "-of" " field.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-d" " string "
.BI "-sl" " int "
.BI "-cb" " int "
.BI "-ce" " int "
.BI "-tz" " real "
.BI "-[no]spherical" ""
.BI "-ng" " int "
.SH DESCRIPTION
Compute the electrostatical potential across the box. The potential iscalculated by first summing the charges per slice and then integratingtwice of this charge distribution. Periodic boundaries are not taken  into account. Reference of potential is taken to be the left side ofthe box. It's also possible to calculate the potential in sphericalcoordinates as function of r by calculating a charge distribution inspherical slices and twice integrating them. epsilon_r is taken as 1,2 is more appropriate in many cases
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-n" " index.ndx" 
.B Input
 Index file 

.BI "-s" " topol.tpr" 
.B Input
 Generic run input: tpr tpb tpa xml 

.BI "-o" " potential.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-oc" " charge.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-of" " field.xvg" 
.B Output
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-d"  " string" " Z" 
 Take the normal on the membrane in direction X, Y or Z.

.BI "-sl"  " int" " 10" 
 Calculate potential as function of boxlength, dividing the box in nr slices.

.BI "-cb"  " int" " 0" 
 Discard first nr slices of box for integration

.BI "-ce"  " int" " 0" 
 Discard last nr slices of box for integration

.BI "-tz"  " real" "      0" 
 Translate all coordinates distance in the direction of the box

.BI "-[no]spherical"  "    no"
 Calculate spherical thingie

.BI "-ng"  " int" " 1" 
 Number of groups to consider

\- Discarding slices for integration should not be necessary.

