.TH g_rdf 1 "Mon 29 Aug 2005"
.SH NAME
g_rdf
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_rdf\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-o" " rdf.xvg "
.BI "-sq" " sq.xvg "
.BI "-cn" " rdf_cn.xvg "
.BI "-hq" " hq.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-bin" " real "
.BI "-[no]com" ""
.BI "-[no]pbc" ""
.BI "-[no]xy" ""
.BI "-cut" " real "
.BI "-ng" " int "
.BI "-fade" " real "
.BI "-nlevel" " int "
.BI "-startq" " real "
.BI "-endq" " real "
.BI "-energy" " real "
.SH DESCRIPTION
The structure of liquids can be studied by either neutron or X-ray
scattering. The most common way to describe liquid structure is by a
radial distribution function. However, this is not easy to obtain from
a scattering experiment.


g_rdf calculates radial distribution functions in different ways.
The normal method is around a (set of) particle(s), the other method
is around the center of mass of a set of particles.
With both methods rdf's can also be calculated around axes parallel
to the z-axis with option 
.B -xy
.


If a run input file is supplied (
.B -s
), exclusions defined
in that file are taken into account when calculating the rdf.
The option 
.B -cut
is meant as an alternative way to avoid
intramolecular peaks in the rdf plot.
It is however better to supply a run input file with a higher number of
exclusions. For eg. benzene a topology with nrexcl set to 5
would eliminate all intramolecular contributions to the rdf.
Note that all atoms in the selected groups are used, also the ones
that don't have Lennard-Jones interactions.


Option 
.B -cn
produces the cumulative number rdf.

To bridge the gap between theory and experiment structure factors can
be computed (option 
.B -sq
). The algorithm uses FFT, the gridspacing of which is determined by option 
.B -grid
.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input, Opt.
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-o" " rdf.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-sq" " sq.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-cn" " rdf_cn.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-hq" " hq.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-bin"  " real" "  0.002" 
 Binwidth (nm)

.BI "-[no]com"  "    no"
 RDF with respect to the center of mass of first group

.BI "-[no]pbc"  "   yes"
 Use periodic boundary conditions for computing distances

.BI "-[no]xy"  "    no"
 Use only the x and y components of the distance

.BI "-cut"  " real" "      0" 
 Shortest distance (nm) to be considered

.BI "-ng"  " int" " 1" 
 Number of secondary groups to compute RDFs around a central group

.BI "-fade"  " real" "      0" 
 From this distance onwards the RDF is tranformed by g'(r) = 1 + [g(r)-1] exp(-(r/fade-1)2 to make it go to 1 smoothly. If fade is 0.0 nothing is done.

.BI "-nlevel"  " int" " 20" 
 Number of different colors in the diffraction image

.BI "-startq"  " real" "      0" 
 Starting q (1/nm) 

.BI "-endq"  " real" "     60" 
 Ending q (1/nm)

.BI "-energy"  " real" "     12" 
 Energy of the incoming X-ray (keV) 

