.TH g_rmsdist 1 "Mon 29 Aug 2005"
.SH NAME
g_rmsdist
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_rmsdist\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-equiv" " equiv.dat "
.BI "-o" " distrmsd.xvg "
.BI "-rms" " rmsdist.xpm "
.BI "-scl" " rmsscale.xpm "
.BI "-mean" " rmsmean.xpm "
.BI "-nmr3" " nmr3.xpm "
.BI "-nmr6" " nmr6.xpm "
.BI "-noe" " noe.dat "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-nlevels" " int "
.BI "-max" " real "
.BI "-[no]sumh" ""
.SH DESCRIPTION
g_rmsdist computes the root mean square deviation of atom distances,
which has the advantage that no fit is needed like in standard RMS
deviation as computed by g_rms.
The reference structure is taken from the structure file.
The rmsd at time t is calculated as the rms
of the differences in distance between atom-pairs in the reference
structure and the structure at time t.


g_rmsdist can also produce matrices of the rms distances, rms distances
scaled with the mean distance and the mean distances and matrices with
NMR averaged distances (1/r3 and 1/r6 averaging). Finally, lists
of atom pairs with 1/r3 and 1/r6 averaged distance below the
maximum distance (
.B -max
, which will default to 0.6 in this case)
can be generated, by default averaging over equivalent hydrogens
(all triplets of hydrogens named *[123]). Additionally a list of
equivalent atoms can be supplied (
.B -equiv
), each line containing
a set of equivalent atoms specified as residue number and name and
atom name; e.g.:



.B 3 SER  HB1 3 SER  HB2



Residue and atom names must exactly match those in the structure
file, including case. Specifying non-sequential atoms is undefined.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-equiv" " equiv.dat" 
.B Input, Opt.
 Generic data file 

.BI "-o" " distrmsd.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-rms" " rmsdist.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.BI "-scl" " rmsscale.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.BI "-mean" " rmsmean.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.BI "-nmr3" " nmr3.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.BI "-nmr6" " nmr6.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.BI "-noe" " noe.dat" 
.B Output, Opt.
 Generic data file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-nlevels"  " int" " 40" 
 Discretize rms in  levels

.BI "-max"  " real" "     -1" 
 Maximum level in matrices

.BI "-[no]sumh"  "   yes"
 average distance over equivalent hydrogens

