.TH g_rmsdist 1 "Fri 18 Jan 2013" "" "GROMACS suite, VERSION 4.5.6"
.SH NAME
g_rmsdist - calculates atom pair distances averaged with power \-2, \-3 or \-6

.B VERSION 4.5.6
.SH SYNOPSIS
\f3g_rmsdist\fP
.BI "\-f" " traj.xtc "
.BI "\-s" " topol.tpr "
.BI "\-n" " index.ndx "
.BI "\-equiv" " equiv.dat "
.BI "\-o" " distrmsd.xvg "
.BI "\-rms" " rmsdist.xpm "
.BI "\-scl" " rmsscale.xpm "
.BI "\-mean" " rmsmean.xpm "
.BI "\-nmr3" " nmr3.xpm "
.BI "\-nmr6" " nmr6.xpm "
.BI "\-noe" " noe.dat "
.BI "\-[no]h" ""
.BI "\-[no]version" ""
.BI "\-nice" " int "
.BI "\-b" " time "
.BI "\-e" " time "
.BI "\-dt" " time "
.BI "\-[no]w" ""
.BI "\-xvg" " enum "
.BI "\-nlevels" " int "
.BI "\-max" " real "
.BI "\-[no]sumh" ""
.BI "\-[no]pbc" ""
.SH DESCRIPTION
\&\fB g_rmsdist\fR computes the root mean square deviation of atom distances,
\&which has the advantage that no fit is needed like in standard RMS
\&deviation as computed by \fB g_rms\fR.
\&The reference structure is taken from the structure file.
\&The RMSD at time t is calculated as the RMS
\&of the differences in distance between atom\-pairs in the reference
\&structure and the structure at time t.


\&\fB g_rmsdist\fR can also produce matrices of the rms distances, rms distances
\&scaled with the mean distance and the mean distances and matrices with
\&NMR averaged distances (1/r3 and 1/r6 averaging). Finally, lists
\&of atom pairs with 1/r3 and 1/r6 averaged distance below the
\&maximum distance (\fB \-max\fR, which will default to 0.6 in this case)
\&can be generated, by default averaging over equivalent hydrogens
\&(all triplets of hydrogens named *[123]). Additionally a list of
\&equivalent atoms can be supplied (\fB \-equiv\fR), each line containing
\&a set of equivalent atoms specified as residue number and name and
\&atom name; e.g.:


\&\fB 3 SER  HB1 3 SER  HB2\fR


\&Residue and atom names must exactly match those in the structure
\&file, including case. Specifying non\-sequential atoms is undefined.
.SH FILES
.BI "\-f" " traj.xtc" 
.B Input
 Trajectory: xtc trr trj gro g96 pdb cpt 

.BI "\-s" " topol.tpr" 
.B Input
 Structure+mass(db): tpr tpb tpa gro g96 pdb 

.BI "\-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "\-equiv" " equiv.dat" 
.B Input, Opt.
 Generic data file 

.BI "\-o" " distrmsd.xvg" 
.B Output
 xvgr/xmgr file 

.BI "\-rms" " rmsdist.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.BI "\-scl" " rmsscale.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.BI "\-mean" " rmsmean.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.BI "\-nmr3" " nmr3.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.BI "\-nmr6" " nmr6.xpm" 
.B Output, Opt.
 X PixMap compatible matrix file 

.BI "\-noe" " noe.dat" 
.B Output, Opt.
 Generic data file 

.SH OTHER OPTIONS
.BI "\-[no]h"  "no    "
 Print help info and quit

.BI "\-[no]version"  "no    "
 Print version info and quit

.BI "\-nice"  " int" " 19" 
 Set the nicelevel

.BI "\-b"  " time" " 0     " 
 First frame (ps) to read from trajectory

.BI "\-e"  " time" " 0     " 
 Last frame (ps) to read from trajectory

.BI "\-dt"  " time" " 0     " 
 Only use frame when t MOD dt = first time (ps)

.BI "\-[no]w"  "no    "
 View output \fB .xvg\fR, \fB .xpm\fR, \fB .eps\fR and \fB .pdb\fR files

.BI "\-xvg"  " enum" " xmgrace" 
 xvg plot formatting: \fB xmgrace\fR, \fB xmgr\fR or \fB none\fR

.BI "\-nlevels"  " int" " 40" 
 Discretize RMS in this number of levels

.BI "\-max"  " real" " \-1    " 
 Maximum level in matrices

.BI "\-[no]sumh"  "yes   "
 Average distance over equivalent hydrogens

.BI "\-[no]pbc"  "yes   "
 Use periodic boundary conditions when computing distances

.SH SEE ALSO
.BR gromacs(7)

More information about \fBGROMACS\fR is available at <\fIhttp://www.gromacs.org/\fR>.
