.TH g_rmsf 1 "Mon 29 Aug 2005"
.SH NAME
g_rmsf
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_rmsf\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-q" " eiwit.pdb "
.BI "-oq" " bfac.pdb "
.BI "-ox" " xaver.pdb "
.BI "-o" " rmsf.xvg "
.BI "-od" " rmsdev.xvg "
.BI "-oc" " correl.xvg "
.BI "-dir" " rmsf.log "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-[no]res" ""
.BI "-[no]aniso" ""
.SH DESCRIPTION
g_rmsf computes the root mean square fluctuation (RMSF, i.e. standard 
deviation) of atomic positions 
after first fitting to a reference frame.


With option 
.B -oq
the RMSF values are converted to B-factor
values, which are written to a pdb file with the coordinates, of the
structure file, or of a pdb file when 
.B -q
is specified.
Option 
.B -ox
writes the B-factors to a file with the average
coordinates.


With the option 
.B -od
the root mean square deviation with
respect to the reference structure is calculated.


With the option 
.B aniso
g_rmsf will compute anisotropic
temperature factors and then it will also output average coordinates
and a pdb file with ANISOU records (corresonding to the 
.B -oq

or 
.B -ox
option). Please note that the U values
are orientation dependent, so before comparison with experimental data
you should verify that you fit to the experimental coordinates.


When a pdb input file is passed to the program and the 
.B -aniso

flag is set
a correlation plot of the Uij will be created, if any anisotropic
temperature factors are present in the pdb file.


With option 
.B -dir
the average MSF (3x3) matrix is diagonalized.
This shows the directions in which the atoms fluctuate the most and
the least.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-q" " eiwit.pdb" 
.B Input, Opt.
 Protein data bank file 

.BI "-oq" " bfac.pdb" 
.B Output, Opt.
 Protein data bank file 

.BI "-ox" " xaver.pdb" 
.B Output, Opt.
 Protein data bank file 

.BI "-o" " rmsf.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-od" " rmsdev.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-oc" " correl.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-dir" " rmsf.log" 
.B Output, Opt.
 Log file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-[no]res"  "    no"
 Calculate averages for each residue

.BI "-[no]aniso"  "    no"
 Compute anisotropic termperature factors

