.TH g_sas 1 "Mon 29 Aug 2005"
.SH NAME
g_sas
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_sas\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-o" " area.xvg "
.BI "-or" " resarea.xvg "
.BI "-oa" " atomarea.xvg "
.BI "-q" " connelly.pdb "
.BI "-n" " index.ndx "
.BI "-i" " surfat.itp "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-solsize" " real "
.BI "-ndots" " int "
.BI "-qmax" " real "
.BI "-[no]f_index" ""
.BI "-minarea" " real "
.BI "-[no]pbc" ""
.BI "-[no]prot" ""
.BI "-dgs" " real "
.SH DESCRIPTION
g_sas computes hydrophobic, hydrophilic and total solvent accessible surface area.
As a side effect the Connolly surface can be generated as well in
a pdb file where the nodes are represented as atoms and the vertices
connecting the nearest nodes as CONECT records.
The program will ask for a group for the surface calculation
and a group for the output. The calculation group should always
consists of all the non-solvent atoms in the system.
The output group can be the whole or part of the calculation group.
The area can be plotted
per residue and atom as well (options 
.B -or
and 
.B -oa
).
In combination with the latter option an 
.B itp
file can be
generated (option 
.B -i
)
which can be used to restrain surface atoms.


By default, periodic boundary conditions are taken into account,
this can be turned off using the 
.B -pbc
option.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input
 Generic run input: tpr tpb tpa xml 

.BI "-o" " area.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-or" " resarea.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-oa" " atomarea.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-q" " connelly.pdb" 
.B Output, Opt.
 Protein data bank file 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-i" " surfat.itp" 
.B Output, Opt.
 Include file for topology 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-solsize"  " real" "   0.14" 
 Radius of the solvent probe (nm)

.BI "-ndots"  " int" " 24" 
 Number of dots per sphere, more dots means more accuracy

.BI "-qmax"  " real" "    0.2" 
 The maximum charge (e, absolute value) of a hydrophobic atom

.BI "-[no]f_index"  "    no"
 Determine from a group in the index file what are the hydrophobic atoms rather than from the charge

.BI "-minarea"  " real" "    0.5" 
 The minimum area (nm2) to count an atom as a surface atom when writing a position restraint file  (see help)

.BI "-[no]pbc"  "   yes"
 Take periodicity into account

.BI "-[no]prot"  "   yes"
 Output the protein to the connelly pdb file too

.BI "-dgs"  " real" "      0" 
 default value for solvation free energy per area (kJ/mol/nm2)

