.TH g_sgangle 1 "Mon 29 Aug 2005"
.SH NAME
g_sgangle
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_sgangle\fP
.BI "-f" " traj.xtc "
.BI "-n" " index.ndx "
.BI "-s" " topol.tpr "
.BI "-oa" " sg_angle.xvg "
.BI "-od" " sg_dist.xvg "
.BI "-od1" " sg_dist1.xvg "
.BI "-od2" " sg_dist2.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-[no]pbc" ""
.BI "-[no]one" ""
.BI "-[no]z" ""
.SH DESCRIPTION
Compute the angle and distance between two groups. 
The groups are defined by a number of atoms given in an index file and
may be two or three atoms in size.
If -one is set, only one group should be specified in the index
file and the angle between this group at time 0 and t will be computed.
The angles calculated depend on the order in which the atoms are 
given. Giving for instance 5 6 will rotate the vector 5-6 with 
180 degrees compared to giving 6 5. 

If three atoms are given, 
the normal on the plane spanned by those three atoms will be
calculated, using the formula  P1P2 x P1P3.
The cos of the angle is calculated, using the inproduct of the two
normalized vectors.


Here is what some of the file options do:

-oa: Angle between the two groups specified in the index file. If a group contains three atoms the normal to the plane defined by those three atoms will be used. If a group contains two atoms, the vector defined by those two atoms will be used.

-od: Distance between two groups. Distance is taken from the center of one group to the center of the other group.

-od1: If one plane and one vector is given, the distances for each of the atoms from the center of the plane is given seperately.

-od2: For two planes this option has no meaning.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-n" " index.ndx" 
.B Input
 Index file 

.BI "-s" " topol.tpr" 
.B Input
 Generic run input: tpr tpb tpa xml 

.BI "-oa" " sg_angle.xvg" 
.B Output
 xvgr/xmgr file 

.BI "-od" " sg_dist.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-od1" " sg_dist1.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-od2" " sg_dist2.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-[no]pbc"  "    no"
 Use periodic boundary conditions

.BI "-[no]one"  "    no"
 Only one group compute angle between vector at time zero and time t

.BI "-[no]z"  "    no"
 Use the Z-axis as reference

