.TH g_traj 1 "Mon 29 Aug 2005"
.SH NAME
g_traj
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3g_traj\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-ox" " coord.xvg "
.BI "-ov" " veloc.xvg "
.BI "-of" " force.xvg "
.BI "-ob" " box.xvg "
.BI "-ot" " temp.xvg "
.BI "-ekt" " ektrans.xvg "
.BI "-ekr" " ekrot.xvg "
.BI "-vd" " veldist.xvg "
.BI "-cv" " veloc.pdb "
.BI "-cf" " force.pdb "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-tu" " enum "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-[no]com" ""
.BI "-[no]mol" ""
.BI "-[no]nojump" ""
.BI "-[no]x" ""
.BI "-[no]y" ""
.BI "-[no]z" ""
.BI "-ng" " int "
.BI "-[no]len" ""
.BI "-bin" " real "
.BI "-scale" " real "
.SH DESCRIPTION
g_traj plots coordinates, velocities, forces and/or the box.
With 
.B -com
the coordinates, velocities and forces are
calculated for the center of mass of each group.
When 
.B -mol
is set, the numbers in the index file are
interpreted as molecule numbers and the same procedure as with

.B -com
is used for each molecule.


Option 
.B -ot
plots the temperature of each group,
provided velocities are present in the trajectory file.
No corrections are made for constrained degrees of freedom!
This implies 
.B -com
.


Options 
.B -ekt
and 
.B -ekr
plot the translational and
rotational kinetic energy of each group,
provided velocities are present in the trajectory file.
This implies 
.B -com
.


Options 
.B -cv
and 
.B -cf
write the average velocities
and average forces as temperature factors to a pdb file with
the average coordinates. The temperature factors are scaled such
that the maximum is 10. The scaling can be changed with the option

.B -scale
. To get the velocities or forces of one
frame set both 
.B -b
and 
.B -e
to the time of
desired frame. When averaging over frames you might need to use
the 
.B -nojump
option to obtain the correct average coordinates.


Option 
.B -vd
computes a velocity distribution, i.e. the
norm of the vector is plotted. In addition in the same graph
the kinetic energy distribution is given.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-ox" " coord.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-ov" " veloc.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-of" " force.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-ob" " box.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-ot" " temp.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-ekt" " ektrans.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-ekr" " ekrot.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-vd" " veldist.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.BI "-cv" " veloc.pdb" 
.B Output, Opt.
 Protein data bank file 

.BI "-cf" " force.pdb" 
.B Output, Opt.
 Protein data bank file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-tu"  " enum" " ps" 
 Time unit: 
.B ps
, 
.B fs
, 
.B ns
, 
.B us
, 
.B ms
, 
.B s
, 
.B m
or 
.B h


.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-[no]com"  "    no"
 Plot data for the com of each group

.BI "-[no]mol"  "    no"
 Index contains molecule numbers iso atom numbers

.BI "-[no]nojump"  "    no"
 Remove jumps of atoms across the box

.BI "-[no]x"  "   yes"
 Plot X-component

.BI "-[no]y"  "   yes"
 Plot Y-component

.BI "-[no]z"  "   yes"
 Plot Z-component

.BI "-ng"  " int" " 1" 
 Number of groups to consider

.BI "-[no]len"  "    no"
 Plot vector length

.BI "-bin"  " real" "      1" 
 Binwidth for velocity histogram (nm/ps)

.BI "-scale"  " real" "      0" 
 Scale factor for pdb output, 0 is autoscale

