.TH g_wheel 1 "Fri 18 Jan 2013" "" "GROMACS suite, VERSION 4.5.6"
.SH NAME
g_wheel - plots helical wheels

.B VERSION 4.5.6
.SH SYNOPSIS
\f3g_wheel\fP
.BI "\-f" " nnnice.dat "
.BI "\-o" " plot.eps "
.BI "\-[no]h" ""
.BI "\-[no]version" ""
.BI "\-nice" " int "
.BI "\-r0" " int "
.BI "\-rot0" " real "
.BI "\-T" " string "
.BI "\-[no]nn" ""
.SH DESCRIPTION
\&\fB g_wheel\fR plots a helical wheel representation of your sequence.
\&The input sequence is in the \fB .dat\fR file where the first line contains
\&the number of residues and each consecutive line contains a residue name.
.SH FILES
.BI "\-f" " nnnice.dat" 
.B Input
 Generic data file 

.BI "\-o" " plot.eps" 
.B Output
 Encapsulated PostScript (tm) file 

.SH OTHER OPTIONS
.BI "\-[no]h"  "no    "
 Print help info and quit

.BI "\-[no]version"  "no    "
 Print version info and quit

.BI "\-nice"  " int" " 19" 
 Set the nicelevel

.BI "\-r0"  " int" " 1" 
 The first residue number in the sequence

.BI "\-rot0"  " real" " 0     " 
 Rotate around an angle initially (90 degrees makes sense)

.BI "\-T"  " string" " " 
 Plot a title in the center of the wheel (must be shorter than 10 characters, or it will overwrite the wheel)

.BI "\-[no]nn"  "yes   "
 Toggle numbers

.SH SEE ALSO
.BR gromacs(7)

More information about \fBGROMACS\fR is available at <\fIhttp://www.gromacs.org/\fR>.
