.TH genvsites 1 "Thu 16 Oct 2008"
.SH NAME
genvsites
.B VERSION 3.3.99_development_20070618
.SH SYNOPSIS
\f3genvsites\fP
.BI "-c" " eiwit.gro "
.BI "-o" " conf.gro "
.BI "-p" " topol.top "
.BI "-pp" " processed.top "
.BI "-q" " topol.top "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-[no]v" ""
.BI "-ff" " string "
.BI "-vsite" " enum "
.BI "-[no]heavyh" ""
.BI "-[no]deuterate" ""
.SH DESCRIPTION
This program read a coordinate file and a topology file, adds
virtual sites as indicated on the command line and writes out
a new topology and coordinate file.
.SH FILES
.BI "-c" " eiwit.gro" 
.B Input
 Generic structure: gro g96 pdb tpr tpb tpa xml 

.BI "-o" " conf.gro" 
.B Output
 Generic structure: gro g96 pdb xml 

.BI "-p" " topol.top" 
.B Input
 Topology file 

.BI "-pp" " processed.top" 
.B Output, Opt.
 Topology file 

.BI "-q" " topol.top" 
.B Output
 Topology file 

.SH OTHER OPTIONS
.BI "-[no]h"  "no    "
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-[no]v"  "no    "
 Be loud and noisy

.BI "-ff"  " string" " select" 
 Force field, interactive by default. Use -h for information.

.BI "-vsite"  " enum" " none" 
 Convert atoms to virtual sites: 
.B none
, 
.B hydrogens
or 
.B aromatics


.BI "-[no]heavyh"  "no    "
 Make hydrogen atoms heavy

.BI "-[no]deuterate"  "no    "
 Change the mass of hydrogens to 2 amu

