.TH gmxcheck 1 "Mon 29 Aug 2005"
.SH NAME
gmxcheck
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3gmxcheck\fP
.BI "-f" " traj.xtc "
.BI "-f2" " traj.xtc "
.BI "-s1" " top1.tpr "
.BI "-s2" " top2.tpr "
.BI "-c" " topol.tpr "
.BI "-e" " ener.edr "
.BI "-e2" " ener2.edr "
.BI "-n" " index.ndx "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-vdwfac" " real "
.BI "-bonlo" " real "
.BI "-bonhi" " real "
.BI "-tol" " real "
.BI "-lastener" " string "
.SH DESCRIPTION
gmxcheck reads a trajectory (
.B .trj
, 
.B .trr
or 

.B .xtc
) or an energy file (
.B .ene
or 
.B .edr
)
and prints out useful information about them.


Option 
.B -c
checks for presence of coordinates,
velocities and box in the file, for close contacts (smaller than

.B -vdwfac
and not bonded, i.e. not between 
.B -bonlo

and 
.B -bonhi
, all relative to the sum of both Van der Waals
radii) and atoms outside the box (these may occur often and are
no problem). If velocities are present, an estimated temperature
will be calculated from them.


If an index file is given it's contents will be sumamrized.


If both a trajectory and a tpr file are given (with 
.B -s1
)
the program will check whether the bond lengths defined in the tpr
file are indeed correct in the trajectory. If not you may have
non-matching files due to e.g. deshuffling or due to problems with
virtual sites. With these flags, gmxcheck provides a quick check for such problems.

The program can compare run two input (
.B .tpr
, 
.B .tpb
or

.B .tpa
) files
when both 
.B -s1
and 
.B -s2
are supplied.
Similarly a pair of trajectory files can be compared (using the 
.B -f2

option), or a pair of energy files (using the 
.B -e2
option).
.SH FILES
.BI "-f" " traj.xtc" 
.B Input, Opt.
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-f2" " traj.xtc" 
.B Input, Opt.
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s1" " top1.tpr" 
.B Input, Opt.
 Generic run input: tpr tpb tpa xml 

.BI "-s2" " top2.tpr" 
.B Input, Opt.
 Generic run input: tpr tpb tpa xml 

.BI "-c" " topol.tpr" 
.B Input, Opt.
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-e" " ener.edr" 
.B Input, Opt.
 Generic energy: edr ene 

.BI "-e2" " ener2.edr" 
.B Input, Opt.
 Generic energy: edr ene 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-vdwfac"  " real" "    0.8" 
 Fraction of sum of VdW radii used as warning cutoff

.BI "-bonlo"  " real" "    0.4" 
 Min. fract. of sum of VdW radii for bonded atoms

.BI "-bonhi"  " real" "    0.7" 
 Max. fract. of sum of VdW radii for bonded atoms

.BI "-tol"  " real" "  0.001" 
 Relative tolerance for comparing real values defined as 2*(a-b)/(|a|+|b|)

.BI "-lastener"  " string" " " 
 Last energy term to compare (if not given all are tested). It makes sense to go up until the Pressure.

