.TH gmxdump 1 "Mon 29 Aug 2005"
.SH NAME
gmxdump
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3gmxdump\fP
.BI "-s" " topol.tpr "
.BI "-f" " traj.xtc "
.BI "-e" " ener.edr "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-[no]nr" ""
.SH DESCRIPTION
gmxdump reads a run input file (
.B .tpa
/
.B .tpr
/
.B .tpb
),
a trajectory (
.B .trj
/
.B .trr
/
.B .xtc
) or an energy
file (
.B .ene
/
.B .edr
) and prints that to standard
output in a readable format. This program is essential for
checking your run input file in case of problems.


.SH FILES
.BI "-s" " topol.tpr" 
.B Input, Opt.
 Generic run input: tpr tpb tpa xml 

.BI "-f" " traj.xtc" 
.B Input, Opt.
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-e" " ener.edr" 
.B Input, Opt.
 Generic energy: edr ene 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-[no]nr"  "   yes"
 Show index numbers in output (leaving them out makes comparison easier, but creates a useless topology)

