.TH gmxdump 1 "Thu 16 Oct 2008"
.SH NAME
gmxdump - makes binary files human readable

.B VERSION 4.0
.SH SYNOPSIS
\f3gmxdump\fP
.BI "-s" " topol.tpr "
.BI "-f" " traj.xtc "
.BI "-e" " ener.edr "
.BI "-cp" " state.cpt "
.BI "-om" " grompp.mdp "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-[no]nr" ""
.SH DESCRIPTION
gmxdump reads a run input file (
.B .tpa
/
.B .tpr
/
.B .tpb
),
a trajectory (
.B .trj
/
.B .trr
/
.B .xtc
) or an energy
file (
.B .ene
/
.B .edr
) and prints that to standard
output in a readable format. This program is essential for
checking your run input file in case of problems.


When requesting to dump a topology file the program will dump
the processed topology, since not all original information is maintained
in tpr files.
.SH FILES
.BI "-s" " topol.tpr" 
.B Input, Opt.
 Run input file: tpr tpb tpa 

.BI "-f" " traj.xtc" 
.B Input, Opt.
 Trajectory: xtc trr trj gro g96 pdb cpt 

.BI "-e" " ener.edr" 
.B Input, Opt.
 Energy file: edr ene 

.BI "-cp" " state.cpt" 
.B Input, Opt.
 Checkpoint file 

.BI "-om" " grompp.mdp" 
.B Output, Opt.
 grompp input file with MD parameters 

.SH OTHER OPTIONS
.BI "-[no]h"  "no    "
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-[no]nr"  "yes   "
 Show index numbers in output (leaving them out makes comparison easier, but creates a useless topology)

