.TH highway 1 "Thu 16 Oct 2008"
.SH NAME
highway - X-windows gadget for highway simulations

.B VERSION 4.0
.SH SYNOPSIS
\f3highway\fP
.BI "-f" " highway.dat "
.BI "-[no]h" ""
.BI "-nice" " int "
.SH DESCRIPTION
highway is the gromacs highway simulator. It is an X-windows
gadget that shows a (periodic) Autobahn with a user defined
number of cars. Fog can be turned on or off to increase the
number of crashes. Nice for a background CPU-eater. A sample
input file is in $GMXDATA/top/highway.dat
.SH FILES
.BI "-f" " highway.dat" 
.B Input
 Generic data file 

.SH OTHER OPTIONS
.BI "-[no]h"  "no    "
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

