.TH highway 1 "Mon 29 Aug 2005"
.SH NAME
highway
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3highway\fP
.BI "-f" " highway.dat "
.BI "-[no]h" ""
.BI "-nice" " int "
.SH DESCRIPTION
highway is the gromacs highway simulator. It is an X-windows
gadget that shows a (periodic) Autobahn with a user defined
number of cars. Fog can be turned on or off to increase the
number of crashes. Nice for a background CPU-eater. A sample
input file is in $GMXDATA/top/highway.dat
.SH FILES
.BI "-f" " highway.dat" 
.B Input
 Generic data file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

