.TH hrefify 1 "Thu 16 Oct 2008"
.SH NAME
hrefify
.B VERSION 3.3.99_development_200800503
.SH SYNOPSIS
\f3hrefify\fP
.BI "-l" " links.dat "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-f" " string "
.BI "-o" " string "
.BI "-e" " string "
.BI "-t" " string "
.SH DESCRIPTION
hrefify adds href's for all the words in the input file which are not
already hyperlinked and which appear in the file specified with the
option 
.B -l
.


If the href's should call a script, text can be added
with the 
.B -t
option.
.SH FILES
.BI "-l" " links.dat" 
.B Input, Lib.
 Generic data file 

.SH OTHER OPTIONS
.BI "-[no]h"  "no    "
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-f"  " string" " " 
 HTML input

.BI "-o"  " string" " " 
 HTML output

.BI "-e"  " string" " " 
 Exclude a string from HREF's, when this option is not set, the filename without path and extension will be excluded from HREF's

.BI "-t"  " string" " " 
 Insert a string in front of the href file name, useful for scripts

