.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "LUCK" "1" "15 Feb 2008" "GROMACS suite, Version 3.3"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
luck \- GROMACS installation test program
.SH SYNOPSIS
.B luck
.SH DESCRIPTION
.B luck
writes a randomly selected quote to \fIstdout\fP.  Normally this
serves to test a freshly-compiled GROMACS installation; it also helps to
maintain that air of cultural sophistication and wide-ranging appeal that
characterizes any molecular dynamics package worth its force fields.
.SH OPTIONS
.B luck
takes no options\.  It may vary its output depending on whether
the user is cool or not.
.SH SEE ALSO
.BR fortune (1),
.BR gromacs (7)
.SH AUTHOR
Sadly, the current GROMACS distribution lacks official documentation
for this command.

This manual page was written by Nicholas Breen <\&nbreen@ofb\.net\&>,
for the Debian GNU/Linux system (but may be used by others)\.
