.TH make_ndx 1 "Mon 29 Aug 2005"
.SH NAME
make_ndx
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3make_ndx\fP
.BI "-f" " conf.gro "
.BI "-n" " index.ndx "
.BI "-o" " index.ndx "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-natoms" " int "
.SH DESCRIPTION
Index groups are necessary for almost every gromacs program.
All these programs can generate default index groups. You ONLY
have to use make_ndx when you need SPECIAL index groups.
There is a default index group for the whole system, 9 default
index groups are generated for proteins, a default index group
is generated for every other residue name.

When no index file is supplied, also make_ndx will generate the
default groups.
With the index editor you can select on atom, residue and chain names
and numbers.
When a run input file is supplied you can also select on atom type.
You can use NOT, AND and OR, you can split groups
into chains, residues or atoms. You can delete and rename groups.


The atom numbering in the editor and the index file starts at 1.
.SH FILES
.BI "-f" " conf.gro" 
.B Input, Opt.
 Generic structure: gro g96 pdb tpr tpb tpa xml 

.BI "-n" " index.ndx" 
.B Input, Opt., Mult.
 Index file 

.BI "-o" " index.ndx" 
.B Output
 Index file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-natoms"  " int" " 0" 
 set number of atoms (default: read from coordinate or index file)

