.TH make_edi 1 "Fri 18 Jan 2013" "" "GROMACS suite, VERSION 4.5.6"
.SH NAME
make_edi - generate input files for essential dynamics sampling

.B VERSION 4.5.6
.SH SYNOPSIS
\f3make_edi\fP
.BI "\-f" " eigenvec.trr "
.BI "\-eig" " eigenval.xvg "
.BI "\-s" " topol.tpr "
.BI "\-n" " index.ndx "
.BI "\-tar" " target.gro "
.BI "\-ori" " origin.gro "
.BI "\-o" " sam.edi "
.BI "\-[no]h" ""
.BI "\-[no]version" ""
.BI "\-nice" " int "
.BI "\-xvg" " enum "
.BI "\-mon" " string "
.BI "\-linfix" " string "
.BI "\-linacc" " string "
.BI "\-radfix" " string "
.BI "\-radacc" " string "
.BI "\-radcon" " string "
.BI "\-flood" " string "
.BI "\-outfrq" " int "
.BI "\-slope" " real "
.BI "\-linstep" " string "
.BI "\-accdir" " string "
.BI "\-radstep" " real "
.BI "\-maxedsteps" " int "
.BI "\-eqsteps" " int "
.BI "\-deltaF0" " real "
.BI "\-deltaF" " real "
.BI "\-tau" " real "
.BI "\-Eflnull" " real "
.BI "\-T" " real "
.BI "\-alpha" " real "
.BI "\-[no]restrain" ""
.BI "\-[no]hessian" ""
.BI "\-[no]harmonic" ""
.BI "\-constF" " string "
.SH DESCRIPTION
\&\fB make_edi\fR generates an essential dynamics (ED) sampling input file to be used with \fB mdrun\fR
\&based on eigenvectors of a covariance matrix (\fB g_covar\fR) or from a
\&normal modes anaysis (\fB g_nmeig\fR).
\&ED sampling can be used to manipulate the position along collective coordinates
\&(eigenvectors) of (biological) macromolecules during a simulation. Particularly,
\&it may be used to enhance the sampling efficiency of MD simulations by stimulating
\&the system to explore new regions along these collective coordinates. A number
\&of different algorithms are implemented to drive the system along the eigenvectors
\&(\fB \-linfix\fR, \fB \-linacc\fR, \fB \-radfix\fR, \fB \-radacc\fR, \fB \-radcon\fR),
\&to keep the position along a certain (set of) coordinate(s) fixed (\fB \-linfix\fR),
\&or to only monitor the projections of the positions onto
\&these coordinates (\fB \-mon\fR).


\&References:

\&A. Amadei, A.B.M. Linssen, B.L. de Groot, D.M.F. van Aalten and 
\&H.J.C. Berendsen; An efficient method for sampling the essential subspace 
\&of proteins., J. Biomol. Struct. Dyn. 13:615\-626 (1996)

\&B.L. de Groot, A. Amadei, D.M.F. van Aalten and H.J.C. Berendsen; 
\&Towards an exhaustive sampling of the configurational spaces of the 
\&two forms of the peptide hormone guanylin,
\&J. Biomol. Struct. Dyn. 13 : 741\-751 (1996)

\&B.L. de Groot, A.Amadei, R.M. Scheek, N.A.J. van Nuland and H.J.C. Berendsen; 
\&An extended sampling of the configurational space of HPr from E. coli
\&Proteins: Struct. Funct. Gen. 26: 314\-322 (1996)
\&

You will be prompted for one or more index groups that correspond to the eigenvectors,
\&reference structure, target positions, etc.


\&\fB \-mon\fR: monitor projections of the coordinates onto selected eigenvectors.


\&\fB \-linfix\fR: perform fixed\-step linear expansion along selected eigenvectors.


\&\fB \-linacc\fR: perform acceptance linear expansion along selected eigenvectors.
\&(steps in the desired directions will be accepted, others will be rejected).


\&\fB \-radfix\fR: perform fixed\-step radius expansion along selected eigenvectors.


\&\fB \-radacc\fR: perform acceptance radius expansion along selected eigenvectors.
\&(steps in the desired direction will be accepted, others will be rejected).
\&\fB Note:\fR by default the starting MD structure will be taken as origin of the first
\&expansion cycle for radius expansion. If \fB \-ori\fR is specified, you will be able
\&to read in a structure file that defines an external origin.


\&\fB \-radcon\fR: perform acceptance radius contraction along selected eigenvectors
\&towards a target structure specified with \fB \-tar\fR.


\&NOTE: each eigenvector can be selected only once. 


\&\fB \-outfrq\fR: frequency (in steps) of writing out projections etc. to \fB .edo\fR file


\&\fB \-slope\fR: minimal slope in acceptance radius expansion. A new expansion
\&cycle will be started if the spontaneous increase of the radius (in nm/step)
\&is less than the value specified.


\&\fB \-maxedsteps\fR: maximum number of steps per cycle in radius expansion
\&before a new cycle is started.


\&Note on the parallel implementation: since ED sampling is a 'global' thing
\&(collective coordinates etc.), at least on the 'protein' side, ED sampling
\&is not very parallel\-friendly from an implentation point of view. Because
\&parallel ED requires some extra communication, expect the performance to be
\&lower as in a free MD simulation, especially on a large number of nodes. 


\&All output of \fB mdrun\fR (specify with \fB \-eo\fR) is written to a .edo file. In the output
\&file, per OUTFRQ step the following information is present: 


\&\fB *\fR the step number

\&\fB *\fR the number of the ED dataset. (\fB Note\fR that you can impose multiple ED constraints in
\&a single simulation (on different molecules) if several \fB .edi\fR files were concatenated
\&first. The constraints are applied in the order they appear in the \fB .edi\fR file.) 

\&\fB *\fR RMSD (for atoms involved in fitting prior to calculating the ED constraints)

\&* projections of the positions onto selected eigenvectors

\&




\&FLOODING:


\&with \fB \-flood\fR, you can specify which eigenvectors are used to compute a flooding potential,
\&which will lead to extra forces expelling the structure out of the region described
\&by the covariance matrix. If you switch \-restrain the potential is inverted and the structure
\&is kept in that region.
\&


\&The origin is normally the average structure stored in the \fB eigvec.trr\fR file.
\&It can be changed with \fB \-ori\fR to an arbitrary position in configurational space.
\&With \fB \-tau\fR, \fB \-deltaF0\fR, and \fB \-Eflnull\fR you control the flooding behaviour.
\&Efl is the flooding strength, it is updated according to the rule of adaptive flooding.
\&Tau is the time constant of adaptive flooding, high tau means slow adaption (i.e. growth). 
\&DeltaF0 is the flooding strength you want to reach after tau ps of simulation.
\&To use constant Efl set \fB \-tau\fR to zero.
\&


\&\fB \-alpha\fR is a fudge parameter to control the width of the flooding potential. A value of 2 has been found
\&to give good results for most standard cases in flooding of proteins.
\&alpha basically accounts for incomplete sampling, if you sampled further the width of the ensemble would
\&increase, this is mimicked by alpha  1.
\&For restraining, alpha  1 can give you smaller width in the restraining potential.
\&


\&RESTART and FLOODING:
\&If you want to restart a crashed flooding simulation please find the values deltaF and Efl in
\&the output file and manually put them into the \fB .edi\fR file under DELTA_F0 and EFL_NULL.
.SH FILES
.BI "\-f" " eigenvec.trr" 
.B Input
 Full precision trajectory: trr trj cpt 

.BI "\-eig" " eigenval.xvg" 
.B Input, Opt.
 xvgr/xmgr file 

.BI "\-s" " topol.tpr" 
.B Input
 Structure+mass(db): tpr tpb tpa gro g96 pdb 

.BI "\-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "\-tar" " target.gro" 
.B Input, Opt.
 Structure file: gro g96 pdb tpr etc. 

.BI "\-ori" " origin.gro" 
.B Input, Opt.
 Structure file: gro g96 pdb tpr etc. 

.BI "\-o" " sam.edi" 
.B Output
 ED sampling input 

.SH OTHER OPTIONS
.BI "\-[no]h"  "no    "
 Print help info and quit

.BI "\-[no]version"  "no    "
 Print version info and quit

.BI "\-nice"  " int" " 0" 
 Set the nicelevel

.BI "\-xvg"  " enum" " xmgrace" 
 xvg plot formatting: \fB xmgrace\fR, \fB xmgr\fR or \fB none\fR

.BI "\-mon"  " string" " " 
 Indices of eigenvectors for projections of x (e.g. 1,2\-5,9) or 1\-100:10 means 1 11 21 31 ... 91

.BI "\-linfix"  " string" " " 
 Indices of eigenvectors for fixed increment linear sampling

.BI "\-linacc"  " string" " " 
 Indices of eigenvectors for acceptance linear sampling

.BI "\-radfix"  " string" " " 
 Indices of eigenvectors for fixed increment radius expansion

.BI "\-radacc"  " string" " " 
 Indices of eigenvectors for acceptance radius expansion

.BI "\-radcon"  " string" " " 
 Indices of eigenvectors for acceptance radius contraction

.BI "\-flood"  " string" " " 
 Indices of eigenvectors for flooding

.BI "\-outfrq"  " int" " 100" 
 Freqency (in steps) of writing output in \fB .edo\fR file

.BI "\-slope"  " real" " 0     " 
 Minimal slope in acceptance radius expansion

.BI "\-linstep"  " string" " " 
 Stepsizes (nm/step) for fixed increment linear sampling (put in quotes! "1.0 2.3 5.1 \-3.1")

.BI "\-accdir"  " string" " " 
 Directions for acceptance linear sampling \- only sign counts! (put in quotes! "\-1 +1 \-1.1")

.BI "\-radstep"  " real" " 0     " 
 Stepsize (nm/step) for fixed increment radius expansion

.BI "\-maxedsteps"  " int" " 0" 
 Maximum number of steps per cycle

.BI "\-eqsteps"  " int" " 0" 
 Number of steps to run without any perturbations 

.BI "\-deltaF0"  " real" " 150   " 
 Target destabilization energy for flooding

.BI "\-deltaF"  " real" " 0     " 
 Start deltaF with this parameter \- default 0, nonzero values only needed for restart

.BI "\-tau"  " real" " 0.1   " 
 Coupling constant for adaption of flooding strength according to deltaF0, 0 = infinity i.e. constant flooding strength

.BI "\-Eflnull"  " real" " 0     " 
 The starting value of the flooding strength. The flooding strength is updated according to the adaptive flooding scheme. For a constant flooding strength use \fB \-tau\fR 0. 

.BI "\-T"  " real" " 300   " 
 T is temperature, the value is needed if you want to do flooding 

.BI "\-alpha"  " real" " 1     " 
 Scale width of gaussian flooding potential with alpha2 

.BI "\-[no]restrain"  "no    "
 Use the flooding potential with inverted sign \- effects as quasiharmonic restraining potential

.BI "\-[no]hessian"  "no    "
 The eigenvectors and eigenvalues are from a Hessian matrix

.BI "\-[no]harmonic"  "no    "
 The eigenvalues are interpreted as spring constant

.BI "\-constF"  " string" " " 
 Constant force flooding: manually set the forces for the eigenvectors selected with \-flood (put in quotes! "1.0 2.3 5.1 \-3.1"). No other flooding parameters are needed when specifying the forces directly.

.SH SEE ALSO
.BR gromacs(7)

More information about \fBGROMACS\fR is available at <\fIhttp://www.gromacs.org/\fR>.
