.TH mk_angndx 1 "Mon 29 Aug 2005"
.SH NAME
mk_angndx
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3mk_angndx\fP
.BI "-s" " topol.tpr "
.BI "-n" " angle.ndx "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-type" " enum "
.SH DESCRIPTION
mk_angndx makes an index file for calculation of
angle distributions etc. It uses a run input file (
.B .tpx
) for the
definitions of the angles, dihedrals etc.
.SH FILES
.BI "-s" " topol.tpr" 
.B Input
 Generic run input: tpr tpb tpa xml 

.BI "-n" " angle.ndx" 
.B Output
 Index file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-type"  " enum" " angle" 
 Type of angle: 
.B angle
, 
.B g96-angle
, 
.B dihedral
, 
.B improper
, 
.B ryckaert-bellemans
or 
.B phi-psi


