.TH ngmx 1 "Mon 29 Aug 2005"
.SH NAME
ngmx
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3ngmx\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.SH DESCRIPTION
ngmx is the Gromacs trajectory viewer. This program reads a
trajectory file, a run input file and an index file and plots a
3D structure of your molecule on your standard X Window
screen. No need for a high end graphics workstation, it even
works on Monochrome screens.


The following features have been implemented:
3D view, rotation, translation and scaling of your molecule(s),
labels on atoms, animation of trajectories,
hardcopy in PostScript format, user defined atom-filters
runs on MIT-X (real X), open windows and motif,
user friendly menus, option to remove periodicity, option to
show computational box.


Some of the more common X command line options can be used:

-bg, -fg change colors, -font fontname, changes the font.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input
 Generic run input: tpr tpb tpa xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

\- Balls option does not work

\- Some times dumps core without a good reason

