.TH nmrun 1 "Mon 23 Jul 2001"
.SH NAME
nmrun
.B VERSION 3.0
.SH SYNOPSIS
\f3nmrun\fP
.BI "-s" " topol.tpr "
.BI "-m" " hessian.mtx "
.BI "-g" " nm.log "
.BI "-[no]h" ""
.BI "-[no]X" ""
.BI "-nice" " int "
.BI "-np" " int "
.BI "-[no]v" ""
.BI "-[no]compact" ""
.SH DESCRIPTION
nmrun builds a Hessian matrix from single conformation.
For usual Normal Modes-like calculations, make sure that
the structure provided is properly energy-minimised.
The generated matrix can be diagonalized by g_nmeig.
.SH FILES
.BI "-s" " topol.tpr" 
.B Input
 Generic run input: tpr tpb tpa 

.BI "-m" " hessian.mtx" 
.B Output
 Hessian matrix 

.BI "-g" " nm.log" 
.B Output
 Log file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-[no]X"  "    no"
 Use dialog box GUI to edit command line options

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-np"  " int" " 1" 
 Number of nodes, must be the same as used for grompp

.BI "-[no]v"  "    no"
 Verbose mode

.BI "-[no]compact"  "   yes"
 Write a compact log file

