.TH pdb2gmx 1 "Mon 29 Aug 2005"
.SH NAME
pdb2gmx
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3pdb2gmx\fP
.BI "-f" " eiwit.pdb "
.BI "-o" " conf.gro "
.BI "-p" " topol.top "
.BI "-i" " posre.itp "
.BI "-n" " clean.ndx "
.BI "-q" " clean.pdb "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-[no]merge" ""
.BI "-ff" " string "
.BI "-water" " enum "
.BI "-[no]inter" ""
.BI "-[no]ss" ""
.BI "-[no]ter" ""
.BI "-[no]lys" ""
.BI "-[no]asp" ""
.BI "-[no]glu" ""
.BI "-[no]his" ""
.BI "-angle" " real "
.BI "-dist" " real "
.BI "-[no]una" ""
.BI "-[no]ignh" ""
.BI "-[no]missing" ""
.BI "-[no]v" ""
.BI "-posrefc" " real "
.BI "-vsite" " enum "
.BI "-[no]heavyh" ""
.BI "-[no]deuterate" ""
.SH DESCRIPTION
This program reads a pdb file, reads
some database files, adds hydrogens to the molecules and generates
coordinates in Gromacs (Gromos) format and a topology in Gromacs format.
These files can subsequently be processed to generate a run input file.



The force fields in the distribution are currently:


oplsaa OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)

G43b1  GROMOS96 43b1 Vacuum Forcefield 

G43a1  GROMOS96 43a1 Forcefield 

G43a2  GROMOS96 43a2 Forcefield (improved alkane dihedrals)

G45a3  GROMOS96 45a3 Forcefield 

G53a5  GROMOS96 53a5 Forcefield 

G53a6  GROMOS96 53a6 Forcefield 

gmx    Gromacs Forcefield (a modified GROMOS87, see manual)

encads Encad all-atom force field, using scaled-down vacuum charges

encadv Encad all-atom force field, using full solvent charges


The corresponding data files can be found in the library directory
with names like ffXXXX.YYY. Check chapter 5 of the manual for more
information about file formats. By default the forcefield selection
is interactive, but you can use the 
.B -ff
option to specify
one of the short names above on the command line instead. In that
case pdb2gmx just looks for the corresponding file.


Note that a pdb file is nothing more than a file format, and it
need not necessarily contain a protein structure. Every kind of
molecule for which there is support in the database can be converted.
If there is no support in the database, you can add it yourself.


The program has limited intelligence, it reads a number of database
files, that allow it to make special bonds (Cys-Cys, Heme-His, etc.),
if necessary this can be done manually. The program can prompt the
user to select which kind of LYS, ASP, GLU, CYS or HIS residue she
wants. For LYS the choice is between LYS (two protons on NZ) or LYSH
(three protons, default), for ASP and GLU unprotonated (default) or
protonated, for HIS the proton can be either on ND1 (HISA), on NE2
(HISB) or on both (HISH). By default these selections are done
automatically. For His, this is based on an optimal hydrogen bonding
conformation. Hydrogen bonds are defined based on a simple geometric
criterium, specified by the maximum hydrogen-donor-acceptor angle
and donor-acceptor distance, which are set by 
.B -angle
and

.B -dist
respectively.


Option 
.B -merge
will ask if you want to merge consecutive chains
into one molecule definition, this can be useful for connecting chains
with a disulfide brigde or intermolecular distance restraints.


pdb2gmx will also check the occupancy field of the pdb file.
If any of the occupanccies are not one, indicating that the atom is
not resolved well in the structure, a warning message is issued.
When a pdb file does not originate from an X-Ray structure determination
all occupancy fields may be zero. Either way, it is up to the user
to verify the correctness of the input data (read the article!).


During processing the atoms will be reordered according to Gromacs
conventions. With 
.B -n
an index file can be generated that
contains one group reordered in the same way. This allows you to
convert a Gromos trajectory and coordinate file to Gromos. There is
one limitation: reordering is done after the hydrogens are stripped
from the input and before new hydrogens are added. This means that
you should not use 
.B -ignh
.


The 
.B .gro
and 
.B .g96
file formats do not support chain
identifiers. Therefore it is useful to enter a pdb file name at
the 
.B -o
option when you want to convert a multichain pdb file.



The option 
.B -vsite
removes hydrogen and fast improper dihedral
motions. Angular and out-of-plane motions can be removed by changing
hydrogens into virtual sites and fixing angles, which fixes their
position relative to neighboring atoms. Additionally, all atoms in the
aromatic rings of the standard amino acids (i.e. PHE, TRP, TYR and HIS)
can be converted into virtual sites, elminating the fast improper dihedral
fluctuations in these rings. Note that in this case all other hydrogen
atoms are also converted to virtual sites. The mass of all atoms that are
converted into virtual sites, is added to the heavy atoms.


Also slowing down of dihedral motion can be done with 
.B -heavyh

done by increasing the hydrogen-mass by a factor of 4. This is also
done for water hydrogens to slow down the rotational motion of water.
The increase in mass of the hydrogens is subtracted from the bonded
(heavy) atom so that the total mass of the system remains the same.
.SH FILES
.BI "-f" " eiwit.pdb" 
.B Input
 Generic structure: gro g96 pdb tpr tpb tpa xml 

.BI "-o" " conf.gro" 
.B Output
 Generic structure: gro g96 pdb xml 

.BI "-p" " topol.top" 
.B Output
 Topology file 

.BI "-i" " posre.itp" 
.B Output
 Include file for topology 

.BI "-n" " clean.ndx" 
.B Output, Opt.
 Index file 

.BI "-q" " clean.pdb" 
.B Output, Opt.
 Generic structure: gro g96 pdb xml 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-[no]merge"  "    no"
 Merge chains into one molecule definition

.BI "-ff"  " string" " select" 
 Force field, interactive by default. Use -h for information.

.BI "-water"  " enum" " spc" 
 Water model to use: with GROMOS we recommend SPC, with OPLS, TIP4P: 
.B spc
, 
.B spce
, 
.B tip3p
, 
.B tip4p
, 
.B tip5p
or 
.B f3c


.BI "-[no]inter"  "    no"
 Set the next 6 options to interactive

.BI "-[no]ss"  "    no"
 Interactive SS bridge selection

.BI "-[no]ter"  "    no"
 Interactive termini selection, iso charged

.BI "-[no]lys"  "    no"
 Interactive Lysine selection, iso charged

.BI "-[no]asp"  "    no"
 Interactive Aspartic Acid selection, iso charged

.BI "-[no]glu"  "    no"
 Interactive Glutamic Acid selection, iso charged

.BI "-[no]his"  "    no"
 Interactive Histidine selection, iso checking H-bonds

.BI "-angle"  " real" "    135" 
 Minimum hydrogen-donor-acceptor angle for a H-bond (degrees)

.BI "-dist"  " real" "    0.3" 
 Maximum donor-acceptor distance for a H-bond (nm)

.BI "-[no]una"  "    no"
 Select aromatic rings with united CH atoms on Phenylalanine, Tryptophane and Tyrosine

.BI "-[no]ignh"  "    no"
 Ignore hydrogen atoms that are in the pdb file

.BI "-[no]missing"  "    no"
 Continue when atoms are missing, dangerous

.BI "-[no]v"  "    no"
 Be slightly more verbose in messages

.BI "-posrefc"  " real" "   1000" 
 Force constant for position restraints

.BI "-vsite"  " enum" " none" 
 Convert atoms to virtual sites: 
.B none
, 
.B hydrogens
or 
.B aromatics


.BI "-[no]heavyh"  "    no"
 Make hydrogen atoms heavy

.BI "-[no]deuterate"  "    no"
 Change the mass of hydrogens to 2 amu

