.TH pdb2gmx 1 "Thu 28 Feb 2002"
.SH NAME
pdb2gmx
.B VERSION 3.1
.SH SYNOPSIS
\f3pdb2gmx\fP
.BI "-f" " eiwit.pdb "
.BI "-o" " conf.gro "
.BI "-p" " topol.top "
.BI "-i" " posre.itp "
.BI "-n" " clean.ndx "
.BI "-q" " clean.pdb "
.BI "-[no]h" ""
.BI "-[no]X" ""
.BI "-nice" " int "
.BI "-[no]merge" ""
.BI "-[no]inter" ""
.BI "-[no]ss" ""
.BI "-[no]ter" ""
.BI "-[no]lys" ""
.BI "-[no]asp" ""
.BI "-[no]glu" ""
.BI "-[no]his" ""
.BI "-angle" " real "
.BI "-dist" " real "
.BI "-posrefc" " real "
.BI "-[no]una" ""
.BI "-[no]sort" ""
.BI "-[no]H14" ""
.BI "-[no]ignh" ""
.BI "-[no]alldih" ""
.BI "-dummy" " enum "
.BI "-[no]heavyh" ""
.BI "-[no]deuterate" ""
.SH DESCRIPTION
This program reads a pdb file, lets you choose a forcefield, reads
some database files, adds hydrogens to the molecules and generates
coordinates in Gromacs (Gromos) format and a topology in Gromacs format.
These files can subsequently be processed to generate a run input file.



Note that a pdb file is nothing more than a file format, and it
need not necessarily contain a protein structure. Every kind of
molecule for which there is support in the database can be converted.
If there is no support in the database, you can add it yourself.


The program has limited intelligence, it reads a number of database
files, that allow it to make special bonds (Cys-Cys, Heme-His, etc.),
if necessary this can be done manually. The program can prompt the
user to select which kind of LYS, ASP, GLU, CYS or HIS residue she
wants. For LYS the choice is between LYS (two protons on NZ) or LYSH
(three protons, default), for ASP and GLU unprotonated (default) or
protonated, for HIS the proton can be either on ND1 (HISA), on NE2
(HISB) or on both (HISH). By default these selections are done
automatically. For His, this is based on an optimal hydrogen bonding
conformation. Hydrogen bonds are defined based on a simple geometric
criterium, specified by the maximum hydrogen-donor-acceptor angle
and donor-acceptor distance, which are set by 
.B -angle
and

.B -dist
respectively.


Option 
.B -merge
will ask if you want to merge consecutive chains
into one molecule, this can be useful for connecting chains with a
disulfide brigde.


pdb2gmx will also check the occupancy field of the pdb file.
If any of the occupanccies are not one, indicating that the atom is
not resolved well in the structure, a warning message is issued.
When a pdb file does not originate from an X-Ray structure determination
all occupancy fields may be zero. Either way, it is up to the user
to verify the correctness of the input data (read the article!).


During processing the atoms will be reordered according to Gromacs
conventions. With 
.B -n
an index file can be generated that
contains one group reordered in the same way. This allows you to
convert a Gromos trajectory and coordinate file to Gromos. There is
one limitation: reordering is done after the hydrogens are stripped
from the input and before new hydrogens are added. This means that
you should not use 
.B -ignh
.


The 
.B .gro
and 
.B .g96
file formats do not support chain
identifiers. Therefore it is useful to enter a pdb file name at
the 
.B -o
option when you want to convert a multichain pdb file.




.B -sort
will sort all residues according to the order in the
database, sometimes this is necessary to get charge groups
together.



.B -alldih
will generate all proper dihedrals instead of only
those with as few hydrogens as possible, this is useful for use with
the Charmm forcefield.


The option 
.B -dummy
removes hydrogen and fast improper dihedral
motions. Angular and out-of-plane motions can be removed by changing
hydrogens into dummy atoms and fixing angles, which fixes their
position relative to neighboring atoms. Additionally, all atoms in the
aromatic rings of the standard amino acids (i.e. PHE, TRP, TYR and HIS)
can be converted into dummy atoms, elminating the fast improper dihedral
fluctuations in these rings. Note that in this case all other hydrogen
atoms are also converted to dummy atoms. The mass of all atoms that are
converted into dummy atoms, is added to the heavy atoms.


Also slowing down of dihedral motion can be done with 
.B -heavyh

done by increasing the hydrogen-mass by a factor of 4. This is also
done for water hydrogens to slow down the rotational motion of water.
The increase in mass of the hydrogens is subtracted from the bonded
(heavy) atom so that the total mass of the system remains the same.
Reference Feenstra et al., J. Comput. Chem. 20, 786 (1999).
.SH FILES
.BI "-f" " eiwit.pdb" 
.B Input
 Generic structure: gro g96 pdb tpr tpb tpa 

.BI "-o" " conf.gro" 
.B Output
 Generic structure: gro g96 pdb 

.BI "-p" " topol.top" 
.B Output
 Topology file 

.BI "-i" " posre.itp" 
.B Output
 Include file for topology 

.BI "-n" " clean.ndx" 
.B Output, Opt.
 Index file 

.BI "-q" " clean.pdb" 
.B Output, Opt.
 Generic structure: gro g96 pdb 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-[no]X"  "    no"
 Use dialog box GUI to edit command line options

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-[no]merge"  "    no"
 Merge multiple chains into one molecule

.BI "-[no]inter"  "    no"
 Set the next 6 options to interactive

.BI "-[no]ss"  "    no"
 Interactive SS bridge selection

.BI "-[no]ter"  "    no"
 Interactive termini selection, iso charged

.BI "-[no]lys"  "    no"
 Interactive Lysine selection, iso charged

.BI "-[no]asp"  "    no"
 Interactive Aspartic Acid selection, iso charged

.BI "-[no]glu"  "    no"
 Interactive Glutamic Acid selection, iso charged

.BI "-[no]his"  "    no"
 Interactive Histidine selection, iso checking H-bonds

.BI "-angle"  " real" "    135" 
 Minimum hydrogen-donor-acceptor angle for a H-bond (degrees)

.BI "-dist"  " real" "    0.3" 
 Maximum donor-acceptor distance for a H-bond (nm)

.BI "-posrefc"  " real" "   1000" 
 Force constant for position restraints

.BI "-[no]una"  "    no"
 Select aromatic rings with united CH atoms on Phenylalanine, Tryptophane and Tyrosine

.BI "-[no]sort"  "   yes"
 Sort the residues according to database

.BI "-[no]H14"  "    no"
 Use 1-4 interactions between hydrogen atoms

.BI "-[no]ignh"  "    no"
 Ignore hydrogen atoms that are in the pdb file

.BI "-[no]alldih"  "    no"
 Generate all proper dihedrals

.BI "-dummy"  " enum" " none" 
 Convert atoms to dummy atoms: 
.B none
, 
.B hydrogens
or 
.B aromatics


.BI "-[no]heavyh"  "    no"
 Make hydrogen atoms heavy

.BI "-[no]deuterate"  "    no"
 Change the mass of hydrogens to 2 amu

