.TH sigeps 1 "Thu 16 Oct 2008"
.SH NAME
sigeps - convert c6/12 or c6/cn combinations to and from sigma/epsilon

.B VERSION 4.0
.SH SYNOPSIS
\f3sigeps\fP
.BI "-o" " potje.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-c6" " real "
.BI "-cn" " real "
.BI "-pow" " int "
.BI "-sig" " real "
.BI "-eps" " real "
.BI "-A" " real "
.BI "-B" " real "
.BI "-C" " real "
.BI "-qi" " real "
.BI "-qj" " real "
.BI "-sigfac" " real "
.SH DESCRIPTION
Sigeps is a simple utility that converts c6/c12 or c6/cn combinations
to sigma and epsilon, or vice versa. It can also plot the potential
in  file. In addition it makes an approximation of a Buckingham potential
to a Lennard Jones potential.
.SH FILES
.BI "-o" " potje.xvg" 
.B Output
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "no    "
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-[no]w"  "no    "
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "yes   "
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-c6"  " real" " 0.001 " 
 c6

.BI "-cn"  " real" " 1e-06 " 
 constant for repulsion

.BI "-pow"  " int" " 12" 
 power of the repulsion term

.BI "-sig"  " real" " 0.3   " 
 sig

.BI "-eps"  " real" " 1     " 
 eps

.BI "-A"  " real" " 100000" 
 Buckingham A

.BI "-B"  " real" " 32    " 
 Buckingham B

.BI "-C"  " real" " 0.001 " 
 Buckingham C

.BI "-qi"  " real" " 0     " 
 qi

.BI "-qj"  " real" " 0     " 
 qj

.BI "-sigfac"  " real" " 0.7   " 
 Factor in front of sigma for starting the plot

