.TH tpbconv 1 "Mon 29 Aug 2005"
.SH NAME
tpbconv
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3tpbconv\fP
.BI "-s" " topol.tpr "
.BI "-f" " traj.trr "
.BI "-e" " ener.edr "
.BI "-n" " index.ndx "
.BI "-o" " tpxout.tpr "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-time" " real "
.BI "-extend" " real "
.BI "-until" " real "
.BI "-[no]zeroq" ""
.BI "-[no]unconstrained" ""
.SH DESCRIPTION
tpbconv can edit run input files in three ways.


.B 1st.
by creating a run input file
for a continuation run when your simulation has crashed due to e.g.
a full disk, or by making a continuation run input file.
Note that a frame with coordinates and velocities is needed,
which means that when you never write velocities, you can not use
tpbconv and you have to start the run again from the beginning.
When pressure and/or Nose-Hoover temperature coupling is used
an energy file can be supplied to get an exact continuation
of the original run.



.B 2nd.
by creating a tpx file for a subset of your original
tpx file, which is useful when you want to remove the solvent from
your tpx file, or when you want to make e.g. a pure Ca tpx file.

.B WARNING: this tpx file is not fully functional
.

.B 3rd.
by setting the charges of a specified group
to zero. This is useful when doing free energy estimates
using the LIE (Linear Interactio Energy) method.
.SH FILES
.BI "-s" " topol.tpr" 
.B Input
 Generic run input: tpr tpb tpa xml 

.BI "-f" " traj.trr" 
.B Input, Opt.
 Full precision trajectory: trr trj 

.BI "-e" " ener.edr" 
.B Input, Opt.
 Generic energy: edr ene 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-o" " tpxout.tpr" 
.B Output
 Generic run input: tpr tpb tpa xml 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 0" 
 Set the nicelevel

.BI "-time"  " real" "     -1" 
 Continue from frame at this time (ps) instead of the last frame

.BI "-extend"  " real" "      0" 
 Extend runtime by this amount (ps)

.BI "-until"  " real" "      0" 
 Extend runtime until this ending time (ps)

.BI "-[no]zeroq"  "    no"
 Set the charges of a group (from the index) to zero

.BI "-[no]unconstrained"  "   yes"
 For a continuous trajectory, the constraints should not be solved before the first step (default)

