.TH trjcat 1 "Mon 29 Aug 2005"
.SH NAME
trjcat
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3trjcat\fP
.BI "-f" " traj.xtc "
.BI "-o" " trajout.xtc "
.BI "-n" " index.ndx "
.BI "-demux" " remd.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-tu" " enum "
.BI "-[no]xvgr" ""
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-prec" " int "
.BI "-[no]vel" ""
.BI "-[no]settime" ""
.BI "-[no]sort" ""
.BI "-[no]keeplast" ""
.BI "-[no]cat" ""
.SH DESCRIPTION
trjcat concatenates several input trajectory files in sorted order. 
In case of double time frames the one in the later file is used. 
By specifying 
.B -settime
you will be asked for the start time 
of each file. The input files are taken from the command line, 
such that a command like 
.B trjcat -o fixed.trr *.trr
should do 
the trick. Using 
.B -cat
you can simply paste several files 
together without removal of frames with identical time stamps.


One important option is inferred when the output file is amongst the
input files. In that case that particular file will be appended to
which implies you do not need to store double the amount of data.
Obviously the file to append to has to be the one with lowest starting
time since one can only append at the end of a file.


If the 
.B -demux
option is given, the N trajectories that are
read, are written in another order as specified in the xvg file.The xvg file should contain something like:


0  0  1  2  3  4  5

2  1  0  2  3  5  4

Where the first number is the time, and subsequent numbers point to
trajectory indices.
The frames corresponding to the numbers present at the first line
are collected into the output trajectory. If the number of frames in
the trajectory does not match that in the xvg file then the program
tries to be smart. Beware.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input, Mult.
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-o" " trajout.xtc" 
.B Output, Mult.
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-demux" " remd.xvg" 
.B Input, Opt.
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-tu"  " enum" " ps" 
 Time unit: 
.B ps
, 
.B fs
, 
.B ns
, 
.B us
, 
.B ms
, 
.B s
, 
.B m
or 
.B h


.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-b"  " time" "     -1" 
 First time to use (ps)

.BI "-e"  " time" "     -1" 
 Last time to use (ps)

.BI "-dt"  " time" "      0" 
 Only write frame when t MOD dt = first time (ps)

.BI "-prec"  " int" " 3" 
 Precision for .xtc and .gro writing in number of decimal places

.BI "-[no]vel"  "   yes"
 Read and write velocities if possible

.BI "-[no]settime"  "    no"
 Change starting time interactively

.BI "-[no]sort"  "   yes"
 Sort trajectory files (not frames)

.BI "-[no]keeplast"  "    no"
 keep overlapping frames at end of trajectory

.BI "-[no]cat"  "    no"
 do not discard double time frames

