.TH trjcat 1 "Thu 28 Feb 2002"
.SH NAME
trjcat
.B VERSION 3.1
.SH SYNOPSIS
\f3trjcat\fP
.BI "-o" " trajout.xtc "
.BI "-n" " index.ndx "
.BI "-[no]h" ""
.BI "-[no]X" ""
.BI "-nice" " int "
.BI "-tu" " enum "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-prec" " int "
.BI "-[no]vel" ""
.BI "-[no]settime" ""
.BI "-[no]sort" ""
.BI "-[no]cat" ""
.SH DESCRIPTION
trjcat concatenates several input trajectory files in sorted order. 
In case of double time frames the one in the later file is used. 
By specifying 
.B -settime
you will be asked for the start time 
of each file. The input files are taken from the command line, 
such that a command like 
.B trjcat -o fixed.trr *.trr
should do 
the trick. Using 
.B -cat
you can simply paste several files 
together without removal of frames with identical time stamps.
.SH FILES
.BI "-o" " trajout.xtc" 
.B Output
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-[no]X"  "    no"
 Use dialog box GUI to edit command line options

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-tu"  " enum" " ps" 
 Time unit: 
.B ps
, 
.B fs
, 
.B ns
, 
.B us
, 
.B ms
, 
.B s
, 
.B m
or 
.B h


.BI "-b"  " time" "     -1" 
 First time to use (ps)

.BI "-e"  " time" "     -1" 
 Last time to use (ps)

.BI "-dt"  " time" "      0" 
 Only write frame when t MOD dt = first time (ps)

.BI "-prec"  " int" " 3" 
 Precision for .xtc and .gro writing in number of decimal places

.BI "-[no]vel"  "   yes"
 Read and write velocities if possible

.BI "-[no]settime"  "    no"
 Change starting time interactively

.BI "-[no]sort"  "   yes"
 Sort trajectory files (not frames)

.BI "-[no]cat"  "    no"
 do not discard double time frames

