.TH trjconv 1 "Mon 29 Aug 2005"
.SH NAME
trjconv
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3trjconv\fP
.BI "-f" " traj.xtc "
.BI "-o" " trajout.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-fr" " frames.ndx "
.BI "-sub" " cluster.ndx "
.BI "-drop" " drop.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-tu" " enum "
.BI "-[no]w" ""
.BI "-[no]xvgr" ""
.BI "-skip" " int "
.BI "-dt" " time "
.BI "-dump" " time "
.BI "-t0" " time "
.BI "-timestep" " time "
.BI "-pbc" " enum "
.BI "-ur" " enum "
.BI "-center" " enum "
.BI "-box" " vector "
.BI "-shift" " vector "
.BI "-fit" " enum "
.BI "-ndec" " int "
.BI "-[no]vel" ""
.BI "-[no]force" ""
.BI "-trunc" " time "
.BI "-exec" " string "
.BI "-[no]app" ""
.BI "-split" " time "
.BI "-[no]sep" ""
.BI "-[no]ter" ""
.BI "-dropunder" " real "
.BI "-dropover" " real "
.SH DESCRIPTION
trjconv can convert trajectory files in many ways:


.B 1.
from one format to another


.B 2.
select a subset of atoms

.B 3.
remove periodicity from molecules


.B 4.
keep multimeric molecules together


.B 5.
center atoms in the box


.B 6.
fit atoms to reference structure


.B 7.
reduce the number of frames


.B 8.
change the timestamps of the frames 
(
.B -t0
and 
.B -timestep
)


.B 9.
cut the trajectory in small subtrajectories according
to information in an index file. This allows subsequent analysis of
the subtrajectories that could, for example be the result of a
cluster analysis. Use option 
.B -sub
.
This assumes that the entries in the index file are frame numbers and
dumps each group in the index file to a separate trajectory file.


.B 10.
select frames within a certain range of a quantity given
in an 
.B .xvg
file.


The program 
.B trjcat
can concatenate multiple trajectory files.



Currently seven formats are supported for input and output:

.B .xtc
, 
.B .trr
, 
.B .trj
, 
.B .gro
, 
.B .g96
,

.B .pdb
and 
.B .g87
.
The file formats are detected from the file extension.
The precision of 
.B .xtc
and 
.B .gro
output is taken from the
input file for 
.B .xtc
, 
.B .gro
and 
.B .pdb
,
and from the 
.B -ndec
option for other input formats. The precision
is always taken from 
.B -ndec
, when this option is set.
All other formats have fixed precision. 
.B .trr
and 
.B .trj

output can be single or double precision, depending on the precision
of the trjconv binary.
Note that velocities are only supported in

.B .trr
, 
.B .trj
, 
.B .gro
and 
.B .g96
files.


Option 
.B -app
can be used to
append output to an existing trajectory file.
No checks are performed to ensure integrity
of the resulting combined trajectory file.


Option 
.B -sep
can be used to write every frame to a seperate
.gro, .g96 or .pdb file, default all frames all written to one file.

.B .pdb
files with all frames concatenated can be viewed with

.B rasmol -nmrpdb
.


It is possible to select part of your trajectory and write it out
to a new trajectory file in order to save disk space, e.g. for leaving
out the water from a trajectory of a protein in water.

.B ALWAYS
put the original trajectory on tape!
We recommend to use the portable 
.B .xtc
format for your analysis
to save disk space and to have portable files.


There are two options for fitting the trajectory to a reference
either for essential dynamics analysis or for whatever.
The first option is just plain fitting to a reference structure
in the structure file, the second option is a progressive fit
in which the first timeframe is fitted to the reference structure 
in the structure file to obtain and each subsequent timeframe is 
fitted to the previously fitted structure. This way a continuous
trajectory is generated, which might not be the case when using the
regular fit method, e.g. when your protein undergoes large
conformational transitions.


Option 
.B -pbc
sets the type of periodic boundary condition
treatment:

* 
.B whole
puts the atoms in the box and then makes
broken molecules whole (a run input file is required).
Atom number 1 of each molecule will be inside the box.

* 
.B com
puts the center of mass of all 
.I residues

in the box. Not that this can break molecules that consist of
more than one residue (e.g. proteins).

* 
.B inbox
puts all the atoms in the box.

* 
.B nojump
checks if atoms jump across the box and then puts
them back. This has the effect that all molecules
will remain whole (provided they were whole in the initial
conformation), note that this ensures a continuous trajectory but
molecules may diffuse out of the box. The starting configuration
for this procedure is taken from the structure file, if one is
supplied, otherwise it is the first frame.

* 
.B cluster
clusters all the atoms in the selected index
such that they are all closest to the center of mass of the cluster
which is iteratively updated. Note that this will only give meaningful
results if you in fact have a cluster. Luckily that can be checked
afterwards using a trajectory viewer.


.B -pbc
is ignored when 
.B -fit
or 
.B -pfit
is set,
in that case molecules will be made whole.


Option 
.B -ur
sets the unit cell representation for options

.B whole
and 
.B inbox
of 
.B -pbc
.
All three options give different results for triclinc boxes and
identical results for rectangular boxes.

.B rect
is the ordinary brick shape.

.B tric
is the triclinic unit cell.

.B compact
puts all atoms at the closest distance from the center
of the box. This can be useful for visualizing e.g. truncated
octahedrons. The center for options 
.B tric
and 
.B compact

is 
.B tric
(see below), unless the option 
.B -center

is set differently.


Option 
.B -center
centers the system in the box. The user can
select the group which is used to determine the geometrical center.
The center options are:

.B tric
: half of the sum of the box vectors,

.B rect
: half of the box diagonal,

.B zero
: zero.
Use option 
.B -pbc whole
in addition to 
.B -center
when you
want all molecules in the box after the centering.


With 
.B -dt
it is possible to reduce the number of 
frames in the output. This option relies on the accuracy of the times
in your input trajectory, so if these are inaccurate use the

.B -timestep
option to modify the time (this can be done
simultaneously). For making smooth movies the program 
.B g_filter

can reduce the number of frames while using low-pass frequency
filtering, this reduces aliasing of high frequency motions.


Using 
.B -trunc
trjconv can truncate 
.B .trj
in place, i.e.
without copying the file. This is useful when a run has crashed
during disk I/O (one more disk full), or when two contiguous
trajectories must be concatenated without have double frames.



.B trjcat
is more suitable for concatenating trajectory files.


Option 
.B -dump
can be used to extract a frame at or near
one specific time from your trajectory.


Option 
.B -drop
reads an 
.B .xvg
file with times and values.
When options 
.B -dropunder
and/or 
.B -dropover
are set,
frames with a value below and above the value of the respective options
will not be written.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-o" " trajout.xtc" 
.B Output
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input, Opt.
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-fr" " frames.ndx" 
.B Input, Opt.
 Index file 

.BI "-sub" " cluster.ndx" 
.B Input, Opt.
 Index file 

.BI "-drop" " drop.xvg" 
.B Input, Opt.
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-tu"  " enum" " ps" 
 Time unit: 
.B ps
, 
.B fs
, 
.B ns
, 
.B us
, 
.B ms
, 
.B s
, 
.B m
or 
.B h


.BI "-[no]w"  "    no"
 View output xvg, xpm, eps and pdb files

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-skip"  " int" " 1" 
 Only write every nr-th frame

.BI "-dt"  " time" "      0" 
 Only write frame when t MOD dt = first time (ps)

.BI "-dump"  " time" "     -1" 
 Dump frame nearest specified time (ps)

.BI "-t0"  " time" "      0" 
 Starting time (ps) (default: don't change)

.BI "-timestep"  " time" "      0" 
 Change time step between input frames (ps)

.BI "-pbc"  " enum" " none" 
 PBC treatment (see help text for full description): 
.B none
, 
.B whole
, 
.B inbox
, 
.B nojump
, 
.B cluster
or 
.B com


.BI "-ur"  " enum" " rect" 
 Unit-cell representation: 
.B rect
, 
.B tric
or 
.B compact


.BI "-center"  " enum" " no" 
 Center atoms in box: 
.B no
, 
.B tric
, 
.B rect
or 
.B zero


.BI "-box"  " vector" " 0 0 0" 
 Size for new cubic box (default: read from input)

.BI "-shift"  " vector" " 0 0 0" 
 All coordinates will be shifted by framenr*shift

.BI "-fit"  " enum" " none" 
 Fit molecule to ref structure in the structure file: 
.B none
, 
.B rot+trans
, 
.B translation
or 
.B progressive


.BI "-ndec"  " int" " 3" 
 Precision for .xtc and .gro writing in number of decimal places

.BI "-[no]vel"  "   yes"
 Read and write velocities if possible

.BI "-[no]force"  "    no"
 Read and write forces if possible

.BI "-trunc"  " time" "     -1" 
 Truncate input trj file after this time (ps)

.BI "-exec"  " string" " " 
 Execute command for every output frame with the frame number as argument

.BI "-[no]app"  "    no"
 Append output

.BI "-split"  " time" "      0" 
 Start writing new file when t MOD split = first time (ps)

.BI "-[no]sep"  "    no"
 Write each frame to a separate .gro, .g96 or .pdb file

.BI "-[no]ter"  "    no"
 Use 'TER' in pdb file as end of frame in stead of default 'ENDMDL'

.BI "-dropunder"  " real" "      0" 
 Drop all frames below this value

.BI "-dropover"  " real" "      0" 
 Drop all frames above this value

