.TH trjorder 1 "Mon 29 Aug 2005"
.SH NAME
trjorder
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3trjorder\fP
.BI "-f" " traj.xtc "
.BI "-s" " topol.tpr "
.BI "-n" " index.ndx "
.BI "-o" " ordered.xtc "
.BI "-nshell" " nshell.xvg "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-b" " time "
.BI "-e" " time "
.BI "-dt" " time "
.BI "-[no]xvgr" ""
.BI "-na" " int "
.BI "-da" " int "
.BI "-[no]com" ""
.BI "-r" " real "
.SH DESCRIPTION
trjorder orders molecules according to the smallest distance
to atoms in a reference group. It will ask for a group of reference
atoms and a group of molecules. For each frame of the trajectory
the selected molecules will be reordered according to the shortest
distance between atom number 
.B -da
in the molecule and all the
atoms in the reference group. All atoms in the trajectory are written
to the output trajectory.


trjorder can be useful for e.g. analyzing the n waters closest to a
protein.
In that case the reference group would be the protein and the group
of molecules would consist of all the water atoms. When an index group
of the first n waters is made, the ordered trajectory can be used
with any Gromacs program to analyze the n closest waters.


If the output file is a pdb file, the distance to the reference target
will be stored in the B-factor field in order to color with e.g. rasmol.
.SH FILES
.BI "-f" " traj.xtc" 
.B Input
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-s" " topol.tpr" 
.B Input
 Structure+mass(db): tpr tpb tpa gro g96 pdb xml 

.BI "-n" " index.ndx" 
.B Input, Opt.
 Index file 

.BI "-o" " ordered.xtc" 
.B Output
 Generic trajectory: xtc trr trj gro g96 pdb 

.BI "-nshell" " nshell.xvg" 
.B Output, Opt.
 xvgr/xmgr file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-b"  " time" "      0" 
 First frame (ps) to read from trajectory

.BI "-e"  " time" "      0" 
 Last frame (ps) to read from trajectory

.BI "-dt"  " time" "      0" 
 Only use frame when t MOD dt = first time (ps)

.BI "-[no]xvgr"  "   yes"
 Add specific codes (legends etc.) in the output xvg files for the xmgrace program

.BI "-na"  " int" " 3" 
 Number of atoms in a molecule

.BI "-da"  " int" " 1" 
 Atom used for the distance calculation

.BI "-[no]com"  "    no"
 Use the distance to the center of mass of the reference group

.BI "-r"  " real" "      0" 
 Cutoff used for the distance calculation when computing the number of molecules in a shell around e.g. a protein

