.TH wheel 1 "Mon 29 Aug 2005"
.SH NAME
wheel
.B VERSION 3.3_beta_20050823
.SH SYNOPSIS
\f3wheel\fP
.BI "-f" " nnnice.dat "
.BI "-o" " plot.eps "
.BI "-[no]h" ""
.BI "-nice" " int "
.BI "-r0" " int "
.BI "-rot0" " real "
.BI "-T" " string "
.BI "-[no]nn" ""
.SH DESCRIPTION
wheel plots a helical wheel representation of your sequence.The input sequence is in the .dat file where the first line contains
the number of residues and each consecutive line contains a residuename.
.SH FILES
.BI "-f" " nnnice.dat" 
.B Input
 Generic data file 

.BI "-o" " plot.eps" 
.B Output
 Encapsulated PostScript (tm) file 

.SH OTHER OPTIONS
.BI "-[no]h"  "    no"
 Print help info and quit

.BI "-nice"  " int" " 19" 
 Set the nicelevel

.BI "-r0"  " int" " 1" 
 The first residue number in the sequence

.BI "-rot0"  " real" "      0" 
 Rotate around an angle initially (90 degrees makes sense)

.BI "-T"  " string" " " 
 Plot a title in the center of the wheel (must be shorter than 10 characters, or it will overwrite the wheel)

.BI "-[no]nn"  "   yes"
 Toggle numbers

