.gmxapi-extra-installs:
  variables:
    EXTRA_INSTALLS: python3-dev python3-networkx python3-setuptools python3-mpi4py python3-numpy python3-pip python3-pytest


.configure-gmxapi-template:
  extends:
    - .gmxapi-extra-installs
  variables:
    CMAKE_GMXAPI_OPTIONS: "-DGMX_PYTHON_PACKAGE=ON"
 
