.gcc-before-script-template:
  variables:
    COMPILER_MAJOR_VERSION: 7
    EXTRA_INSTALLS: ""

  before_script:
      - echo $EXTRA_INSTALLS
      - time apt-get -qq update
      - time apt-get -qqy --no-install-suggests --no-install-recommends install
          $EXTRA_INSTALLS
      - mkdir -p ccache
      - export CCACHE_BASEDIR=${PWD}
      - export CCACHE_DIR=${PWD}/ccache

