.build-gcc-template:
  variables:
    COMPILER_MAJOR_VERSION: 7
    BUILD_DIR: build-gcc
    CMAKE_COMPILER_SCRIPT: -DCMAKE_C_COMPILER=gcc-$COMPILER_MAJOR_VERSION -DCMAKE_CXX_COMPILER=g++-$COMPILER_MAJOR_VERSION
