include:
    - local: '/admin/ci-templates/.image-templates.yml'
    - local: '/admin/ci-templates/.build-cache-template.yml'
    - local: '/admin/ci-templates/.pull-cache-template.yml'
    - local: '/admin/ci-templates/.variables-template.yml'
    - local: '/admin/ci-templates/.build-template.yml'
    - local: '/admin/ci-templates/.test-runner-template.yml'
    - local: '/admin/ci-templates/.gcc-before-script.yml'
    - local: '/admin/ci-templates/.gcc-build-template.yml'
    - local: '/admin/ci-templates/.gcc-test-template.yml'
    - local: '/admin/ci-templates/.clang-build-template.yml'
    - local: '/admin/ci-templates/.clang-test-template.yml'
    - local: '/admin/ci-templates/.clang-before-script.yml'
    - local: '/admin/ci-templates/.documentation-before-script.yml'
    - local: '/admin/ci-templates/.tags-template.yml'
    - local: '/admin/ci-templates/.test-script-template.yml'
    - local: '/admin/ci-templates/.build-docs-template.yml'
    - local: '/admin/ci-templates/.cuda-gcc-build-template.yml'
    - local: '/admin/ci-templates/.build-mpi-template.yml'
    - local: '/admin/ci-templates/.build-gmxapi-template.yml'
    - local: '/admin/ci-templates/.regressiontest-template.yml'
    - local: '/admin/ci-templates/.release-template.yml'
