.release-version-template:
  image: biophysics/gcc-gromacs
  stage: configure-build

  variables:
    KUBERNETES_CPU_LIMIT: 1
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_MEMORY_LIMIT: 2Gi

  only:
    refs:
      - merge_requests
      - schedules
      - web
    variables:
      - $GROMACS_RELEASE
  script:
    - cmake -P cmake/gmxVersionInfo.cmake &> version.json

  artifacts:
    paths:
      - version.json


.release-verify-template:
  image: biophysics/gcc-gromacs
  stage: release-verify

  variables:
    KUBERNETES_CPU_LIMIT: 1
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_MEMORY_LIMIT: 2Gi

  only:
    refs:
      - merge_requests
      - schedules
      - web
    variables:
      - $GROMACS_RELEASE
  script:
    - VERSION=`cat version.json |
        python3 -c "import json,sys; print(json.load(sys.stdin)['version'])"`
    - if [[ $GROMACS_RELEASE != "true" ]] ; then
          VERSION=$VERSION-dev ;
      fi
    - REGTEST_COMPARE=`cat version.json |
        python3 -c "import json,sys; print(json.load(sys.stdin)['regressiontest-md5sum'])"`
    - SOURCENAME=gromacs-$VERSION
    - SOURCETARBALL=$SOURCENAME.tar.gz
    - SOURCE_MD5SUM=`md5sum $SOURCETARBALL | awk '{print $1}'`
    - REGTESTNAME=regressiontests-$VERSION
    - REGTESTTARBALL=$REGTESTNAME.tar.gz
    - REGTEST_MD5SUM=`md5sum $REGTESTTARBALL | awk '{print $1}'`
    - echo "$SOURCETARBALL md5sum = $SOURCE_MD5SUM"
    - echo "$REGTESTTARBALL md5sum = $REGTEST_MD5SUM"
    - echo "$REGTESTTARBALL reference md5sum = $REGTEST_COMPARE"
    - if [[ $REGTEST_COMPARE != $REGTEST_MD5SUM && $GROMACS_RELEASE == "true" ]] ; then
      echo "Mismatch in regressiontest md5sums";
      exit 1;
      fi
