.test-base-template:
   variables:
       BUILD_DIR: build
   # Docker image uploaded to dockerhub by user eriklindahl
   # TODO: Get DockerFile for admin/dockerfiles
   image: biophysics/gcc-gromacs
   stage: test
   retry:
    max: 2

