.test-script-template:
   script:
     - cd $BUILD_DIR
     - ctest -D ExperimentalTest --output-on-failure | tee ctestLog.log || true
     - awk '/The following tests FAILED/,/^Errors while running CTest|^$/'
          ctestLog.log | tee ctestErrors.log
     - xsltproc scripts/CTest2JUnit.xsl Testing/`head -n 1 < Testing/TAG`/Test.xml > JUnitTestResults.xml
     - if [ -s ctestErrors.log ] ; then
         echo "Error during running ctest";
         exit 1;
       fi
     - cd ..
   artifacts:
     reports:
       junit: $BUILD_DIR/JUnitTestResults.xml
     paths:
         - $BUILD_DIR/Testing
         - $BUILD_DIR/tests
     when: always
     expire_in: 1 week

.test-regressiontests-template:
    variables:
      - TOTAL_RANK_NUMBER: 2
      - MPI_RANK_NUMBER: 2
      - PME_RANK_NUMBER: 0
      - MPI_RUN_COMMAND: ""
      - DOUBLE: ""
    only:
      - refs
      - schedules
      - merge_requests
    script:
      - tar xzf gmx-regressiontests.tar.gz
      - source $INSTALL_DIR/bin/GMXRC
      - cd regressiontests
      - perl gmxtest.pl -np $TOTAL_RANK_NUMBER -nt $MPI_RANK_NUMBER -npme $PME_RANK_NUMBER
        $DOUBLE $MPI_RUN_COMMAND
