#!/bin/csh -f

set out = $GMXHOME/complete
set dir = $cwd

echo Generating tcsh completions

if ( -f $out) then
  cd $GMXHOME
  mv complete \#complete\#
endif
touch $out

cd $GMXHOME/bin/$GMXCPU
set PROGRAMS = [a-z]*
cd $dir

printf 'if ( \$shell == \"/bin/tcsh\" ) then\n' >> $out

foreach i ( $PROGRAMS )
  if ( ( $i != "average" ) && ( $i != "luck" ) ) then
    $i -man completion >& /dev/null
    cat $i.completion >> $out
    \rm $i.completion
  endif
end

printf "endif\n" >> $out

#last line
