#!/bin/csh -f

set out = $GMXHOME/complete
set dir = $cwd

echo Generating tcsh completions

if ( -f $out) then
  cd $GMXHOME
  mv complete \#complete\#
endif
touch $out

cd $GMXHOME/bin/$GMXCPU 
set PROGRAMS = [a-z]*
cd $dir

echo "if ( "'$shell'" == /bin/tcsh ) then" >> $out

foreach program ( $PROGRAMS )
  if ( ( $program != "average" ) && ( $program != "luck" ) ) then
    $GMXHOME/bin/$GMXCPU/$program -man completion >& /dev/null
    cat $program.completion >> $out
    \rm $program.completion
  endif
end

echo "endif" >> $out

#last line
