#!/bin/csh

setenv HTML	$GMXHOME/html
if ( ! -d $HTML ) mkdir $HTML
setenv GIFDIR   $HTML/gif
if ( ! -d $GIFDIR ) ln -s ~gmx/public_html/gif $GIFDIR
setenv HTMLOL   $HTML/online$VER
if ( ! -d $HTMLOL ) mkdir $HTMLOL
setenv	INDEX	$HTML/online_index$VER.html
if ( -f $INDEX ) \rm $INDEX

cat > $INDEX << EOD
<html>
<h1>Index</h1>
<IMG SRC="gif/rainbow.gif" WIDTH=100% HEIGHT=7>
<h3>General</h3>
<ul>
<li><A HREF="changes1.6.html" TARGET="bottom" >New features</a>
<p>
<li><A HREF="online1.6/flow.html" TARGET="right" >Flow chart</a>
<p>
<li><A HREF="online1.6/files.html" TARGET="right" >File formats</a>
<p>
<li><A HREF="online1.6/mdp_opt.html" TARGET="right" >mdp options</a>
<p>
<li><A HREF="online1.6/count.html" TARGET="right" >Top of the pops</a>
</ul>
<IMG SRC="gif/rainbow.gif" WIDTH=100% HEIGHT=7>
<h3>Programs</h3>
<ul>
<li><A HREF="online1.6/general.html" TARGET="right" >General</a>
<p>
EOD

cd 	$GMXHOME/bin/$CPU
foreach i ( * )
  if ( ( -x $i ) && ( $i != "g_potential" ) && ( $i != "my_dssp" ) ) then
    $i -man 2
    if ( -f $i.html ) then 
      if ( -f $HTMLOL/$i.html ) \rm $HTMLOL/$i.html
      mv $i.html $HTMLOL
      cat >> $INDEX << EOK
<li><a href="online$VER/$i.html" TARGET="right">$i</a>
EOK
    endif
  endif
end

cat >> $INDEX << EOM
</ul>
<IMG SRC="gif/rainbow.gif" WIDTH=100% HEIGHT=7>
</HTML>
EOM

echo "New html pages in $HTML (file:/$INDEX)"

#last line
