#!/bin/csh -f

setenv VER 	2.0
setenv HTML	$GMXHOME/html
if ( ! -d $HTML ) mkdir $HTML
setenv MANDIR   online
setenv HTMLOL   $HTML/$MANDIR
if ( ! -d $HTMLOL ) mkdir $HTMLOL
setenv	INDEX	$HTML/$MANDIR.html
if ( -f $INDEX ) \rm $INDEX

cat > $INDEX << EOD
<HTML>
<TITLE>GROMACS $VER manual </TITLE>
<BODY>
<H1>GROMACS $VER manual</H1>
<TABLE BORDER=1 CELLSPACING=0 CELLPADDING=10>
<TR>
<TD VALIGN=top WIDTH="25%">
<h3>General</h3>
<A HREF="changes$VER.html">New features</a>
<br>
<br><A HREF="$MANDIR/getting_started.html">Getting Started</a>
<br>
<br><A HREF="$MANDIR/flow.html" >Flow chart</a>
<br>
<br><A HREF="$MANDIR/files.html" >File formats</a>
<br>
<br><A HREF="$MANDIR/mdp_opt.html" >mdp options</a>
<br>
<br><A HREF="$MANDIR/count.html" >Top of the pops</a>
</TD>
<TD VALIGN=top WIDTH="75%">
<h3>Programs</h3>
<multicol cols=5> 
<A HREF="$MANDIR/options.html" >Options</a>
<br>
EOD

cd 	$GMXHOME/bin/$CPU
foreach i ( * )
  if ( ( -x $i ) && ( $i != "my_dssp" ) && ( $i != "luck" ) ) then
    echo -n "$i "
    cd $HTMLOL
    $GMXHOME/bin/$CPU/$i -quiet -man html >& /dev/null
      cat >> $INDEX << EOK
<br><a href="$MANDIR/$i.html">$i</a>
EOK
    endif
    cd 	$GMXHOME/bin/$CPU
  endif
end

cat >> $INDEX << EOM
</multicol>
</TD>
</TR>
</TABLE>
</BODY>
</HTML>
EOM

echo ""
echo "New html pages in $HTML (file:/$INDEX)"

#last line
